### ISSUE TITLE
json key Distinguish between Uppercase lowercase

### ISSUE THREAD

**Issue by zyz** [rpgmaker/NetJSON#100]
public class Test{
    public int Id{ get; set; }
}
var jsonStr = "{\"id\":1}";
var t = NetJSON.NetJSON.Deserialize<Test>(jsonStr);

t.Id equal defaultvalue 0

**Comment by rpgmaker** [comment]
Just need to add the following to your code before calling deserialization logic.

NetJSON.CaseSensitive = false

By default it is case sensitive for properties and fields.

Thanks,

**Comment by rpgmaker** [comment]
You can reopen if it does not work for you.

Thanks,
