### ISSUE TITLE
Need instancing instead of static usage

### ISSUE THREAD

**Issue by alikalfaoglu** [rpgmaker/NetJSON#102]
For multithreaded process environment, such as a web process, different serialization options may be required for different threads. Statically defined options are not suitable for this type of usage.

**Comment by rpgmaker** [comment]
Would having it static thread scope work?

Thanks,

**Comment by rpgmaker** [comment]
In most cases you will most likely reuse the same option across the board for a request. Most of the option available do not give different result in term of serialization except for maybe date handling. 

Everything else can be enabled without causing issue.

I will look into instance as a way of using options but it will be require a bit more work to adapt the current code base to that idea.

Thanks,

**Comment by alikalfaoglu** [comment]
Different options may be required for different threads in same process. For ex., if you're serializing an object to re-use it again within your project, you may well include type name in the serialized content to ease some scenarios. But if you're sending the content to another platform that may really cause some trouble.

As far as I tested, performance is great, if you can handle this issue, i'll replace Newtonsoft with NetJSON. Also planning to replace our WCF netTCP based service systems' datacontract serialization with NetJSON. Cause it's performance is worth doing that. Our project is really big, we'll gain a lot :)

By the way, thanks for quick response..

**Comment by rpgmaker** [comment]
Just an update. I am working on it. It requires moving a few things around.

Thanks,

**Comment by alikalfaoglu** [comment]
Any progress?

**Comment by rpgmaker** [comment]
I made some progress on it. Just had not had enough time to go back and test it yet. I will try to get it tested by the end of week. Want to make sure I dont create new bugs due to the changes and moving things around. I only checked in the initial state of what the signature will look here but all full code is not in yet. https://github.com/rpgmaker/NetJSON/commit/2d9338c42d712739efe011a4f2e413a2e0ce21bf

Thanks for been patient

**Comment by rpgmaker** [comment]
Here is the initially checkin that i made so far. It is missing the logic for controller $type per serialization, but most of the support options are now useable as NetJSONSettings and the rest that are not customizable and global are left as they are such as GeneratingAssembly. 

https://github.com/rpgmaker/NetJSON/commit/6bc9fd49c92fb9df1dbaeea6bb20d9da3ded131a

Let me know if this is what you were expecting.

Thanks,

**Comment by alikalfaoglu** [comment]
Due to my initial tests, it is working fine. Thanks for your support..

**Comment by rpgmaker** [comment]
i will close it and finish up the implementation for controlling IncludeTypeInformation which is used for Poly.

Thanks,
