### ISSUE TITLE
.Net Core support

### ISSUE THREAD

**Issue by martonx** [rpgmaker/NetJSON#105]
Hi,

Is NetJson .Net Core compatible?

**Comment by rpgmaker** [comment]
At this time it is not. I will have to look into the support of reflection
emit. If it has enough support then I can port it over.

Thanks,

**Comment by rpgmaker** [comment]
It looks like there is support for it. So I will play around  with it to see how much will work. 

Thanks,

**Comment by rpgmaker** [comment]
Sorry for the late reply. I am working on porting to .Net Core now.

**Comment by rpgmaker** [comment]
Please. I have the support for .net core: https://github.com/rpgmaker/NetJSON/commit/0dfcd4292a425b608867d0f2a9f531b1e4943c0f


Thanks,
