### ISSUE TITLE
Can you please put into WIKI info how to beautify serialized JSON string?

### ISSUE THREAD

**Issue by hhblaze** [rpgmaker/NetJSON#106]
Can you please put into WIKI info how to beautify serialized JSON string?
Thank you!

**Comment by rpgmaker** [comment]
To be honest, this is out of scope for the idea of what netjson suppose to do. Focus is on performance and adding option to make string look clear will only slow things down. Have you considered calling a third party library after serialize is completed?

Since most of the code is cil, it will be a little harder to just add spacing and tabs even if it is driven by a Flag that is off by default.

Let me know what you think and if you are open to the idea of submitting a pull request for it.

Thanks,

**Comment by hhblaze** [comment]
When I have already NetJSON serialized string I call such extension on it:

```C#
        public static string BeautifyJSONString(this string s)
        {
            StringBuilder sb = new StringBuilder();
            int horizontal = 0;

            int[] horizonts = new int[10000];
            int hrIndex = -1;
            bool CarriageReturn = false;

            foreach (var c in s)
            {
                switch (c)
                {                    
                    case '{':
                    case '[':
                        sb.Append(c);
                        hrIndex++;
                        horizonts[hrIndex] = horizontal;
                        CarriageReturn = true;
                        break;
                    case '}':
                    case ']':
                        CarriageReturn = false;
                        sb.Append('\n');
                        horizontal = horizonts[hrIndex];
                        hrIndex--;
                        for (int i = 0; i < horizontal; i++)
                        {
                            sb.Append(' ');
                        }
                        sb.Append(c);
                        break;
                    case ',':
                        sb.Append(c);
                        CarriageReturn = true;

                        break;
                    default:
                        if (CarriageReturn)
                        {
                            CarriageReturn = false;
                            sb.Append('\n');
                            horizontal = horizonts[hrIndex] + 1;
                            for (int i = 0; i < horizontal; i++)
                            {
                                sb.Append(' ');
                            }
                        }
                        sb.Append(c);
                        break;
                }

                horizontal++;
            }

            return sb.ToString();
        }
```

**Comment by rpgmaker** [comment]
Do you want me to integrate the above code into the source to allow beautify of json?

Thanks,

**Comment by hhblaze** [comment]
That's definitely up to you...

**Comment by hhblaze** [comment]
and yes, I allow

**Comment by rpgmaker** [comment]
Thanks, I will consider using it. Since I am too lazy to create one. 😀

**Comment by rpgmaker** [comment]
I have extended the NetJSONSettings class to include Format as an option. So using the NetJSONFormat.Prettify will call the function that you gave me. Commit can be found here: https://github.com/rpgmaker/NetJSON/issues/107

**Comment by hhblaze** [comment]
Thank you very much, I will wait for NuGet version

**Comment by rpgmaker** [comment]
I have update the nuget package to include the latest code.

**Comment by hhblaze** [comment]
Thank you, it works!

var prettifiedString = NetJSON.NetJSON.Serialize(obj2ser,new NetJSON.NetJSONSettings { Format = NetJSON.NetJSONFormat.Prettify });

**Comment by hhblaze** [comment]
As an abstract question to you...
Have you thought about implementing protobuf protocol based on your beautiful reflection engine?

**Comment by rpgmaker** [comment]
I have already implemented my protocol that compete with protobuf here: https://github.com/rpgmaker/MessageShark

**Comment by rpgmaker** [comment]
You can see the result here: http://theburningmonk.com/benchmarks/

**Comment by hhblaze** [comment]
Wow, will take a look - thank you!
