### ISSUE TITLE
Models with a constructor are not supported

### ISSUE THREAD

**Issue by NimaAra** [rpgmaker/NetJSON#109]
Given: 
```csharp
public class Person
{
    public string Name { get; }
    public int Age { get; }

    public Person(string first, int age)
    {
        Name = first;
        Age = age;
    }
}
```

When trying to serialize using: 

```csharp
var result = NetJSON.NetJSON.Serialize(new Person("Jack", 12));
```

I get the: 
> "The type initializer for 'NetJSONCachedSerializer`1' threw an exception."

Stack: 
> "   at NetJSON.NetJSON.GetSerializer[T]()
   at NetJSON.NetJSON.Serialize[T](T value)
   at UserQuery.<>c.<Main>b__1_0(Object _, Person data) in C:\Users\admin\AppData\Local\Temp\LINQPad5\_keedptxm\query_mnmzjb.cs:line 49"

**Comment by rpgmaker** [comment]
Unfortunately at this time, i don't currently support class/struct without a default constructor. Calling FormatterServices.GetUninitializedObject is too expensive, so for now you will need to have a default constructor to use NetJSON.

**Comment by NimaAra** [comment]
Thanks for the reply, unfortunately the ability to serialize immutable models are important to me and at this moment JSON.NET remains the one of the very few serializers which can achieve this.

`FormatterServices.GetUninitializedObject` is quite fast (of course fast being relative) in fact I have a little helper method for creating objects and have benchmarking somewhere beating the perf against any other conventional methods including `new(T)`. It uses a combination of `Compiled Expressions`, `FastMember (IL Weaving)` and for fallback `FormatterServices.GetUninitializedObject` (compiled expression). 

I have not had a look at the source code for `NetJSON` but here's the method in case in can be of any benefit to you:

 ```csharp
public static class New<T>
{
    // ReSharper disable once UnusedMember.Local
    private static readonly Dictionary<Type, Func<T>> FuncCache = new Dictionary<Type, Func<T>>();

    /// <summary>
    /// Get an instance of <typeparamref name="T"/>.
    /// <see cref="http://stackoverflow.com/a/16162809/1226568"/>
    /// </summary>
    /// <typeparam name="T">
    /// Type of object to instantiate which can 
    /// be any type (except an array) or even without a default constructor.
    /// </typeparam>
    public static readonly Func<T> MakeInstance = Creator();

    private static Func<T> Creator()
    {
        var type = typeof(T);

        Func<T> result;
        if (FuncCache.TryGetValue(type, out result)) { return result; }

        if (type.IsArray)
        {
            throw new NotSupportedException("Arrays are not supported, consider using a List or a Collection");
        }

        if (type == typeof(string))
        {
            result = Expression.Lambda<Func<T>>(Expression.Constant(string.Empty)).Compile();
        }
        else
        {
            var accessor = type.GetAccessor();
            if (accessor.CreateNewSupported)
            {
                result = () => (T)accessor.CreateNew();
            }
            else if (type.HasDefaultConstructor())
            {
                result = Expression.Lambda<Func<T>>(Expression.New(type)).Compile();
            }
            else if (type.IsGenericList())
            {
                var genericArg = type.GetGenericArguments()[0];
                result = () => (T)New.MakeList(genericArg);
            }
            else
            {
                result = () => (T)FormatterServices.GetUninitializedObject(type);
            }
        }

        FuncCache[type] = result;
        return result;
    }
}

  public static class New
  {
      public static readonly Func<Type, IList> MakeList = type => MakeListImpl(type)();

      private static readonly ConcurrentDictionary<Type, Func<IList>> Cache = new ConcurrentDictionary<Type, Func<IList>>();
      private static Func<IList> MakeListImpl(Type genericArg)
      {
          Func<IList> result;
          if (Cache.TryGetValue(genericArg, out result)) { return result; }

          var concreteType = typeof(List<>).MakeGenericType(genericArg);

          result = Expression.Lambda<Func<IList>>(Expression.New(concreteType)).Compile();
          Cache[genericArg] = result;
          return result;
      }
  }
```

**Comment by rpgmaker** [comment]
Thanks for suggestions. At the moment I do inline the construction of the class and structure in the cil that is generated. I will think about allowing non constructors by having a NetJsonSettings flag that will be off by default and when set I can use the formatter for construction of class as needed.

Thanks,

**Comment by NimaAra** [comment]
Brilliant! looking forward to this feature.

Thank you.

**Comment by rpgmaker** [comment]
Please test again. Thanks,

**Comment by NimaAra** [comment]
Thanks for adding this. Serialization is working fine however I am unable to deserialize.

Given the model:

```csharp
public sealed class Person
{
    public Person(string name, int age)
    {
        this.Name = name;
        this.Age = age;
    }

    public string Name { get; }
    public int Age { get; }
}
```

And the test:

```csharp
[TestMethod]
public void TestModelWithConstructor()
{
    var model = new Person("John", 12);

    var json = NetJSON.Serialize(model);

    var settings = new NetJSONSettings {IncludeTypeInformation = true};
    var deserializedModel = NetJSON.Deserialize<Person>(json, settings);
    Assert.AreEqual(deserializedModel.Name, "John");
    Assert.AreEqual(deserializedModel.Age, 12);
}
```

The assertions fail.

**Comment by rpgmaker** [comment]
Sorry will fix it today.

Thanks

**Comment by NimaAra** [comment]
Hi,

Running against **1.1.0.3** the above still fails. Looks like it expects the properties to have setters which is against my requirement of supporting immutable types.

Thanks,

**Comment by rpgmaker** [comment]
It is not fixed yet. I missed it

**Comment by rpgmaker** [comment]
I just realized that the issue is fixed. The problem you are having is with not having a setter/private setter. NetJSON does not support non-public setter, members, class, and structs.

Thanks,

**Comment by rpgmaker** [comment]
The only way to make this work with my code generation is to create delegates that is callable from the current cil code. I might do that as long as the class it is a public class. Give me some time to think about the implementation, will look into it this weekend.

Thanks,

**Comment by rpgmaker** [comment]
Create a new issue with the proper title in regards to setters and getters.

Thanks,

**Comment by NimaAra** [comment]
Yes the idea behind this issue was to support immutable types otherwise I could just stick to using POCOs.

I agree the title is misleading I will open a new issue.
