### ISSUE TITLE
NetJSON hangs in eternal loop

### ISSUE THREAD

**Issue by binis2** [rpgmaker/NetJSON#110]
Hello there

I found a case when NetJSON hangs in eternal loop with the attached json

Here is my json classes

    public class Root
    {
        public Data data { get; set; }
    }

    public class Data
    {
        public Data2 data { get; set; }
    }

    public class Data2
    {
        public Dictionary<String, Sport> sport { get; set; }
    }

    public class Sport
    {
        public int id { get; set; }
        public string name { get; set; }
        public Dictionary<String, Region> region { get; set; }
    }

    public class Region
    {
        public int id { get; set; }
        public string name { get; set; }
        public Dictionary<String, Competition> competition { get; set; }
    }

    public class Competition
    {
        public int id { get; set; }
        public string name { get; set; }
        public Dictionary<String, Game> game { get; set; }
    }

    public class Game
    {
        public int id { get; set; }
        public int start_ts { get; set; }
        public string team1_name { get; set; }
        public string team2_name { get; set; }
        public int type { get; set; }
        public Info info { get; set; }
        public int markets_count { get; set; }
        public int is_blocked { get; set; }
        public Dictionary<String, Stat> stats { get; set; }
        public bool is_stat_available { get; set; }
    }

    public class Info
    {
        public string current_game_state { get; set; }
        public string current_game_time { get; set; }
        public string add_minutes { get; set; }
        public string score1 { get; set; }
        public string score2 { get; set; }
        public string shirt1_color { get; set; }
        public string shirt2_color { get; set; }
        public string short1_color { get; set; }
        public string short2_color { get; set; }
    }

    public class Stat
    {
        public int? team1_value { get; set; }
        public int? team2_value { get; set; }
    }

The problem is in parsing Stat. If I comment team*_value properties the json is parsed fine

Keep up the good work.

Best Regards,
Binis 

[netjson_test.txt](https://github.com/rpgmaker/NetJSON/files/320364/netjson_test.txt)

**Comment by rpgmaker** [comment]
Wow. That is a really complex json class structure. My guess is that I am not properly handling null values passed to them. 

Thanks for the find, will try to fix this weekend

**Comment by rpgmaker** [comment]
The issue was indeed having null values in null able int. I got caught up trying to resolve some performance issues. I will give you updates by Monday.

Thanks,

**Comment by rpgmaker** [comment]
The reason there is an infinite loop is because you are mixing data types. Your stats object team1_value and team2_value is represented as both int and string. It confused the serializer since i don't support reading a field as two different type and also because the data type determine how to read the json data not the other way around.

That explains why it works when you remove the two field/property.

I am going to close this issue since it is not a supported feature of NetJSON. I will try to look into supporting it in the feature. If you find that my reasoning for closing this issue is not ok.

Thanks,
