### ISSUE TITLE
Performance decreased

### ISSUE THREAD

**Issue by amacal** [rpgmaker/NetJSON#111]
Just tried to compare static and dynamic deserialization and found out that deserialization using NetJSON slowed down.

```` text
Newtonsoft-static  : 00:00:19.3743379
Newtonsoft-dynamic : 00:00:33.1510260
Jil-static         : 00:00:04.7653259
Jil-dynamic        : 00:00:14.9730451
NetJSON-static     : 00:00:16.1322889
````

Here is the source code with used json and model:

https://github.com/amacal/jynd/blob/master/sources/Jynd.Benchmark/Program.cs

**Comment by rpgmaker** [comment]
Can you set NetJSON.UseStringOptimization to true and let me know if there is any difference.

Thanks,

**Comment by rpgmaker** [comment]
Can also try to set NetJSON.QuoteType to SingleQuote. Without this option, it will try to auto detect the quote been used. I have added a lot of functionality that needs to disabled or turn on if you are doing a comparison to jil. Examples is case sensitive is false, including field is enabled by default. To do a comparison, you will need to turn on same option for jil and newtonsoft.

Thanks,

**Comment by NimaAra** [comment]
@amacal try replacing `DateTime.Now` with `Stopwatch` for any benchmarking.

@rpgmaker enabling the extra options as below:

```csharp
private static TimeSpan UseNetJsonStatic(string data)
{
    NetJSON.NetJSON.UseStringOptimization = true;
    NetJSON.NetJSON.QuoteType = NetJSON.NetJSONQuote.Single;

    var sw = Stopwatch.StartNew();

    for (int i = 0; i < 1000000; i++)
    {
        Check(NetJSON.NetJSON.Deserialize<Person>(data));
    }

    return sw.Elapsed;
}
```
Results in:
```
Newtonsoft-static  : 00:00:17.1500715
Newtonsoft-dynamic : 00:00:29.4008869
Jil-static         : 00:00:04.4158444
Jil-dynamic        : 00:00:12.3818057
NetJSON-static     : 00:00:12.3572828
```

**Comment by rpgmaker** [comment]
Thanks for the test. I will look into what has changed overtime. I guess after I introduced the NetJsonSettings things changed since I removed a lot of inline, settings cannot be attached to generated assembly anymore.

**Comment by rpgmaker** [comment]
I figured out why it slowed down. It was because of the string comparison function that I added

**Comment by NimaAra** [comment]
That is great! FYI, I went all the way back to **1.0.15** with the same sort of result.

Do you knew when you added it and got a link to the source?

**Comment by rpgmaker** [comment]
I am going to check in the fix soon. I also made some improvements. I also noticed that the result are more accurate when gc.collect after every method. It prevent any of the methods from benefiting from previous allocations

**Comment by rpgmaker** [comment]
Also for the serialize methodso in netjson using the settings parameter is better since internally it always initialize it.

**Comment by rpgmaker** [comment]
Please test again. I change the Main() method to use GC methods prior to every call for accurate timer and i also used the StopWatch instead.


public static void Main()
        {
            string data = Data.Replace('\'', '\"');


            GC.Collect();
            GC.WaitForPendingFinalizers();
            Console.WriteLine("Jil-static         : {0}", UseJilStatic(data));
            GC.Collect();
            GC.WaitForPendingFinalizers();
            Console.WriteLine("Jil-dynamic        : {0}", UseJilDynamic(data));
            GC.Collect();
            GC.WaitForPendingFinalizers();
            Console.WriteLine("Newtonsoft-static  : {0}", UseNewtonsoftStatic(data));
            GC.Collect();
            GC.WaitForPendingFinalizers();
            Console.WriteLine("Newtonsoft-dynamic : {0}", UseNewtonsoftDynamic(data));
            GC.Collect();
            GC.WaitForPendingFinalizers();
            Console.WriteLine("NetJSON-static     : {0}", UseNetJsonStatic(data));

            GC.Collect();
            GC.WaitForPendingFinalizers();
            Console.WriteLine("Jynd-dynamic       : {0}", UseJyndDynamic(data));
            GC.Collect();
            GC.WaitForPendingFinalizers();
        }

**Comment by rpgmaker** [comment]
I also noticed that the order of the calls also matter at least for the last two serializer. Did not change with Jil

With Jynd last:

Jil-static         : 00:00:02.4112220
Jil-dynamic        : 00:00:06.0236078
Newtonsoft-static  : 00:00:07.8248275
Newtonsoft-dynamic : 00:00:13.3063563
NetJSON-static     : 00:00:02.0341211
Jynd-dynamic       : 00:00:02.0022569

With NetJSON last:

Jil-static         : 00:00:02.3730104
Jil-dynamic        : 00:00:06.1777428
Newtonsoft-static  : 00:00:07.8546815
Newtonsoft-dynamic : 00:00:13.5195880
Jynd-dynamic       : 00:00:02.0913612
NetJSON-static     : 00:00:02.0351926

With Jil last:

Jil-dynamic        : 00:00:06.0299259
Newtonsoft-static  : 00:00:07.7352895
Newtonsoft-dynamic : 00:00:13.1482729
Jynd-dynamic       : 00:00:02.0497989
NetJSON-static     : 00:00:02.0407855
Jil-static         : 00:00:02.2643721

**Comment by rpgmaker** [comment]
Btw, this is a cheat [MethodImpl(MethodImplOptions.AggressiveInlining)] :). I don't have access to the option since i have to support 3.5 and 4.0

**Comment by Villenny** [comment]
Have you considered conditionally compiling it in where available?

**Comment by rpgmaker** [comment]
I can only if I create a project for 4.5.x. currently I only compile 3.5 and 4.0.

Thanks,

**Comment by Villenny** [comment]
Hmm I think you can do this inside your project to let you detect the
framework version, although its actually better to do the #if in reverse
for all the framework versions you compile to that DONT support the option,
that way you dont have to update it for every version that gets released:

<PropertyGroup Condition="'$(TargetFrameworkVersion)' == 'v4.5'"> <
DefineConstants>$(DefineConstants);DOTNET_45</DefineConstants> </
PropertyGroup>

<PropertyGroup Condition="'$(TargetFrameworkVersion)' == 'v4.0'"> <
DefineConstants>$(DefineConstants);DOTNET_40</DefineConstants> </
PropertyGroup>

**Comment by rpgmaker** [comment]
Thanks for the idea. I will consider it
