### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by NimaAra** [rpgmaker/NetJSON#113]
Currently the following tests are failing:

1. `SerializePolyObjects()`
2. `TestSerializeDateUtcNowWithMillisecondDefaultFormatUtc()`

It would be great if you could have a CI catching these or any possible performance regressions. I am using [AppVeyor](https://www.appveyor.com/) for my projects.

Let me know if you need any help setting these up.

**Comment by rpgmaker** [comment]
You need to convert to using the netjson setting for your test just like I did for my test.


Thanks,

**Comment by NimaAra** [comment]
I am not sure if I understand this correctly. These are existing tests failing on a fresh checkout.

**Comment by rpgmaker** [comment]
That is interesting. I ran the debug and release and both run fine. The
only test that failed for me is case sensitive test

**Comment by NimaAra** [comment]
I expect this to be due to your timezone. That is why I suggest running the tests on a CI.

**Comment by rpgmaker** [comment]
Can you help me verify if the timezone test is using NetJsonSettings? If it is not, can you please convert the static settings to class based setting and let me know if it is working.

Thanks,

**Comment by NimaAra** [comment]
Here's the failing test:

```csharp
[TestMethod]
public void TestSerializeDateUtcNowWithMillisecondDefaultFormatUtc() {
    var settings = new NetJSONSettings { DateFormat = NetJSONDateFormat.Default, TimeZoneFormat = NetJSONTimeZoneFormat.Utc };
    var date = DateTime.UtcNow;
    var djson = NetJSON.Serialize(date, settings);
    var ddate = NetJSON.Deserialize<DateTime>(djson, settings);

    Assert.IsTrue(date == ddate);
}
```

**Comment by rpgmaker** [comment]
Ok. Thanks I will look into it. Was it working before?

**Comment by NimaAra** [comment]
Thanks, don't know, first time building the solution :-)

**Comment by rpgmaker** [comment]
Thanks. I always ran the unit test and they worked except  for poly test which fails only in release mode and works in debug mode. I have a pending change to fix it and it only happens based on how I run it with the test. In isolation, it always work.

I will try using a CI for it. Know any free one that I can use with git?

Thanks

**Comment by NimaAra** [comment]
Ok thanks for the info. 

Yes sure I use **AppVeyor ** for my projects as mentioned above they are "Okay"! :-)

**Comment by rpgmaker** [comment]
I setup appVeyor and everything is building fine with no issue.

https://ci.appveyor.com/project/TJBakre/netjson

Thanks,

**Comment by rpgmaker** [comment]
Reopen the issue if the build is still failing. In the meantime I am going to assume everything is good. And thanks for suggesting the ci tool.

**Comment by NimaAra** [comment]
Looks great¬ :-) I will confirm the tests shortly.

**Comment by NimaAra** [comment]
Hmm.... one of them is still failing on my side. I will debug it later to see what's going.

```chsarp
[TestMethod]
public void TestSerializeDateUtcNowWithMillisecondDefaultFormatUtc() {
    var settings = new NetJSONSettings { DateFormat = NetJSONDateFormat.Default, TimeZoneFormat = NetJSONTimeZoneFormat.Utc };
    var date = DateTime.UtcNow;
    var djson = NetJSON.Serialize(date, settings);
    var ddate = NetJSON.Deserialize<DateTime>(djson, settings);
    Assert.IsTrue(date == ddate);
}
```

**Comment by rpgmaker** [comment]
Ok. Let me know what you find. It is not failing locally nor on the ci that I setup.

Thanks,
