### ISSUE TITLE
XML Documentation missing

### ISSUE THREAD

**Issue by NimaAra** [rpgmaker/NetJSON#114]
Would you be able to include the XML documentation on public classes and models so that we can have IntelliSense support?

**Comment by rpgmaker** [comment]
Sure. I will try to do so soon.

**Comment by NimaAra** [comment]
Still cannot see `IntelliSense` support, looks like you forgot to include the _XML_ file in the _NuGet_ package.

Under **Properties** of the main project make sure, **Build** => **Output** => **XML documentation file** is ticked.

Thanks

**Comment by rpgmaker** [comment]
I did publish the latest nuget package yet. Will do so after the other issue is resolved

**Comment by NimaAra** [comment]
Great! works well I hope doc can be expanded to eventually cover all the methods. Let me know if I can help.

I am planning to be using your library in the enterprise but we need to make sure some of the minor stuff is polished.

Thank you.
