### ISSUE TITLE
Issue with deserializing lists with > 100 items

### ISSUE THREAD

**Issue by hcd** [rpgmaker/NetJSON#119]
Hello,
I'm in the process of using NetJSon for some parts of our application that heavily uses json (with Newtonsoft json). For some aspects the raw power of NetJson would be a serious advantage.
But during my performance testing, I've encountered a very weird issue. 

I've created a very simple base class, just having an Id (int).
Then I created  a DTO class that derives from the baseclass, and add a Code (string) property to it
I add 30.000 of these items in a List<> in a for-loop (setting the id & code to the loop-counter for easy inspection).
The I serialized and deserialize this list into a clone-list.
This clone also has 30.000 items.
Then I add a property "Description" (string)  to my DTO class, and rerun the test. No problem
Then I renamed "Description" to "DescriptionShort". After the test , the clone list suddenly had 20100 items instead of 30000 ! On inspection, i see that element 999 in the clonelist has id=999, but element 1000 had id 10000  (ten-thousand !)

Oh, and it gets weirder. I renamed the property DescriptionShort back to  Description, and add a property "DescriptionLong" tot he DTO class.  Now suddenly after the test, my clonelist has 29.100 items ....

BTW, if my DTO does NOT derive from the base class but directly implements the Id property, this doesn't happen ....

**Comment by hcd** [comment]
Btw here's the code te reproduce : 

         namespace PerfTests
        {
           public abstract class DtoBase
            {
                public int Id { get; set; }
            }

    public class MyDto : DtoBase
    {
        public string Code { get; set; }
        public string DescriptionShort { get; set; }
        public string DescriptionLong { get; set; }
    }


    [TestClass]
    public class DtoVsEntitySerializationTests
    {
        private int numItems = 30000;

        [TestMethod]
        public void DtoSerilaizationViaNETJson()
        {
            string json;
            List<MyDto> clone;
            var list = new List<MyDto>();
            using (new StopWatchTimer($"DtoSerializationViaNETJson create"))
                for (int i = 0; i < numItems; i++)
                {
                    list.Add(CreateDto(i));
                }
            using (new StopWatchTimer($"DtoSerializationViaNETJson to json"))
                json = NetJSON.NetJSON.Serialize(list);
            using (new StopWatchTimer($"DtoSerializationViaNETJson from json"))
                clone = NetJSON.NetJSON.Deserialize<List<MyDto>>(json);

            Assert.IsTrue(clone.Count == numItems);
        }
   }

      private MyDto CreateDto(int i)
           {
               var result = new MyDto();
               result.Id = i;
               result.Code = "DTO" + i;
               return result;
           }
    }




            public class StopWatchTimer : IDisposable
            {
                private readonly string _description;
                private Stopwatch _sw = new Stopwatch();
                public StopWatchTimer(string description = null)
                {
                    _description = description;
                    _sw.Start();
                }

                public void Dispose()
                {
                    _sw.Stop();
                    Debug.WriteLine($"{_description} : FINISHED -> elapsed time : {_sw.ElapsedMilliseconds} ms" + (_sw.ElapsedMilliseconds<2?$"  (ticks:{_sw.ElapsedTicks})":""));
                    _sw = null;
                }
            }

**Comment by rpgmaker** [comment]
Thanks for the example. I will look into it

**Comment by rpgmaker** [comment]
Just for a quick test, can you remove the abstract keyword from your class and test again. And if possible, can you test a scenario where you have abstract on the base and also the Id property and then try to do an override in the child class. Just wanted to eliminate some scenario.

Thanks,

**Comment by hcd** [comment]
I have 2 hours of meetings (starting in 5 minutes), but i'll do it right after !

**Comment by rpgmaker** [comment]
Thanks a lot

**Comment by hcd** [comment]
When I got back, I tried to run the unittest, but now I got 30.000 items. And i know for sure I have not been dreaming ;)
So I made the base class not-abstract, and re-ran : 20100 items. Then I made it abstract again : 20100 items.  Then I tried to make the Id abstract, and override it in the subclass : again 20100 items.
Then I even removed the base class altogether : still 20100 items !

So weird, It's like it's non-deterministic behavior ...

**Comment by hcd** [comment]
Here's some screenshots of my results of various cases. But I have to make the remark that for some cases, I had both the correct as incorrect result on different testruns. I cannot seem to see a pattern in it ...

Not OK: abstractbaseclasswithid.png
![nok_abstractbaseclasswithid](https://cloud.githubusercontent.com/assets/111714/16339976/d44f496e-3a25-11e6-8ed6-3625b6117753.png)
Not OK: baseclasswithid.png
![nok_baseclasswithid](https://cloud.githubusercontent.com/assets/111714/16339975/d44e8e5c-3a25-11e6-8401-a1e829b4a075.png)
OK: abstractbaseclasswithabstractid.png
![ok_abstractbaseclasswithabstractid](https://cloud.githubusercontent.com/assets/111714/16339978/d4531c4c-3a25-11e6-83c5-0358364b52e3.png)
OK: abstractbaseclasswithvirtualid.png
![ok_abstractbaseclasswithvirtualid](https://cloud.githubusercontent.com/assets/111714/16339979/d454da50-3a25-11e6-87e4-5cba6523f5c3.png)
OK: abstractemptybaseclass.png
![ok_abstractemptybaseclass](https://cloud.githubusercontent.com/assets/111714/16339977/d44faa12-3a25-11e6-8e49-b0e372c358eb.png)
OK: emptybaseclass.png
![ok_emptybaseclass](https://cloud.githubusercontent.com/assets/111714/16339980/d4562ca2-3a25-11e6-9f7c-a819657011b0.png)
OK :  nobaseclass.png
![ok_nobaseclass](https://cloud.githubusercontent.com/assets/111714/16339981/d47184d4-3a25-11e6-95ec-eeb93ccdce3a.png)

**Comment by rpgmaker** [comment]
Thanks for the detail result. I really appreciate it. I will use the information to help me figure out the issues.

Thanks,
