### ISSUE TITLE
Cannot serialize a model with IEnumerable<T> as a property

### ISSUE THREAD

**Issue by NimaAra** [rpgmaker/NetJSON#121]
Given the model: 

```csharp
public class Person
{
    public string Name { get; set; }
    public uint Age { get; set; }
    public IEnumerable<Person> Friends { get; set;}
}
```

The following throws `TypeInitialization` exception:

```csharp
var person = new Person
{
    Name = "Jack",
    Age = 10,
    Friends = new[] 
    { 
        new Person {Name = "Bob", Age = 1},
        new Person {Name = "Alice", Age = 2}
    }
};

var personJson = NetJSON.NetJSON.Serialize(person);
```

Changing the **Friends** property to `Person[]` fixes the problem.

**Comment by rpgmaker** [comment]
Thanks for the find. That is not currently support yet. I will look into supporting it once I get the immutable serialization working.

Thanks,

**Comment by NimaAra** [comment]
Thank you Sir :-)

**Comment by rpgmaker** [comment]
Please test again. The fix was very simple, I already had the logic to handle it but was missing a simple conditional check :)

**Comment by NimaAra** [comment]
Works great. Thanks.
