### ISSUE TITLE
Serializing this model results in skipped properties

### ISSUE THREAD

**Issue by NimaAra** [rpgmaker/NetJSON#122]
Given the following model:

```csharp
public sealed class Computer
{
    public long Timestamp { get; set; }
    public Process[] Processes { get; set; }
    public OperatingSystem[] OperatingSystems { get; set; }
}

public sealed class Process
{
    public string Name { get; set; }
    public uint Id { get; set; }
    public string Description { get; set; }
}

public sealed class OperatingSystem
{
    public string Name { get; set; }
    public string Version { get; set; }
    public decimal Price { get; set; }
    public Disk[] Disks { get; set; }
}

public sealed class Disk
{
    public string Name { get; set; }
    public long Capacity { get; set; }
}
```

When populating the object graph as:

```csharp
[TestMethod]
public void Run()
{
    var model = new Computer
    {
        Timestamp = 12345,
        Processes = Enumerable.Range(0, 100)
            .Select(x => new Process
            {
                Id = (uint)x,
                Name = "P: " + x.ToString(),
                Description = "This is process " + x.ToString()
            })
            .ToArray(),

        OperatingSystems = Enumerable.Range(0, 50)
            .Select(x => new OperatingSystem
            {
                Name = "OS - " + x.ToString(),
                Version = "0.0.0." + x.ToString(),
                Price = (decimal)(x * 0.412),
                Disks = new[]
                {
                    new Disk
                    {
                        Name = "Disk: " + x.ToString(),
                        Capacity = x * 100
                    },
                    new Disk
                    {
                        Name = "Disk: " + x.ToString(),
                        Capacity = x * 100
                    }
                }
            })
            .ToArray()
    };

    var modelAsJson = NetJSON.Serialize(model);    
}
```
If you inspect the _JSON_ you will see that some properties are missing on a random basis.

**Comment by NimaAra** [comment]
It looks like this is happening when the value of the property is **0**, check the following for example

```json
"OperatingSystems":[  
  {  
     "Name":"OS - 0",
     "Version":"0.0.0.0",
     "Disks":[  
        {  
           "Name":"Disk: 0"
        },
        {  
           "Name":"Disk: 0"
        }
     ]
  },
  {  
     "Name":"OS - 1",
     "Version":"0.0.0.1",
     "Price":0.412,
     "Disks":[  
        {  
           "Name":"Disk: 1",
           "Capacity":100
        },
        {  
           "Name":"Disk: 1",
           "Capacity":100
        }
     ]
  }
  ...
```

**Comment by rpgmaker** [comment]
Is it skipping any int with value of zero? if so simply set NetJSONSetting.SkipDefaultValue to false or use int? so it know that the value is really set.

Thanks,

**Comment by NimaAra** [comment]
Well in this case it is skipping it for _**uint**_ and _**decimal**_ as well

**Comment by rpgmaker** [comment]
It will do so for every default values. So you will need to make the nullable, uint?, decimal? or simply set SkipDefaultValue to false


Thanks,

**Comment by rpgmaker** [comment]
Let me know if that works for you. If it does not work, then i will debug it to figure why it is doing so :)

Thanks,

**Comment by NimaAra** [comment]
No doing the below does not work:

```csharp
var settings = new NetJSONSettings {SkipDefaultValue = false};
var modelJson = NetJSON.Serialize(model, settings);
```

**Comment by rpgmaker** [comment]
Cool. I will play with it and get back to you.

Thanks,

**Comment by NimaAra** [comment]
Great, Thanks.

**Comment by rpgmaker** [comment]
I figured out the problem. The SkipDefaultValue is not propagated from using NetJSONSetting but it is when using NetJSON.SkipDefaultValue. Try it with NetJSON.SkipDefaultValue = false? I am going to verify why it is not in the meantime.

Thanks,

**Comment by rpgmaker** [comment]
Please and let me know if it resolved the issue.

Thanks,

**Comment by NimaAra** [comment]
Hi, I will try this evening and get back to you.

One note though, would you not agree that the value should be set to `false` by default? Why have this configurable anyway? what is the implications?

Thanks,

**Comment by rpgmaker** [comment]
I believe it is best for it to be set to true by default. It is useful for when you don't care about default value been serialized in your json string which result to smaller data been sent.  We you use it for communication between two server written in .net then it will help improve performance since you are not dealing with unnecessary transformation for default value. 

If you are mostly using it for an application that send data to client then it would be fine to set it to false so that the client can have a full context of the data.

Overall, excluding unneeded fields will always have a far better performance that including them since they are just default value.

Thanks,

**Comment by NimaAra** [comment]
I just did the test, it works great thanks :-)

I agree with your point with regards to optimization however my point is that as a user I would expect everything to be serialized by default and if I wanted the added optimization then I can opt out. This way there is less surprises and I won't have to keep scratching my head thinking what happened to my data.

In fact there are many scenarios that the default value is indeed valid data that need to be transferred across, think about what happens if a non `NetJson` library is to parse the resulting _JSON_. Just something to think about...

On another note, I could not figure out how to get the _JSON_ to be **camelCase**, any idea?

Thanks,

**Comment by rpgmaker** [comment]
Great that it works for you. As for other parser they should be able parse partial json and not require all fields.

Unfortunately, camelCase is not a supported functionality at this time. You can submit a request for it.

Thanks,
