### ISSUE TITLE
Add support for producing camelCased JSON

### ISSUE THREAD

**Issue by NimaAra** [rpgmaker/NetJSON#123]
Your great library does not currently support **camelCased** _JSON_. Adding the feature will be great for us so that we can have a consistent _JSON_ produced.

Thanks.

**Comment by wmjordan** [comment]
+1

**Comment by rpgmaker** [comment]
Can one of you make a pull request for it? Since it is as simple as changing the first character casing to lower.

Thanks,

**Comment by NimaAra** [comment]
@rpgmaker I will look into it when I get a chance even though I have not so far looked at the source.

**Comment by rpgmaker** [comment]
I was going to try it today myself. But if you can do it then that would be great too

Thanks,

**Comment by rpgmaker** [comment]
Please test it and let me know if it works as expected.

Thanks,

**Comment by NimaAra** [comment]
Works great thanks!

Will you be publishing a new release soon?

**Comment by rpgmaker** [comment]
Yes will do so

**Comment by rpgmaker** [comment]
I have published it to nuget and created a new release.

Thanks,

**Comment by NimaAra** [comment]
Thank you Sir. 

On 30 July 2016 19:03:53 BST, Rpgmaker <notifications@github.com> wrote:
>I have published it to nuget and created a new release.
>
>Thanks,
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/rpgmaker/NetJSON/issues/123#issuecomment-236380098

-- 
This email was sent using a mobile device, please excuse my brevity.

____________________________________________________________
FREE 3D MARINE AQUARIUM SCREENSAVER - Watch dolphins, sharks & orcas on your desktop!
Check it out at http://www.inbox.com/marineaquarium
