### ISSUE TITLE
Deserializing members of private types with CamelCase failed

### ISSUE THREAD

**Issue by wmjordan** [rpgmaker/NetJSON#128]
The following code reproduce the problem:

````C#
using System;
using NetJSON;
using Json = NetJSON.NetJSON;
using System.Diagnostics;

namespace ConsoleApplication1
{
	class Program
	{
		static void Main(string[] args) {
			C c = new C { S = "a", I = 1 };
			string s;
			Console.WriteLine(s = Json.Serialize(c, new NetJSONSettings { CamelCase = true }));
			c = Json.Deserialize<C>(s, new NetJSONSettings { CamelCase = true });
			Console.WriteLine(s = Json.Serialize(c, new NetJSONSettings { CamelCase = true }));
		}

		class C
		{
			public string S { get; set; }
			public int I { get; set; }
		}
	}
}
````
The output of the second `Console.WriteLine` was "{}".
Things were fine if `CamelCase` was false.

**Comment by rpgmaker** [comment]
The issue here is not camel case. You need to set case sensitive to false.

**Comment by rpgmaker** [comment]
Using camel make it lower case therefore making deserialization false. Camel case option based on my implementation is only applicable to serialization output, similar to prettify option.

**Comment by wmjordan** [comment]
Oops, I got it.

**Comment by rpgmaker** [comment]
This same output will occur even if the type is not private.

**Comment by wmjordan** [comment]
But what if only the camelCase field names are acceptable, lowercase or UPPERCASE are unacceptable?

**Comment by rpgmaker** [comment]
Then you can use NetJSONProperty attribute on those same fields so that when you send a json value to deserialize you will not need to case sensitive equals false. The attribute will allow you tell netjson what field name to expect when deserialization/serialization occurs.

**Comment by wmjordan** [comment]
Understood.
Thank you for your patience and kind help.
