### ISSUE TITLE
Enum alias

### ISSUE THREAD

**Issue by wmjordan** [rpgmaker/NetJSON#129]
Is it possible to give alias to enum values? I tried `NetJSONPropertyAttribute`, but no effect.

~~BTW, I found that NetJSON serializes enum values to raw Javascript variables, which might lead to problems. Most JSON serializers produce literal forms. Is it possible to serialize enum values to quoted strings?~~

````C#
var ejson = NetJSON.Serialize(SampleEnum.TestEnum1);
// now ejson == TestEnum1, how to get an alias, for instance "Enum1"
````

**Comment by wmjordan** [comment]
Sorry, I could use `UseEnumString`.

**Comment by wmjordan** [comment]
Sorry, I could use `UseEnumString` for string enums.
Now only the Enum alias problem is left.

**Comment by rpgmaker** [comment]
What will be the benefit of having alias for enum? Would that not mean that you are building business mapping in your code for volatile data? Would it not be best for your enum object to match directly to the input or even better let the name be case in sensitive to names enum.

Thanks,

**Comment by wmjordan** [comment]
Some platforms use UPPERCASE enum names, some use snake_case, some use camelCase. Those do not comply the .NET naming conventions, which use PascalCase names. As we work with various platforms without enum aliases mapping, the code could look uglily mixed with various enum namings.

**Comment by wmjordan** [comment]
Some platforms even use their own set of abbreviations, for instance, `PKM_GID`, `PKM_UID`. We don't want to follow their names when programming our own code, and want to use easier to remember enum values, for instance `GroupId`, `UniversityId` instead.

**Comment by rpgmaker** [comment]
For the name differences I guess that will need aliasing. I will look into it.

Thanks,

**Comment by wmjordan** [comment]
> a case insensitive enum parsing that will also trim underscore and etc?
I am afraid that will slow down NetJSON, especially when trimming the underscores. Meanwhile, this only solves the deserialization part, it can not serialize the enum for those platforms.

**Comment by rpgmaker** [comment]
You are correct. I have decided to use aliasing since I can inline it into
the serializer code.

Thanks,

**Comment by rpgmaker** [comment]
Please test again. The following works:


public enum MyEnumTestValue
        {
            [NetJSONProperty("V_1")]
            V1 = 2,
            [NetJSONProperty("V_2")]
            V2 = 4,
            [NetJSONProperty("V_3")]
            V3 = 5
        }
        public class MyEnumClassTest
        {
            public string Name { get; set; }
            public MyEnumTestValue Value { get; set; }
        }

        [TestMethod]
        public void SerializeEnumValueUsingAttribute()
        {
            var settings = new NetJSONSettings { UseEnumString = true };
            var obj = new MyEnumClassTest { Name = "Test Enum", Value = MyEnumTestValue.V1 };
            var json = NetJSON.Serialize(obj, settings);

            var obj2 = NetJSON.Deserialize<MyEnumClassTest>(json, settings);

            var obj3 = NetJSON.Deserialize<MyEnumClassTest>(json.Replace("V_1", "V_3"), settings);

            Assert.IsTrue(obj.Value == obj2.Value);
            Assert.IsTrue(obj3.Value == MyEnumTestValue.V3);
        }

**Comment by wmjordan** [comment]
Good. It is working.
