### ISSUE TITLE
Enum flag values not properly serialized or deserialized

### ISSUE THREAD

**Issue by wmjordan** [rpgmaker/NetJSON#130]
The following code reproduces this issue:
````C#
var o = NetJSON.NetJSON.Serialize(System.IO.FileShare.Read | System.IO.FileShare.Delete);
// o == 0
````
`System.IO.FileShare` has a `FlagsAttribute` and we shall use do something special.

**Comment by rpgmaker** [comment]
Thanks for the find. I missed one CIL instruction :) 

Can you test again

**Comment by wmjordan** [comment]
It still did not work.
I'd updated the code and it still output 0 for the above statement.

**Comment by wmjordan** [comment]
This issue was not the same as #131

**Comment by rpgmaker** [comment]
The reason this is not working is because you are combining two enumeration together that create a value that does not exists within the enum itself. My current implement will only use the values within the implementation. If you use Read and Write flag it will generate the correct enum Value for both string and number.

In order to support this option that you want, i will have to return an int representation of the enum as it is if it cannot be found with a name within the enumeration itself.

Thanks,

**Comment by wmjordan** [comment]
The expected output of the issue example is `"Read,Delete"`.
The serialization part is more challenging since we have to break down the enum value to combinations.
The `ToString` method of the `Enum` type supports flag combinations. You may take a look at their implementation [http://referencesource.microsoft.com/#mscorlib/system/enum.cs,93a0c65b8141e010] and make something similar in NetJSON.

The deserialization part is less difficult, we just split the string and match the segments to existing value representations.

**Comment by rpgmaker** [comment]
Does other json serializer output the comma delimiter value when using flags?

**Comment by wmjordan** [comment]
Yes. Newtonsoft (JSON.NET) produces comma delimited results for flags:
````C#
Console.WriteLine(JsonConvert.SerializeObject(System.IO.FileShare.Read | System.IO.FileShare.Delete, new Newtonsoft.Json.Converters.StringEnumConverter()))
````

**Comment by rpgmaker** [comment]
Test again. It has been fixed. Sorry for the late fix and thanks again for the pull request

**Comment by wmjordan** [comment]
Sorry for the late reply. Recently my Windows got completely broken for attempting to install the Anniversary update. I'd got to reinstall the system and everything. I will get up with the latest code when things are reinstalled.
