### ISSUE TITLE
How to get underlying numeric values from Enum values?

### ISSUE THREAD

**Issue by wmjordan** [rpgmaker/NetJSON#131]
Please try the following code.
````C#
var s = NetJSON.NetJSON.Serialize(FileShare.Delete)
````

The serialization result was `"Delete"` (UseEnumString = true) or `Delete` (UseEnumString = false).
How to get `4` (the `Int32` value of `FileShare.Delete`)?

**Comment by rpgmaker** [comment]
It is not returning the expect int value?

**Comment by wmjordan** [comment]
Nope. The `UseEnumString = false` configuration returns a string without quotes on my computer, with the latest version from Git.

**Comment by rpgmaker** [comment]
Ok. I will look into it.

Thanks,

**Comment by rpgmaker** [comment]
Thanks for the find. I missed one CIL instruction :) 

Please test again. When using the UseEnumString = false, it will output the number instead of the string which is why the quote is excluded but it was buggy

**Comment by rpgmaker** [comment]
This issue is fixed. I just tested and it works fine for me.
