### ISSUE TITLE
Suggestions on the NetJSON class

### ISSUE THREAD

**Issue by wmjordan** [rpgmaker/NetJSON#132]
Nowadays the `NetJSON` class has many methods, some of which are actually internally used by the dynamic assemblies compiled at run-time.
I suggest that you place those methods into an embedded static class or another class, so the users, especially newbies to `NetJSON`, will not be overwhelmed by so many methods.

Another suggestion is to rename the namespace or the class so they don't share the same name.
Nowadays even if we have placed this `using` statement in the code,
````C#
using NetJSON;
````
We still have to fully qualify the `NetJSON` class with its namespace `NetJSON`, simply because they both have the same name.
````C#
var d = NetJSON.NetJSON.Serialize(1); // this is not so convenient
````

**Comment by rpgmaker** [comment]
Thanks. Will do. I still need to make the method public because of dynamic assemblies. But having just the serialize and deserialize logic in the netjson would help. As for the namespace and name. It will be a breaking change to rename any of  it without supporting both way for legacy code

**Comment by wmjordan** [comment]
Yes, I understand that those methods must be public for the sake of dynamic assemblies.
Maybe it looks good to create a public nested class named `Internals` in `NetJSON` class and place those utility methods inside that nested class.

For backward compatibility, you don't need to remove the `NetJSON` class completely. For example, if the new facade class is named `Json`, then the `NetJSON` class could have some methods wrap things up like the following code shows. Consequently, nothing will get broken. The legacy code would just run a very little bit slower.
````C#
[Obsolete("The NetJSON class is deprecated and please use the Json class instead.")]
public static string Serialize<T>(T obj) {
    return Json.Serialize(obj);
}
````

**Comment by rpgmaker** [comment]
I suppose i could do that.

Thanks for the suggestion. I will most likely name it NetJSONSerializer.

Thanks,

**Comment by rpgmaker** [comment]
Would you be able to make the changes for me as a pull request?

Thanks,

**Comment by wmjordan** [comment]
`NetJSONSerializer` appears to be quite long, why not `JSON` only, it is already under the `NetJSON` namespace?
So we can use `JSON.Serialize`, `JSON.Deserialize`, rather than
`NetJSONSerializer.Serialize` and `NetJSONSerializer.Deserialize`.

**Comment by wmjordan** [comment]
OK, I am forking the project.

> Would you be able to make the changes for me as a pull request?

**Comment by wmjordan** [comment]
Usually I deal with code files less than 1000 lines, 2000 lines might be the maximal capability for me.

Shall I use the `partial` technique to break down the _NetJSON.cs_ into several files?
For instance, the `Internals` class might be moved to a separated _NetJSON.Internals.cs_ file.
`Tuple` classes and some Net35 specific stuff could be moved to a new _Net35Utilities.cs_ file.

**Comment by rpgmaker** [comment]
That is fine by me.

Thanks,

**Comment by wmjordan** [comment]
I am sorry that I have to postpone the work.

Recently I was dealing with a poorly written JSON API service, which did not support HTTP Keep-Alive. Each time my program connected to it, a new HTTP connection must be created and the connection would be closed after that request. Consequently, my CPU got extremely busy creating and disposing HTTP connections.
I have got to figure out a way to cope with such kind of API services and therefore my time schedule gets tight.

**Comment by rpgmaker** [comment]
Closing before of merge
