### ISSUE TITLE
Nullables with default value assigned are skipped

### ISSUE THREAD

**Issue by bcarruthers** [rpgmaker/NetJSON#133]
When SkipDefaultValue is true, nullables with a default value assigned are skipped. The following test fails in the latest:
```
class NullableTest
{
    public int? x { get; set; }
    public int? y { get; set; }
}

[TestMethod]
public void NullableWithDefaultValueSetSerializes()
{
    var obj = new NullableTest { x = 0, y = null };
    var settings = new NetJSONSettings { SkipDefaultValue = true };
    var json = NetJSON.Serialize(obj, settings);
    Assert.AreEqual("{\"x\":0}", json);
}
```

**Comment by rpgmaker** [comment]
Did this work in the previous version?  Sorry for getting back to you late. If it was broken previously, i will fix it after i merge the current pull request

Thanks,

**Comment by bcarruthers** [comment]
I just tested, and it appears to work in 1.1.0.5 but not in 1.1.0.6.

**Comment by rpgmaker** [comment]
Ok. I will look into what changed.

Thanks,

**Comment by rpgmaker** [comment]
Please test again. Thanks
