### ISSUE TITLE
Issue with DateTime

### ISSUE THREAD

**Issue by zanarchist** [rpgmaker/NetJSON#135]
I was evaluating your implementation against JSON.Net with some data that a partner sends us. This data had a value which included what should have been a DateTime in UTC format, but it didn't have the trailing Z. This causes an index out of range issue. 

Im not sure if it is your intention to fail on the missing character or if it is an oversight, but it would be much better (IMHO) if there was a default or something like it. 

I copied your source code and changed the line in StringToDate from 
var utcOffsetText = hasOffset ? value.Substring(dateText.Length, diff) : string.Empty;
var firstChar = utcOffsetText[0]; // This line fails if the Z is missing
to
var utcOffsetText = hasOffset ? value.Substring(dateText.Length, diff) : string.Empty;
var firstChar = utcOffsetText.Length > 0 ? utcOffsetText[0] : '\0';

And then it was able to deal with the DateTime just fine.

**Comment by rpgmaker** [comment]
Did you try to pass the netjsonsettings object for both serialize and deserialize with dateformat as iso and timezoneformat as unspecified? Z should only be required when you use timezoneformat of utc.

Thanks,

**Comment by zanarchist** [comment]
Hey, thanks for getting back so quickly. However, Im afraid that wont work. 

Firstly, if you have a look at the method it doesnt take the TimeZoneFormat into account until AFTER it has made the check for the firstChar, so even using  timezoneformat as unspecified this still breaks. 

Secondly, our partner seems to have a data issue. So the data contains an array with 10 dates. They should all be in UTC, but one of them is missing the trailing Z. 
So yes, it is essentially bad data, but other serializers seem to be handling this (as I wasn't actually aware there was an issue till now).

**Comment by rpgmaker** [comment]
I see. I will fix it. In the mean time you can make any adjustments to resolve it temporarily from your side

Thanks,

**Comment by rpgmaker** [comment]
Thanks for the solution to fix and sorry for check-in late
