### ISSUE TITLE
DotNET Core library not included in nuget package

### ISSUE THREAD

**Issue by StummeJ** [rpgmaker/NetJSON#136]
It looks like when I try to install NetJSON from nuget in a .netcoreapp it cannot find a valid package on nuget.  After looking into it, it looks like there is not library targeted for netstandard1.6.

Cheers!

**Comment by rpgmaker** [comment]
It is currently targeting 1.3. Will need to recompile for 1.6. I will think 1.3 should work for 1.6.

Thanks,

**Comment by StummeJ** [comment]
Would that change the current folder structure under the `lib` folder in the package?  If I add the following code to the package.json and rebuild it produces a working nuget package which includes a `netstandard1.6` directory.

**Comment by rpgmaker** [comment]
OK, let me get back to you

**Comment by rpgmaker** [comment]
Thanks. I will make the changes once i get the current pull request merged

**Comment by rpgmaker** [comment]
This is resolved. I have published a package that contains netstandard1.6. Please test and let me know
