### ISSUE TITLE
Nullables with non-default value are serialized in duplicate

### ISSUE THREAD

**Issue by bcarruthers** [rpgmaker/NetJSON#137]
Thank you for fixing the other nullable issue. When testing, I found another issue when serializing non-default nullable values, which is reproduced in this test:
```csharp
[TestMethod]
public void NonDefaultNullableValueSerializes()
{
    var obj = new NullableTest { x = 5 };
    var settings = new NetJSONSettings { SkipDefaultValue = true };
    var json = NetJSON.Serialize(obj, settings);
    Assert.AreEqual("{\"x\":5}", json);
}
```
Expected:<{"x":5}>. Actual:<{"x":5"x":5}>

**Comment by rpgmaker** [comment]
Thanks for the find. The code that is generated had two conditions that writes the property. I need to make sure only one runs.

**Comment by rpgmaker** [comment]
Can you please again? Thanks

**Comment by bcarruthers** [comment]
Looks good, thanks for the quick fix!
