### ISSUE TITLE
Autodetection of single or double quote

### ISSUE THREAD

**Issue by bcarruthers** [rpgmaker/NetJSON#138]
This fails with InvalidJSONException, but either Deserialize() call would succeed if alone in a test, so I'm guessing NetJSON detects the quote type and stores that statically somewhere:
```csharp
private class DoubleTest
{
    public double x { get; set; }
}

[TestMethod]
public void DeserializeWithSingleThenDoubleQuotes()
{
    NetJSON.NetJSON.Deserialize<DoubleTest>("{'x':0.1}");
    NetJSON.NetJSON.Deserialize<DoubleTest>("{\"x\":0.1}");
}
```
Is that the intended behavior? I saw an earlier issue about autodetection, but I wasn't sure about the current state. This scenario only arises for me where JSON is embedded in test code with single quotes for convenience, so it's nothing critical.

**Comment by rpgmaker** [comment]
As long as the json string in the json is escaped. It should be fine. The auto detection is about figuring out which quote to use for everything in the json. You should try to use the deserialize with an instance of netjsonsettings and see what happens. The code should have worked. I have a test verifying it too i believe. If it work then the problem you are getting is related to static setting been used internally by default.

Thanks

**Comment by rpgmaker** [comment]
Here is a test that works fine, extracted from all tje othet tests.


        [TestMethod]
        public void TestAutoDetectQuotes() {
            var dict = new Dictionary<string, string>();
            dict["Test"] = "Test2";
            dict["Test2"] = "Test3";

            var list = new List<string>{
                "Test",
                "Test2"
            };

            var str = "Test";
            var settings = new NetJSONSettings { QuoteType = NetJSONQuote.Single };

            var json = NetJSON.Serialize(dict, settings);
            var jsonList = NetJSON.Serialize(list, settings);
            var jsonStr = NetJSON.Serialize(str, settings);

            var jsonWithDouble = json.Replace("'", "\"");
            var jsonListWithDouble = jsonList.Replace("'", "\"");
            var jsonStrWithDouble = jsonStr.Replace("'", "\"");

            var result = NetJSON.Deserialize<Dictionary<string, string>>(jsonWithDouble);
            var result2 = NetJSON.Deserialize<List<string>>(jsonListWithDouble);
            var result3 = NetJSON.Deserialize<string>(jsonStrWithDouble);
        }

**Comment by bcarruthers** [comment]
Your test code works, and modifying my test to call Deserialize() passing in a settings instance works:
```csharp
NetJSON.NetJSON.Deserialize<DoubleTest>("{'x':0.1}", new NetJSONSettings());
NetJSON.NetJSON.Deserialize<DoubleTest>("{\"x\":0.1}", new NetJSONSettings());
```

**Comment by rpgmaker** [comment]
Closing since it is no longer an issue.

**Comment by talfirevic** [comment]
I ran into the same issue when using
`public static object Deserialize(Type type, string value)` overload

specific string to deserialize is `{"FileName":"f655c912-460a-4e31-a604-e4032e5e09b9","Lat":0,"Long":0}`

And since there is no overload that would accept `NetJSONSettings` and `Type` too I'm stuck.
Also creating an instance of `NetJSONSettings` seems a bit hacky since I'm trying to use NetJSON as `IInputFormatter` on my WebAPI project.

**Comment by rpgmaker** [comment]
You should not need to have the overload if you are using "(double quote) for the entire application. You can still use the static NetJSON.QuoteType to set what you type you want. I can always add an overload if you create a new issue for it. The creation of the setting should not affect performance of the application, but only becomes a problem when there is too many allocation

Thanks,

**Comment by talfirevic** [comment]
@rpgmaker I was mislead by this issue. Actually `Deserialize` won't work if json string ends with `\n` 
Simple test
```

 [TestMethod]
        public void Deserialize()
        {
            var one = "{\"FileName\":\"973c6d92-819f-4aa1-a0b4-7a645cfea189\",\"Lat\":0,\"Long\":0}";
            var two = "{\"FileName\":\"973c6d92-819f-4aa1-a0b4-7a645cfea189\",\"Lat\":0,\"Long\":0}\n";
            
            var stubbornOne = NetJSON.NetJSON.Deserialize(typeof(StubbornClass), one);
            var stubbornTwo = NetJSON.NetJSON.Deserialize(typeof(StubbornClass), two);
        }

        private class StubbornClass
        {
            public string FileName { get; set; }
            public double Lat { get; set; }
            public double Long { get; set; }
        }
```

I'm not sure if having `\n` at the end is actually valid JSON but this might be a good thing to handle within the library.

I can make a separate issue for this if you want.

**Comment by rpgmaker** [comment]
Does it throw a particular exception when it ends with new line? A new issue would be nice if the error is not invalid JSON exception

Thanks,

**Comment by talfirevic** [comment]
It's the same one `NetJSON.NetJSONInvalidJSONException`

T.

**Comment by rpgmaker** [comment]
There was another issue that made me throw the error. Here, reversing back will cause other things to break.

https://github.com/rpgmaker/NetJSON/issues/140

**Comment by rpgmaker** [comment]
Btw, based on this website: https://jsonformatter.curiousconcept.com . Any JSON ending with new lines fails validation.

**Comment by talfirevic** [comment]
@rpgmaker I've checked out the RFC for json http://www.ietf.org/rfc/rfc4627.txt?number=4627 
(this one seems to be the most "popular one")

And it states that 

```
These are the six structural characters:

      begin-array     = ws %x5B ws  ; [ left square bracket

      begin-object    = ws %x7B ws  ; { left curly bracket

      end-array       = ws %x5D ws  ; ] right square bracket

      end-object      = ws %x7D ws  ; } right curly bracket

      name-separator  = ws %x3A ws  ; : colon

      value-separator = ws %x2C ws  ; , comma

   Insignificant whitespace is allowed before or after any of the six
   structural characters.

      ws = *(
                %x20 /              ; Space
                %x09 /              ; Horizontal tab
                %x0A /              ; Line feed or New line
                %x0D                ; Carriage return
            )

```

And if I'm interpreting this correctly having lf/nl at the end should still be a valid JSON.

I could be wrong.

**Comment by wmjordan** [comment]
I think the white space before or after the JSON does nothing bad. They should be tolerated.

**Comment by rpgmaker** [comment]
Ok. I will look into it. Just interesting that the other does not allow it.

**Comment by rpgmaker** [comment]
Please a new issue regarding having new line and i will try to resolve it.

Thanks,

**Comment by wmjordan** [comment]
I'd just created a new issue using the code provided by @talfirevic
