### ISSUE TITLE
Deserializing invalid JSON causes the thread to block.

### ISSUE THREAD

**Issue by NimaAra** [rpgmaker/NetJSON#140]
Given:

```csharp
public static T Deserialize<T>(byte[] bytes)
{
	if (bytes == null || bytes.Length == 0)
	{
		throw new ArgumentNullException(nameof(bytes), "The bytes cannot be null or empty.");
	}

	using (var memStream = new MemoryStream(bytes))
	using (var reader = new StreamReader(memStream))
	{
		return NetJSON.NetJSON.Deserialize<T>(reader, GetOptions());
	}
}

private static NetJSONSettings GetOptions()
{
	return new NetJSONSettings
	{
		CamelCase = true,
		CaseSensitive = false,
		DateFormat = NetJSONDateFormat.EpochTime,
		TimeZoneFormat = NetJSONTimeZoneFormat.Utc,
		Format = NetJSONFormat.Default,
		IncludeTypeInformation = true,
		SkipDefaultValue = false,
		UseEnumString = true,
		QuoteType = NetJSONQuote.Double
	};
}
```

And any models e.g:

```csharp
public sealed class Person { }
```

When deserializing using:

```csharp
var invalidBytes = Encoding.UTF8.GetBytes("Foo");
var invalidModel = Deserialize<Person>(invalidBytes);
```

The thread is blocked forever.

**Comment by rpgmaker** [comment]
Thanks. Will fix it today.

Thanks,

**Comment by NimaAra** [comment]
Thanks.

Could you also review exception handling and consider throwing an exception if the _JSON_ to deserialize does not match the requested model?

Currently both _JSON.Net_ and _Jil_ throw an exception if deserialization fails which is what I expect but _NetJSON_ returns a `null`.

**Comment by rpgmaker** [comment]
Currently for a json that is considered invalid, I throw invalidjsonexception. For validation you are not referring to model validation, right? Ex. When given a complex object and all the properties or fields do not exist in the input json then throw exception? Or more of if i have a type mismatch where a string is given as a input for a complex object then throw exception due to its mismatch?

Thanks,

**Comment by NimaAra** [comment]
I meant more in the context of the original example for this issue, `invalidModel` is returned as null (occasionally when the thread is not blocked) instead of an exception being thrown.

**Comment by rpgmaker** [comment]
Ok. I got it.

Thanks,

**Comment by rpgmaker** [comment]
Hi,

Do you think it is fine to check in code that check the start and end of a json text based on whether it is a complex(Array, dictionary, class) and throw an exception? Or do you think it will cause more problem down the line? I am trying to avoid adding a check in a iteration that would check if the { or [ has been encountered or not before the index passes the size of the string

Thanks,

**Comment by NimaAra** [comment]
I think that would be a reasonable check to make which would then allow you to fail fast and early which I always prefer. I cannot think of this causing more problems down the line.

Thanks.

**Comment by rpgmaker** [comment]
Please test.

Thanks,

**Comment by NimaAra** [comment]
Works beautifully thanks. Could you kindly release a new NuGet?

FYI, why is `NetJSON.PCL` still in the solution?

**Comment by rpgmaker** [comment]
Sure. Will do so. Was thinking I could still support pcl is why it is still there

**Comment by rpgmaker** [comment]
Done. It is available on nuget: https://www.nuget.org/packages/NetJSON/

Thanks,

**Comment by NimaAra** [comment]
Thank you sir for the quick turnaround.
