### ISSUE TITLE
Strongly Named Assembly

### ISSUE THREAD

**Issue by protyagov** [rpgmaker/NetJSON#145]
I ran into this trouble today. Pretty much it seems our release manager fails to build project when new version has updated dll that is not strongly named. From Googling this it seems kind of common when people use unsigned assemblies.

I just learned today about strongly named assemblies after spending few hours figuring out why project fails to compile on the server telling me that it want to use 1.2.1.5 instead of updated 1.2.1.6.
https://msdn.microsoft.com/en-us/library/wd40t7ad(v=vs.110).aspx

It looks like the way I need to have it is to add the following to web.config file:

```
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="protobuf-net" publicKeyToken="257b51d87d2e4d67" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.1.0.0" newVersion="2.1.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="NetJSON" publicKeyToken= ????  culture="neutral" />
        <bindingRedirect oldVersion="1.2.1.5-1.2.1.6" newVersion="1.2.1.6" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
```

However I can not do that because there is no publicKeyToken:

![screen shot 2016-12-15 at 8 32 50 pm](https://cloud.githubusercontent.com/assets/7088732/21250122/5d05d5aa-c308-11e6-8c05-14c846319d88.png)

I am thinking this might be good thing to add to this project in general, and it should be easy to do from project properties -> Signing Tab -? Sign the Assemble. At least this is how I understood the process.

Meanwhile I think I should be able to ask admin on our server to do something with the release manager to actually accept my project one way or another.

**Comment by rpgmaker** [comment]
I will look into the signed assembly. I will most likely create a seperate nuget package to maintain a signed version.

Thanks,

**Comment by rpgmaker** [comment]
You can also set null as the public key temporarily and that should work also since it is a redirect

**Comment by protyagov** [comment]
Did not know that one can use publicKeyToken="null" to avoid the issue. Trying all that now...

Also noticed that when I tap on NetJSON in references and go to properties it still says version 1.2.1.5 despite that I have updated to 1.2.1.6 yesterday and 1.2.1.7 today.  

![screen shot 2016-12-16 at 10 26 22 am](https://cloud.githubusercontent.com/assets/7088732/21270135/e7d0185e-c37a-11e6-9d52-c64c2b276da7.png)

**Comment by NimaAra** [comment]
That's because the assembly versions have not been updated accordingly:

[AssemblyVersion](https://github.com/rpgmaker/NetJSON/blob/master/NetJSON/Properties/AssemblyInfo.cs#L36)
[AssemblyFileVersion](https://github.com/rpgmaker/NetJSON/blob/master/NetJSON/Properties/AssemblyInfo.cs#L37)

**Comment by protyagov** [comment]
Looks like we were able to resolve it, which was issue on our end on how our project was structured. Thanks to all for replies.

**Comment by rpgmaker** [comment]
That is great to hear. Can you close this issue?

Thanks,
