### ISSUE TITLE
NetJSON.Core incorrectly referenced to Xamarin Android project

### ISSUE THREAD

**Issue by binoypatel** [rpgmaker/NetJSON#146]
Hi there,

I am trying to add NetJSON to Xamarin.Android project and found that it's adding reference of NetJSON.Core to the project which in-turn depends on Microsoft.Extensions.DependencyModel and resulting broken build. 

If I reference NetJSON.dll from net40 folder manually, it works. Can you please fix this issue?

Thanks,
Binoy

**Comment by rpgmaker** [comment]
I would think in this case you might want to set the target framework for your project to something inline with .Net framework 4.x. nuget controls which framework is reference based on your project target, I don't think it will be possible for me to forcefully make it target correctly.

If you can post your project settings or csproj file here, I might be able to dig deeper on why it is not working for you.

Thanks,

**Comment by binoypatel** [comment]
Sure, here is my csproj file for Xamarin.Android:

<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProductVersion>8.0.30703</ProductVersion>
    <SchemaVersion>2.0</SchemaVersion>
    <ProjectGuid>{1A0EC261-1BAC-4DE2-8C65-12153F88FD68}</ProjectGuid>
    <ProjectTypeGuids>{EFBA0AD7-5A72-4C68-AF49-83D382785DCF};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}</ProjectTypeGuids>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>App1</RootNamespace>
    <AssemblyName>App1</AssemblyName>
    <FileAlignment>512</FileAlignment>
    <AndroidApplication>true</AndroidApplication>
    <AndroidResgenFile>Resources\Resource.Designer.cs</AndroidResgenFile>
    <GenerateSerializationAssemblies>Off</GenerateSerializationAssemblies>
    <AndroidUseLatestPlatformSdk>True</AndroidUseLatestPlatformSdk>
    <TargetFrameworkVersion>v7.0</TargetFrameworkVersion>
    <AndroidManifest>Properties\AndroidManifest.xml</AndroidManifest>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <AndroidUseSharedRuntime>True</AndroidUseSharedRuntime>
    <AndroidLinkMode>None</AndroidLinkMode>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <AndroidManagedSymbols>true</AndroidManagedSymbols>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <AndroidUseSharedRuntime>False</AndroidUseSharedRuntime>
    <AndroidLinkMode>SdkOnly</AndroidLinkMode>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Mono.Android" />
    <Reference Include="mscorlib" />
    <Reference Include="NetJSON.Core, Version=1.2.1.7, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\packages\NetJSON.1.2.1.7\lib\netstandard1.6\NetJSON.Core.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Xml" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="MainActivity.cs" />
    <Compile Include="Resources\Resource.Designer.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Include="GettingStarted.Xamarin" />
    <None Include="packages.config" />
    <None Include="Resources\AboutResources.txt" />
    <None Include="Assets\AboutAssets.txt" />
  </ItemGroup>
  <ItemGroup>
    <AndroidResource Include="Resources\layout\Main.axml">
      <SubType>Designer</SubType>
    </AndroidResource>
  </ItemGroup>
  <ItemGroup>
    <AndroidResource Include="Resources\values\Strings.xml" />
  </ItemGroup>
  <ItemGroup>
    <AndroidResource Include="Resources\drawable\Icon.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Properties\AndroidManifest.xml" />
  </ItemGroup>
  <Import Project="$(MSBuildExtensionsPath)\Xamarin\Android\Xamarin.Android.CSharp.targets" />
  
</Project>

I have also attached sample project if you need in case.

Thanks,
Binoy
[App1.zip](https://github.com/rpgmaker/NetJSON/files/671544/App1.zip)

**Comment by rpgmaker** [comment]
Could you share a screenshot of your nuget explorer when trying to add netjson. I want to see what it shows. Because based on this link below, it might just be that your project is trying to target the new .Net standard 

https://blog.xamarin.com/net-standard-library-support-for-xamarin/

**Comment by rpgmaker** [comment]
After much research, I cannot fix this issue. The best I can do is include the missing dependencies for it. Based on my finding when you reference nuget packages using the latest xamarin, it uses monoandroid60 for the target in packages.config file which points to .net standard. I tested the same thing with other package such as Newtonsoft.JSON and it does same thing also, it references .net standard packages rather than  .net 4.x framework. I will be closing this issue since and will comment on the issue once I publish a new package(that includes .net standard missing dependencies) for the other issues i am working on. 

If you have any further comments or finding that might conflict what I just said, you may reopen the issue

**Comment by binoypatel** [comment]
Sorry for the late reply, the real problem is I cannot compile the xamarin.android project due to compilation error for Microsoft.Extensions.DependecyModel dependency:

![image](https://cloud.githubusercontent.com/assets/4742252/21486057/456c3a9e-cb7b-11e6-8f4c-f526e9aa3511.png)

Once this is fixed, it doesn't really a problem.

Thanks,
Binoy

**Comment by rpgmaker** [comment]
I have published a new version on nuget that contains the missing dependencies
