### ISSUE TITLE
Bad indent using prettify

### ISSUE THREAD

**Issue by npoy** [rpgmaker/NetJSON#147]
Hi, triying to indent my json i used the NETJsonSetting "NetJSONFormat.Prettify" but that destroys my jsonFile when serialize an specific string value:

**String value:**
"Data Source=[DataSource,];Initial Catalog=[Database,];User ID=[User,];Password=[Password,];Trusted_Connection=[TrustedConnection,False]"

**Image before:**
![image](https://cloud.githubusercontent.com/assets/14371735/21513267/3c4fb876-cc95-11e6-83a3-b733a1afa533.png)

**Image after:**
![image](https://cloud.githubusercontent.com/assets/14371735/21513281/5356b718-cc95-11e6-8afb-e765aa427446.png)

I think that is an error because i had to use other solution to indent my json after the serialization..

Ty, bye!

**Comment by rpgmaker** [comment]
The reason it got indented is because of your []. It thinks that they are arrays. If you remove the brackets, it should work properly.

Thanks,

**Comment by npoy** [comment]
I think that is an error because the indenter function is trying to prettify a string. I had to use another tool to indent the json and it works fine. So, i think that remove [] is not a solution because it happens with {} and commas too.

Thanks,

**Comment by rpgmaker** [comment]
You are correct. I will try to remove the prettify from a regular string i guess.

**Comment by rpgmaker** [comment]
Did the changes helped? I have not updated the nuget package since it is too soon because I just updated it not too long ago. Wanted to wait for a major change first.

**Comment by npoy** [comment]
Thanks for your help man, its working now, I will wait for the nuget update but i can use your source for a while.

Ty Bye.
