### ISSUE TITLE
Date string variants and loss of time stamp precision 

### ISSUE THREAD

**Issue by Branxx** [rpgmaker/NetJSON#152]
re: _dateISORegex

Current setup of this Regex does not recognize (valid) date string such are:

yyy-mm-dd i.e. date only not time specified - default 00:00:00.000)
yyyy-mm-dd hh:mm:ss (i.e. not 'T' and no milisseconds, default .000 )
yyyy-mm-ddThh:mm:ss.0000000Z i.e. highest time precision with .NET framework 100 nanoseconds.

Setting 
_dateISORegex = @"(\d){4}-(\d){2}-(\d){2}([T ](\d){2}:(\d){2}:(\d){2}(.(\d)+)?Z)?"

preserves currently recognized date formats and and enabled for small variants to be still recognised as correct dates.

To maintain compatilbility, TypeRegExs 'date3' would need to change to:
regexs["date3"] = @"^(\d){4}-(\d){2}-(\d){2}([T ](\d){2}:(\d){2}:(\d){2}(.(\d)+)?Z)?$"

As this extends the time precision beyond milliseconds NetJSON.Internals.SerializerUtilities.StringToDate() need a change in several places. I include the whole routine for comparison. Lines that require change are marked with **.

		private static DateTime StringToDate(string value, NetJSONSettings settings, out TimeSpan offset, bool isDateTimeOffset) {
			offset = TimeSpan.Zero;

            if (settings._hasDateStringFormat)
            {
                return DateTime.ParseExact(value, settings.DateStringFormat, CultureInfo.CurrentCulture);
            }

			if (settings.DateFormat == NetJSONDateFormat.EpochTime) {
				var unixTimeStamp = FastStringToLong(value);
				var date = new DateTime(1970, 1, 1, 0, 0, 0, 0, System.DateTimeKind.Utc);
				return date.AddTicks(unixTimeStamp).ToLocalTime();
			}

			DateTime dt;
			string[] tokens = null;
			bool negative = false;
			string offsetText = null;
			int tickMilliseconds = 0;
			bool noOffSetValue = false;
			var timeZoneFormat = settings.TimeZoneFormat;

            if (value == "\\/Date(-62135596800)\\/")
                return DateTime.MinValue;
            else if (value == "\\/Date(253402300800)\\/")
                return DateTime.MaxValue;
            else if (value[0] == '\\') {
                var dateText = value.Substring(7, value.IndexOf(')', 7) - 7);
                negative = dateText.IndexOf('-') >= 0;
                tokens = negative ? dateText.Split(_dateNegChars, StringSplitOptions.RemoveEmptyEntries)
                    : dateText.Split(_datePosChars, StringSplitOptions.RemoveEmptyEntries);
                dateText = tokens[0];

                var ticks = FastStringToLong(dateText);

                dt = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc);
                dt = dt.AddTicks(ticks);

                if (timeZoneFormat == NetJSONTimeZoneFormat.Unspecified || timeZoneFormat == NetJSONTimeZoneFormat.Utc)
                    dt = dt.ToLocalTime();

                var kind = timeZoneFormat == NetJSONTimeZoneFormat.Local ? DateTimeKind.Local :
                    timeZoneFormat == NetJSONTimeZoneFormat.Utc ? DateTimeKind.Utc :
                    DateTimeKind.Unspecified;

                dt = new DateTime(dt.Ticks, kind);

                offsetText = tokens.Length > 1 ? tokens[1] : offsetText;
            }
            else {
                **var dateText = value.Substring(0, Math.Min(value.Length, 19));
                var diff = value.Length - dateText.Length;
                var hasOffset = diff > 0;
                var utcOffsetText = hasOffset ? value.Substring(dateText.Length, diff) : string.Empty;
                var firstChar = utcOffsetText.Length > 0 ? utcOffsetText[0] : '\0';
                negative = diff > 0 && firstChar == '-';
                if (hasOffset)
                    **if (firstChar != '.')
                    {
                        noOffSetValue = timeZoneFormat == NetJSONTimeZoneFormat.Utc || timeZoneFormat == NetJSONTimeZoneFormat.Unspecified;
                        offsetText = utcOffsetText.Substring(1, utcOffsetText.Length - 1).Replace(":", string.Empty).Replace("Z", string.Empty);
                        if (timeZoneFormat == NetJSONTimeZoneFormat.Local)
                        {
                            int indexOfSign = offsetText.IndexOf('-');
                            negative = indexOfSign >= 0;
                            if (!negative)
                            {
                                indexOfSign = offsetText.IndexOf('+');
                            }
                            tickMilliseconds = FastStringToInt(offsetText.Substring(0, indexOfSign));
                            offsetText = offsetText.Substring(indexOfSign + 1, offsetText.Length - indexOfSign - 1);
                            if (negative)
                                offsetText = offsetText.Replace("-", string.Empty);
                            else
                                offsetText = offsetText.Replace("+", string.Empty);
                        }
                        else
                        {
                            tickMilliseconds = FastStringToInt(utcOffsetText);
                        }
                    }
                    else
                    {
                        **dateText = value;
                    }
                    
            
				dt = DateTime.Parse(dateText, CultureInfo.CurrentCulture, DateTimeStyles.AdjustToUniversal);
				if (timeZoneFormat == NetJSONTimeZoneFormat.Local) {
					if (!isDateTimeOffset)
						dt = dt.ToUniversalTime();
                    //dt = new DateTime(dt.Year, dt.Month, dt.Day, dt.Hour, dt.Minute, dt.Second, dt.Millisecond, DateTimeKind.Local);
                    **dt = DateTime.SpecifyKind(dt, DateTimeKind.Local);
                }
                else if (timeZoneFormat == NetJSONTimeZoneFormat.Utc) {
					//dt = new DateTime(dt.Year, dt.Month, dt.Day, dt.Hour, dt.Minute, dt.Second, dt.Millisecond, DateTimeKind.Utc);
                    **dt = DateTime.SpecifyKind(dt, DateTimeKind.Utc);

                }
            }

			var isNullOrWhiteSpace = false;

#if NET_35
            isNullOrWhiteSpace = offsetText.IsNullOrWhiteSpace();
#else
			isNullOrWhiteSpace = string.IsNullOrWhiteSpace(offsetText);
#endif

			if (!isNullOrWhiteSpace) {
				var hours = noOffSetValue ? 0 : FastStringToInt(offsetText.Substring(0, 2));
				var minutes = noOffSetValue ? 0 : (offsetText.Length > 2 ? FastStringToInt(offsetText.Substring(2, 2)) : 0);
				if (negative)
					hours *= -1;
				offset = new TimeSpan(hours, minutes, 0);
				if (!isDateTimeOffset)
					dt = dt.AddHours(hours).AddMinutes(minutes);
				dt = dt.AddTicks(tickMilliseconds)**;
			}

			return dt;
		}

**Comment by rpgmaker** [comment]
Hi,

Could you create a pull request for it?

Thanks,

**Comment by rpgmaker** [comment]
Hi,

Are you still planning on creating a pull request with unit test for this changes?

Thanks,

**Comment by Branxx** [comment]
hi,
sorry for late reply.

try this test. test 3 fails, test 7 is ok.

        [TestMethod]
        public void CanDeserialiseDateTimeWithNanoseconts()
        {
            var t3 = new DateTime(2017, 01, 02, 11, 22, 33,
DateTimeKind.Utc) + TimeSpan.FromTicks(1110000L);
            var t7 = new DateTime(2017, 01, 02, 11, 22, 33,
DateTimeKind.Utc) + TimeSpan.FromTicks(1111111L);
            var s3 = "{ \"TestItem\" : \"2017-01-02T11:22:33.111Z\" }";
            var s7 = "{ \"TestItem\" : \"2017-01-02T11:22:33.1111111Z\" }";
            var deserialised3 =
NetJSON.Deserialize<NullableTestType<DateTime>>(s3, new NetJSONSettings() {
TimeZoneFormat = NetJSONTimeZoneFormat.Utc });
            var deserialised7 =
NetJSON.Deserialize<NullableTestType<DateTime>>(s7);

            Assert.IsNotNull(deserialised3);
            Assert.IsNotNull(deserialised3.TestItem);
            Assert.AreEqual(deserialised3.TestItem.Value, t3);

            Assert.IsNotNull(deserialised7);
            Assert.IsNotNull(deserialised7.TestItem);
            Assert.AreEqual(deserialised7.TestItem.Value, t7);
        }

**Comment by rpgmaker** [comment]
Can you create a pull request with code changes and add your unit in it also. So that I can run it and make sure that all 70 tests plus your is working properly.

Thanks,

**Comment by Branxx** [comment]
I am not familiar with Git but I'll try. Good opportunity for me to learn.

**Comment by rpgmaker** [comment]
Still waiting on your pull request.  ;)

Thanks,

**Comment by rpgmaker** [comment]
I will close this. Please open as a pull request.

Thanks,
