### ISSUE TITLE
Linq to JSON

### ISSUE THREAD

**Issue by sylvaincaillot** [rpgmaker/NetJSON#155]
Hello,
I have a similar code in my app which generates a JSON using NewtonSoft and Linq and I would like to port it to NETJSON to improve my performance:

`JObject myJSON = new JObject(
                                new JProperty("AllData",
                                    new JArray(from e in MyIQueryable
                                               select new JObject(
                                                    new JProperty("A", e.PropA),
                                                    new JProperty("B", ((DateTime)e.PropB).ToString("dd MMM yyyy")),
                                                    new JProperty("C", e.PropC)
                                                )
                                    )
                                )
                            );`

Would you have some directions to do so?

Thank you

Sylvain

**Comment by rpgmaker** [comment]
You could try creating an anonymous or dictionary type and serialize it. Since it is an iqueryable, using .ToDictionary will be easier

Thanks,

**Comment by rpgmaker** [comment]
Does this need to still be open?

Thanks.

**Comment by rpgmaker** [comment]
Thanks :)
