### ISSUE TITLE
Target .netstandard 1.3

### ISSUE THREAD

**Issue by Stoom** [rpgmaker/NetJSON#156]
It looks like all of the libraries that `NetJSON` uses all support .netstandard 1.3 along side .netstandard 1.6.  To increase compatibility with the full .net framework is is possible to also target .netstandard 1.3?

Cheers

**Comment by rpgmaker** [comment]
I have actually tried to support it not too long ago. But there are many things that does not within . Net for both versions. Example is the way assembly are loaded, retrieving enum information are fully supported and the list goes on. 

If you want to help me with getting something that will work, you start targeting 1.3 and let me know alternative methods that can use to satisfy them.

Thanks,

**Comment by NimaAra** [comment]
I agree with @rpgmaker, I tried refactoring the solution to target _1.3_ over the xmas and saw a bunch of show stoppers, at the end I settled with _1.6_.

**Comment by rpgmaker** [comment]
I will be closing this issue tomorrow unless you have found a good way to solve the 1.3 problem.

Thanks,

**Comment by rpgmaker** [comment]
Please reopen if you find new information.
