### ISSUE TITLE
Deserialize doesn't return any result/exeption with wrong json input

### ISSUE THREAD

**Issue by tastyx** [rpgmaker/NetJSON#157]
``` 
            using (var sr = new StreamReader(jsonStream))
            {
                try
                {
                    T deserializedObject = NetJSON.NetJSON.Deserialize<T>(sr, new NetJSON.NetJSONSettings() { CaseSensitive = false });
                    return deserializedObject;
                }
                catch (Exception ex)
                {
                    return null;
                }
            }
```
The first line of the attached JsonExample shows that there's a missing quote at the end of the value, which is making the json invalid. Deserializing this doesn't return a result nor does it throw an exception.

Using latest 1.2.1.9 via Nuget.

[JsonExample.txt](https://github.com/rpgmaker/NetJSON/files/789807/JsonExample.txt)

**Comment by rpgmaker** [comment]
Thanks, I will look into it. Does it simply return null?

**Comment by tastyx** [comment]
Doesn't return anything at all. Seems like an infinite loop or something.

**Comment by rpgmaker** [comment]
Thanks. Will look into it

**Comment by rpgmaker** [comment]
Hi, did not get a chance to look into it. I should be able to get some results this coming week.

Thanks,

**Comment by rpgmaker** [comment]
Sorry, still looking into it.

Thanks,

**Comment by rpgmaker** [comment]
Could you please test again? Sorry it took a while to figure it out :)
