### ISSUE TITLE
NetStandard support

### ISSUE THREAD

**Issue by dsoronda** [rpgmaker/NetJSON#159]
Can you please reduce requirements to NetStandard 1.4 (or 1.2 if possible) so it can be referenced in .NET 4.6.1 projects.

Reference: [.NET Standard Library](https://docs.microsoft.com/en-us/dotnet/articles/standard/library)

**Comment by NimaAra** [comment]
@dsoronda, _**NetJSON**_ as it sands is compatible with _.NET 3.5_ and above. Inside the _NuGet_ package you will find separate compilations for _.NET 3.5_, _.NET 4.0_ as well as _netstandard1.6_.

You can just start referencing it in your project and you are good to go.

**Comment by rpgmaker** [comment]
I agree with nima. As for dropping 4.0, leaving that because it is needed for things such as tuple and dynamic support.

Thanks,

**Comment by dsoronda** [comment]
I have to disagree with @NimaAra. I have NetStandard 1.4 project and can't use NetJSON since it requires NetStandard 1.6.

Currently my choice is to upgrade my project to NetStandard 1.6 so I could use NetJSON  but then I lost option to reference my project from other .NET 4.6.1 projects or to move ALL my projects to  NetStandard 1.6 (and I can't do that for legacy reason).

Also, by building NetStandard 1.1+ project, you will continue to support .NET 4.5+ and Core projects from one library.

**Comment by rpgmaker** [comment]
Hi,

Unfortunately it is not possible to target lesser than 1.6 due to functionality used. The code should work for you with 4.6.1 framework.

Thanks,

**Comment by dsoronda** [comment]
@rpgmaker 

Is there any specific reason not to use 1.4 ? It is in 4.6.1 range after all.

**Comment by rpgmaker** [comment]
Hi,

I tried to support it. But there are missing function for assembly , enum
and thing such nullable. You can download the code and target 1.4 to see
the missing functions and classes.

Remember compatibility to 4.6.1 does not equal to having same
functionality. 4.6.1 is greater than 1.4 standard.


Thanks,

**Comment by NimaAra** [comment]
@dsoronda You seem to be slightly confused with what _netstandard_ is and how it is supported by **_NetJSON_**. If you are targeting the full fat _.NET_ framework e.g. _.NET 3.5_, _.NET 4.6.2_, ... then in the context of **_NetJSON_** all you care about is the most compatible assembly in the _**NuGet**_ package e.g _.NET 4.0_.

If however you are targeting _netstandard1.4_ specifically then you are going to have problems as _**NetJSON**_ only supports _netstandard1.6_ so it depends on what you are trying to do.

There has been many attempts by myself and @rpgmaker to make the support broader than the current _netstandard1.6_ however as @rpgmaker explained there are issues that frankly do not seem to be worth the trouble.

Remember you always have the option to target multiple frameworks. I would suggest you have another read of the link you posted earlier.

**Comment by rpgmaker** [comment]
Can this issue be closed?

Thanks,

**Comment by dsoronda** [comment]
@NimaAra  I'm not confused at all.
Like I said , I have NetStandard 1.4 project (it has to be referenced in both .NET Core and .NET 4.6 projects) so I can't use NetJSON in this case.

So I'll take a look at alternative JSON serializers.

Anyway, thanks for great library.

**Comment by rpgmaker** [comment]
Sorry. We could not help.
Thanks,
