### ISSUE TITLE
Issue with serializing enums with byte or short base class

### ISSUE THREAD

**Issue by physhi** [rpgmaker/NetJSON#161]
It's assumed that enum inherits from int, but if the enum inherits from short, deserialization fails (because it's trying to cast it (boxed short) to boxed int, which doesn't work).

**Comment by rpgmaker** [comment]
Thanks, I will look into it. I should already be handling it.

**Comment by rpgmaker** [comment]
Hi, 

I test it and I am not able to reproduce the issue you are facing. Could you give me an example?

My test is below

`
  [TestMethod]
        public void TestEnumHolderWithByteAndShort()
        {
            var value = new EnumHolder { BEnum = ByteEnum.V2, SEnum = ShortEnum.V2 };
            var json = NetJSON.Serialize(value, new NetJSONSettings { UseEnumString = false });

            var bJson = NetJSON.Serialize(ByteEnum.V2);
            var sJson = NetJSON.Serialize(ShortEnum.V2);

            var value2 = NetJSON.Deserialize<EnumHolder>(json);

            Assert.IsTrue(value.BEnum == value2.BEnum);
            Assert.IsTrue(value.SEnum == value2.SEnum);
        }

    public class EnumHolder
    {
        public ByteEnum BEnum { get; set; }
        public ShortEnum SEnum { get; set; }
    }

    public enum ByteEnum : byte
    {
        V1 = 1,
        V2 = 2
    }

    public enum ShortEnum : short
    {
        V1 = 1,
        V2 = 2
    }

`

**Comment by rpgmaker** [comment]
Let me know if you can reproduce the issue. If not, you can close the issue.

Thanks,

**Comment by physhi** [comment]
I'll try to get the latest bits and repro the issue again in my case. If I
can repro it, I'll send you the exact location of the failure.

Thanks

**Comment by rpgmaker** [comment]
I am closing this for now. If you reproduce it then reopen it.

Thanks,

**Comment by physhi** [comment]
No Problem,

BTW, is there anyway to work with hierarchy? I did not see any type
information in JSON.

**Comment by rpgmaker** [comment]
What do you mean? You can support type information when using type for property such as abstract and interfaces. By using NetJSON.IncludeTypeInformation.

**Comment by physhi** [comment]
I've opened an issue with a test case on what I'm trying to do. Essentially
something similar to TypeNameHandling in Json.Net
