### ISSUE TITLE
DateTime deserialization compatibility with System.Web.Script.Serialization.JavaScriptSerializer

### ISSUE THREAD

**Issue by hhblaze** [rpgmaker/NetJSON#163]
Hi there!

I got a json string generated by old, integrated into .NET
System.Web.Script.Serialization.JavaScriptSerializer

```
{"Id":"ffbc7f67-8b58-4921-8d1b-466f1584e113","Name":"MyXtest","Dscr":"","CreatorId":35,"udtCreationDate":"\/Date(1490945333848)\/","CallBackPage":"WTView","TunnelScheduleId":-1,"ExtraParameters":"DefaultRefresh=10\u0026DefaultDistance=300\u0026DefaultHours=0","LA":636265421335526365,"RT":"1","MN":"DataServicesAuto","Enabled":true}
```
I try part to move the code part that uses that JavaScriptSerializer to NetJson, but I can't find a way of correct deserialization settings for the dateTime.

JavaScriptSerializer says {31.03.2017 7:28:53}
but 
any of formats in 

```C#
var str = File.ReadAllText(@"D:\Temp\x1\nn.txt");
            var sobj = NetJSON.NetJSON.Deserialize<GccObjects.Net.GccSystem.WebTickets.WebTicket>(str,new NetJSON.NetJSONSettings { DateFormat = NetJSON.NetJSONDateFormat.Default });
```

gives wrong results

**Comment by rpgmaker** [comment]
Hi,

What do you get when using NetJSON?

Thanks,

**Comment by hhblaze** [comment]
Default {02.01.1970 18:24:54}

**Comment by hhblaze** [comment]
for all the same, except EpochTime - that throws out an error

**Comment by rpgmaker** [comment]
Interesting. I will look into it. Could you fix it for me in a pull request?

Thanks,

**Comment by hhblaze** [comment]
Hmm, if without pull requests:

in Models.cs 

```C#
	public enum NetJSONDateFormat
	{
		/// <summary>
		/// Default /Date(...)/
		/// </summary>
		Default = 0,
		/// <summary>
		/// ISO Format
		/// </summary>
		ISO = 2,
		/// <summary>
		/// Unix Epoch Milliseconds
		/// </summary>
		EpochTime = 4,
		/// <summary>
		/// JSON.NET Format for backward compatibility
		/// </summary>
		JsonNetISO = 6,
        /// <summary>
        /// .NET System.Web.Script.Serialization.JavaScriptSerializer backward compatibility
        /// </summary>
        JavaScriptSerializer = 8
    }
```

and in NetJSON.Internals
```C#
private static DateTime StringToDate(string value, NetJSONSettings settings, out TimeSpan offset, bool isDateTimeOffset) {
...
//change if (settings.DateFormat == NetJSONDateFormat.EpochTime) {
//on
switch (settings.DateFormat)
            {
                case NetJSONDateFormat.EpochTime:
                    return new DateTime(1970, 1, 1, 0, 0, 0, 0, System.DateTimeKind.Utc)
                        .AddTicks(FastStringToLong(value)).ToLocalTime();                   
                case NetJSONDateFormat.JavaScriptSerializer:                    
                    return new DateTime(1970, 1, 1, 0, 0, 0, 0, System.DateTimeKind.Utc)
                        .AddMilliseconds(FastStringToLong(value));    
                    //!!!! NOTE I am not sure it should be local time (like it's made with EpochTime),
                    //IMHO all must be stored in UTC
            }
...
```

**Comment by rpgmaker** [comment]
Thanks, default supposed to represent Microsoft format of date.

**Comment by hhblaze** [comment]
Clear, then waiting for solution, thank you!

**Comment by rpgmaker** [comment]
Thanks, will review it this evening

**Comment by rpgmaker** [comment]
I have implemented. I am alittle worried if this is correct or not. When i changed to using AddMilliseconds, a lot of test failed because adding the number in millsecond throws an error.

Please test again.

Thanks,

**Comment by hhblaze** [comment]
So, I have updated NuGet to 1.2.1.9
and executed

```C#
  var str = File.ReadAllText(@"D:\Temp\nn.txt");
//where str = {"Id":"ffbc7f67-8b58-4921-8d1b-466f1584e113","Name":"MyXtest","Dscr":"","CreatorId":35,"udtCreationDate":"\/Date(1490945333848)\/","CallBackPage":"WTView","TunnelScheduleId":-1,"ExtraParameters":"DefaultRefresh=10\u0026DefaultDistance=300\u0026DefaultHours=0","LA":636265421335526365,"RT":"1","MN":"DataServicesAuto","Enabled":true}

            var sobj = NetJSON.NetJSON.Deserialize<GccObjects.Net.GccSystem.WebTickets.WebTicket>(str, new NetJSON.NetJSONSettings { DateFormat = NetJSON.NetJSONDateFormat.Default });
```

after deserialization, the date is incorrect (shows {02.01.1970 18:24:54} instead of  {31.03.2017 7:28:53}) what do I do wrong?

but NetJSON.NetJSONDateFormat.Default should go on to work like it was working before, 
many people used its previous implementation and stored data into databases.

**Comment by rpgmaker** [comment]
I have not updated the nuget package. Will do it today after work. I added a new enum for the javascriptserializer like you recommended.

Thanks,

**Comment by hhblaze** [comment]
Ok, 
NetJSON.NetJSONDateFormat.JavascriptSerializer 
returned me  {31.03.2017 09:28:53}  instead of  {31.03.2017 07:28:53}

I think it should be UTC, not local...

**Comment by rpgmaker** [comment]
You need to set the timezone to local as the parameter of netjsonsetting. It default to unspecified

**Comment by rpgmaker** [comment]
Look at the unit test example that I recently added to see what I am referring to.

**Comment by rpgmaker** [comment]
``
var data = NetJSON.Deserialize<MicrosoftJavascriptSerializerTestData>(json, 
                new NetJSONSettings { DateFormat = NetJSONDateFormat.JavascriptSerializer,
                   TimeZoneFormat = NetJSONTimeZoneFormat.Local });

**Comment by hhblaze** [comment]
this works!

**Comment by hhblaze** [comment]
Thank you!

**Comment by rpgmaker** [comment]
The time you gave already contains the UTC offset of 4 which is why it started at the correct time. And use local detect that the kind is already correct so no transformation occurred. Next time you can use + or - for offset

**Comment by hhblaze** [comment]
Very well, thank you!
