### ISSUE TITLE
Escaping in strings

### ISSUE THREAD

**Issue by fufie** [rpgmaker/NetJSON#164]
Hei,

Currently trying to use NetJSON as a dictionary which I traverse and build my object tree, but got a bit confused over escaping behaviour that feels off. I wrote small test case below, where the behaviour for a string in a dictionary is different from a string in a NetJSON-built object.  The `TestParseStringToObject` behaves as I would expect, but `TestParseString` does not respect escaping of doublequote.  

```
namespace CommonTests.Tools
{
	using System.Collections.Generic;
	using NUnit.Framework;

	[TestFixture]
	public class TestJsonParsing
	{
		const string testJsonString = "{\"foo\":\"bar \\\"xyzzy\\\" \"}";

		public class Dummy
		{
			public string foo;
		}

		[Test]
		public void TestParseString()
		{
			var deserialisedDictionary = (Dictionary<string, object>)NetJSON.NetJSON.Deserialize<object>(testJsonString);
			var fooValue = (string)deserialisedDictionary["foo"];
			Assert.AreEqual("bar \"xyzzy\" ", fooValue);
		}

		[Test]
		public void TestParseStringToObject()
		{
			var deserialisedDummy = NetJSON.NetJSON.Deserialize<Dummy>(testJsonString);
			Assert.AreEqual("bar \"xyzzy\" ", deserialisedDummy.foo);
		}
	}
}


```

**Comment by rpgmaker** [comment]
I thanks for the find. Will look into it, it should behave the same to my knowledge because they use same code path. 

Thanks,

**Comment by rpgmaker** [comment]
One question? Do you know the solution to fixing it based on the current codebase? If so, I will appreciate a pull request.

Thanks,

**Comment by fufie** [comment]
I haven't made a dive into the code base to investigate - just isolated the test above. I could have a look later tonight.

Cheers,

**Comment by rpgmaker** [comment]
Thanks, that will be great.

**Comment by fufie** [comment]
After tweaking the build rules for OSX+Mono I am able to get a small test application, but admittedly due to the dynamic nature of the code it isn't the easiest to debug. It's been awhile since I worked at opcode level :)

Of interest, it seems that:
`internal unsafe static string DecodeJSONString(char* ptr, ref int index, NetJSONSettings settings)` 
is only called when parsing into a string (`Dummy.foo` in the test above), but is not called for the `Dictionary`/`TestParseString` case above.

**Comment by rpgmaker** [comment]
Thanks for the catch. I guess you can start from that piece of code for the fix assuming you are working on a pull request for me.

Thanks,

**Comment by fufie** [comment]
FWIW, I had a closer look last night, but debugging was an absolute pain with my setup, so unless you have some instructions on how to set up a decent build environment any patch/pull request would take some time.  Mainly I was unable to step through the dynamically generated code, and reading opcodes in an unfamiliar code base/architecture will take time. I suspect you know this code better than me. :)

As for observations (which might help):

> it should behave the same to my knowledge because they use same code path.

The bug probably happens because they don't follow the same code path. I think it is basically a runtime "type"-check that is needed on the read object to identify it as a string when using an `object`-`Deserializer`.   When the parser "knows" it is getting a string, ie `Dummy.foo` it will use `GenerateExtractValueFor` for a `string`, but when it does this for `object` it fails to identify the string and then call `DecodeJSONString`.

Of interest is that it seems to not escape keys in the dictionary either, so legal json like `{"foo\"bar":"xyz\"zy"}` will include the backslash in the key as well as in the value. 

Might have a look this weekend, but unless I find a way to step into the generated code with the debugger it might not be too helpful.

**Comment by rpgmaker** [comment]
Thanks for looking into it. You can use GenerateAssembly property to make it save the code into a dll for you to see the output but not debug it.

**Comment by rpgmaker** [comment]
Hi,
Any progress on this issue? Do you want me to take a stab at it?

Thanks,

**Comment by fufie** [comment]
Sorry for a late reply, but I have been swamped with other issues and have been unable to look at it.  Please have a look at it.

**Comment by rpgmaker** [comment]
I tested it and if you change from using Deserialize[object] to Deserialize[string,string] it does call the string encoding logic. The problem is that the object converter does not call the method for decoding.

**Comment by rpgmaker** [comment]
I added support for using it without Deserialize[dictionary[string,string]]
