### ISSUE TITLE
Migrate the project to Visual Studio 2017

### ISSUE THREAD

**Issue by NimaAra** [rpgmaker/NetJSON#165]
@rpgmaker Have you managed to move to VS2017 on your DEV machine?

If you have, we can migrate the project so that the solution properly supports .NET Core. This will also fix the build failure in AppVeyor.

**Comment by rpgmaker** [comment]
I have 2017 on dev machine but I usually use 2015 for this project. If you can submit a pull request with support for vs 2017 that would be nice.

Thanks,

**Comment by NimaAra** [comment]
I haven't forgotten about this, it's no1 in my todo list :-)

**Comment by rpgmaker** [comment]
Thanks 😀

**Comment by rpgmaker** [comment]
This is no longer needed. Project is already migrated to 2017
