### ISSUE TITLE
Does not preserve serialized type in deserialization when using IncludeTypeInformation

### ISSUE THREAD

**Issue by physhi** [rpgmaker/NetJSON#166]
Here is a small test case. Also did not find any example of this in tests. Also, I would have expected to have some attribute support for KnownTypes, but did not find that either.

    using NUnit.Framework;
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Definition for NetJSONTests
    /// </summary>
    [TestFixture]
    public class NetJSONTests
    {
        public class FooA
        {
            public int Type
            { get; set; }

            public int IntVal
            { get; set; }
        }

        public class FooB : FooA
        {
            public string StringVal
            { get; set; }
        }

        [Test]
        public void TestHeirarchy()
        {
            var foob = new FooB
            {
                StringVal = "FooB",
                IntVal = 1,
                Type = 2
            };

            var json = NetJSON.NetJSON.Serialize(foob);
            var obj = NetJSON.NetJSON.Deserialize<FooA>(json);

            Assert.IsInstanceOf<FooB>(obj);
        }
    }

**Comment by rpgmaker** [comment]
It does. It picks the property based on the type of your deserialization. If you want type to get save into the JSON, then use NetJSON.IncludeTypeInformation to support that.

Thanks,

**Comment by physhi** [comment]
Didn't find and example, so was stuck. Thanks will update my test and see if that works

**Comment by physhi** [comment]
Update test case still fails. I get following serialization: **{"StringVal":"FooB","Type":2,"IntVal":1}**, which does not contain any typeInformation.

    using NUnit.Framework;
    /// <summary>
    /// Definition for NetJSONTests
    /// </summary>
    [TestFixture]
    public class NetJSONTests
    {
        public class FooA
        {
            public int Type
            { get; set; }

            public int IntVal
            { get; set; }
        }

        public class FooB : FooA
        {
            public string StringVal
            { get; set; }
        }

        [Test]
        public void TestHeirarchy()
        {
            var foob = new FooB
            {
                StringVal = "FooB",
                IntVal = 1,
                Type = 2
            };

            var settings = new NetJSON.NetJSONSettings
            {
                IncludeTypeInformation = true
            };
            var json = NetJSON.NetJSON.Serialize(foob, settings);
            var obj = NetJSON.NetJSON.Deserialize<FooA>(json, settings);

            Assert.IsInstanceOf<FooB>(obj);
        }
    }

**Comment by physhi** [comment]
Still the same issue, the serialized string still does not contain any typeInfo.


        [Test]
        public void TestHeirarchy()
        {
            var foob = new FooB
            {
                StringVal = "FooB",
                IntVal = 1,
                Type = 2
            };

            NetJSON.NetJSON.IncludeTypeInformation = true;
            var json = NetJSON.NetJSON.Serialize(foob);
            var obj = NetJSON.NetJSON.Deserialize<FooA>(json);

            Assert.IsInstanceOf<FooB>(obj);
        }

**Comment by rpgmaker** [comment]
Ok. I will test it myself and get back to you.

Thanks,

**Comment by rpgmaker** [comment]
change 

 var json = NetJSON.NetJSON.Serialize(foob);

to

 var json = NetJSON.NetJSON.Serialize<FooA>(foob); 

it only include the type if your serialization type does not match the type

**Comment by rpgmaker** [comment]
Using it with concrete type works.

**Comment by physhi** [comment]
Got it. Thanks. Infact, when I look back it makes sense.

One more ask, NetJSON does not support any other constructor than default
constructor or does it? I'm assuming it does not.

The reason I ask is I'm moving away from Json.Net to NetJSON (which is very
helpful when working with Redis because of serialization/deserialization
speeds). But I have use cases where do not have default constructor, and
NetJSON has issues with those classes.

**Comment by rpgmaker** [comment]
Try it out. It should work. I support immutable type .

**Comment by rpgmaker** [comment]
The issue was fixed here: https://github.com/rpgmaker/NetJSON/issues/109 and https://github.com/rpgmaker/NetJSON/issues/116 and

**Comment by rpgmaker** [comment]
Closing this issue since problem was resolved and fix for other solution exists in another fix. Reopen if needed.
