### ISSUE TITLE
Ignore property

### ISSUE THREAD

**Issue by petermorlion** [rpgmaker/NetJSON#169]
Is it possible to ignore certain properties? In JSON.NET you can use the `JsonIgnore` attribute. Something similar would be nice, though not an extremely high priority I guess.

**Comment by rpgmaker** [comment]
I could add that feature I suppose. Never thought it was needed since property not in a json string are auto skipped.

**Comment by petermorlion** [comment]
My issue is with serializing. I'm looking into using it for a WebAPI project, and not all clients will be using NetJSON. So the resulting JSON would look nicer if certain properties weren't serialized (I need the properties there for technical/legacy reasons).

But this is not that important to me. I guess you could add it if more people ask it. I just wanted to know if it was possible. No problem that it is not.

**Comment by rpgmaker** [comment]
I just added NetJSON.SerializeAs and NetJSON.CanSerialize. Using this new option will allow you to implement your own custom ignore attributes. You can find example of using it in the recent unit tests i added.

Thanks,
