### ISSUE TITLE
Using custom settings results in empty string

### ISSUE THREAD

**Issue by petermorlion** [rpgmaker/NetJSON#170]
I have a case where I can't serialize using settings. When I do this:

```
NetJSON.NetJSON.Serialize(myObject);
```

it works. But this:

```
NetJSON.NetJSON.Serialize(myObject, new NetJSONSettings());
```

gives me an empty string.

I tried to reproduce this in a new project, but it works fine there. So I'm thinking it must be due to something in the object I'm trying to serialize.

Any idea why I could be getting an empty string (and not an exception) when using custom settings? I'm willing to look further into this, but don't really know where to start. I've already tried various options in the settings object.

**Comment by rpgmaker** [comment]
What is in myObject? Is it of object type that point to a class? That will point to an empty string. Anything of type object that is not primitive or an array object / dictionary of string/object is not supported for type object.

Thanks,

**Comment by petermorlion** [comment]
It's a generic class that looks something like this:

```
public class Result<T>
{
    public int Offset { get; set; }
    public int Limit { get; set; }
    public int TotalResults { get; set; }
    public T Data { get; set; }
}
```

`T` would be a `List<Customer>´ in my case, where `Customer` would have `Id` (int), `Name` (string) and `Address` (string) as properties.

But:
- this serializes perfectly when I don't pass in any settings
- I have a test project with a similar structure where it does serialize with settings

**Comment by rpgmaker** [comment]
Thanks for the sample. Will look at this weekend.

**Comment by rpgmaker** [comment]
Sorry been busy with other things. I will get to this once I merge the ongoing pull request.

Thanks,

**Comment by petermorlion** [comment]
No problem, this isn't high priority for me.

**Comment by rpgmaker** [comment]
I am not able to reproduce it. Could you give me an exact example of what gives you a blank string?

Thanks,

**Comment by petermorlion** [comment]
Unfortunately, I can no longer spend time on this (company stuff and whatnot), so if you don't mind, you can close this for me. I'm very sorry about this, but it's out of my reach. I hope you haven't invested too much time into it. Thanks for the great library though!

**Comment by ksysiekj** [comment]
hi, I think I can help you with this one. I also get empty string when serializing object with my custom setting.

 internal class Program
    {
        private static void Main(string[] args)
        {
            User user = new User
            {
                FirstName = "John",
                Id = 23,
                LastName = "Doe",
                Status = UserStatus.Pending
            };

            string json = NetJSON.NetJSON.Serialize(user);
            // outputs: {"LastName":"Doe","FirstName":"John","Id":23,"Status":3}

            json = NetJSON.NetJSON.Serialize(user, new NetJSONSettings { CamelCase = true, UseEnumString = true });
            // outputs: {"lastName":"Doe","firstName":"John","id":23,"status":"Pending"}

            object userObject = new User
            {
                FirstName = "John",
                Id = 23,
                LastName = "Doe",
                Status = UserStatus.Pending
            };
            json = NetJSON.NetJSON.Serialize(userObject);
            // outputs: {"LastName":"Doe","FirstName":"John","Id":23,"Status":3}

            json = NetJSON.NetJSON.Serialize(userObject, new NetJSONSettings { CamelCase = true, UseEnumString = true });
            // outputs: empty string

            Console.ReadLine();
        }
    }

    internal sealed class User
    {
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public int Id { get; set; }
        public UserStatus Status { get; set; }
    }

    internal enum UserStatus
    {
        Active, Inactive, Suspended, Pending
    }

**Comment by rpgmaker** [comment]
Thanks, I will try it out from my side.
