### ISSUE TITLE
Strong signing breaks struct or friend access failure

### ISSUE THREAD

**Issue by imacks** [rpgmaker/NetJSON#171]
This is similar to #145 but I'm trying to create a signed version of NetJSON (so that I can install in GAC).

Here's what I tried at first:

```C#
#if DEBUG
[assembly: InternalsVisibleTo("JsonGeneratedAssembly")]
#else
[assembly: InternalsVisibleTo("JsonGeneratedAssembly, PublicKeyToken=null")]
#endif
```

I get compile error:

```
error CS1726: Friend assembly reference 'JsonGeneratedAssembly, PublicKeyToken=null' is invalid. Strong-name signed assemblies must specify a public key in their InternalsVisibleTo declarations.
```

So I created a SNK with sn.exe:

```C#
[assembly: InternalsVisibleTo("JsonGeneratedAssembly, PublicKey=xxxxxxx")]
```

Then here:

```C#
		private static AssemblyBuilder GenerateAssemblyBuilder()
		{
			if (_assembly == null)
			{
				lock (_lockAsmObject)
				{
					if (_assembly == null)
					{
						AssemblyName assemName = new AssemblyName(JSON_GENERATED_ASSEMBLY_NAME) { Version = new Version(1, 0, 0, 0) };

						assemName.KeyPair = new StrongNameKeyPair(Convert.FromBase64String("hhhhhhh"));

#if NETSTANDARD
						_assembly = AssemblyBuilder.DefineDynamicAssembly(assemName, AssemblyBuilderAccess.Run);
#else
						_assembly = AppDomain.CurrentDomain.DefineDynamicAssembly(assemName, AssemblyBuilderAccess.RunAndSave);
#endif

						// [...]
```

That doesn't work for NETCORE btw, since there is neither `KeyPair` nor `StrongNameKeyPair` before NETSTANDARD2.0 afaik. It works for NET462, but breaks when trying to serialize structs (unit test just crash on `TestStructWithProperties` and `TestStructWithFields`). I'm too dumb to figure out why...

My alternative solution is to make everything that `JsonGeneratedAssembly.dll` needs public, but then I'll  be concerned about exposing lots of unnecessary internal APIs.

Is there any way around this? Or will we have to satisfy ourselves that we won't be strong signing this project ever?

**Comment by rpgmaker** [comment]
I have not fully thought about having a strong name assembly yet. But it looks like you are using the wrong method or an old method that might not be referenced anymore. The assembly generate method should be taking  a name of assembly.

What version are you using?

Thanks,

**Comment by imacks** [comment]
I'm using the code from your master branch, if that's what you are referring to.

[inside the big NetJSON.cs](https://github.com/rpgmaker/NetJSON/blob/master/NetJSON/NetJSON.cs)

At line 1280:

```C#
                        _assembly =
#if NET_CORE
                AssemblyBuilder
#else
                AppDomain.CurrentDomain
#endif
                        .DefineDynamicAssembly(
                            new AssemblyName(NET_JSON_GENERATED_ASSEMBLY_NAME) {
                                Version = new Version(1, 0, 0, 0)
                            },
#if NET_CORE
                            AssemblyBuilderAccess.Run
#else
                            AssemblyBuilderAccess.RunAndSave
#endif
                            );
```

That should be equivalent to my rewrite?

**Comment by rpgmaker** [comment]
I see. It seem strange that your strong name is not been recognized when serialization is occurring. I will play with it myself and see how it is functioning. If you have a branch with the changes, could you link it here or email it to me to test the code with?

Thanks,

**Comment by imacks** [comment]
Sorry I just re-read your message. I need to clarify that I changed the value of `NET_JSON_GENERATED_ASSEMBLY_NAME` value to `JsonGeneratedAssembly`. I hope that didn't break anything 🍡 I don't know about.

I will commit my fork when I get home.

Thanks man.

**Comment by rpgmaker** [comment]
Just following up. Any progress? Been a while :)

**Comment by rpgmaker** [comment]
Since all you want is a signed version of NetJSON. Why not simply just add strong name for NetJSON and not the generated assembly for netjson? The assembly is never written to disk so it should fine unless your code is verifying all code execute path to make sure they are signed

**Comment by imacks** [comment]
Hey there. Ive been busy these days with stuff...quite a number of packages to sort out.

 The problem is that netjson dll calls code in the  dynamic assembly. From what i understand, strong signed assembly can only reference other strongly signed assemblies, whether the reference assembly is dynamic doesnt seem relevant.

**Comment by rpgmaker** [comment]
In that case. I will see if I can have a strong named version of netjson deployed to nuget.

Thanks,

**Comment by wmjordan** [comment]
@rpgmaker , deep inside @imacks 's problem is not whether NetJSON can be compiled with a strong name, but whether it can run correctly after the assembly is strong name signed.
When NetJSON strong-name-signed, it must reference strong-name-signed assemblies, which includes the dynamic assembly generated by NetJSON on the fly. At this moment, NetJSON does not generate strong-name-signed dynamic assemblies and consequently the serializer types in those assemblies will not be loaded at all.

**Comment by rpgmaker** [comment]
I see. In that case I will see if it is possible to share the same snk for both the generated assembly and netjson itself.

**Comment by wmjordan** [comment]
@rpgmaker, to make the assembly strong-name signed, firstly you create a snk file.
Then export its public key using the sn.exe tool:
````
sn.exe -p netjson.snk netjson.public.snk
````
The generated bytes of netjson.public.snk can be loaded into the `StrongNameKeyPair` instance, like @imacks showed.
````
AssemblyName assemName = new AssemblyName(JSON_GENERATED_ASSEMBLY_NAME) { Version = new Version(1, 0, 0, 0) };
assemName.KeyPair = new StrongNameKeyPair(/* Bytes of NetJsonPublic.snk here*/);

#if NETSTANDARD
	_assembly = AssemblyBuilder.DefineDynamicAssembly(assemName, AssemblyBuilderAccess.Run);
#else
	_assembly = AppDomain.CurrentDomain.DefineDynamicAssembly(assemName, AssemblyBuilderAccess.RunAndSave);
#endif
````
At least, run the following command
````
sn.exe -tp netjson.public.snk
````
A hash string will be displayed afterward.
Copy it to replace the xxxx in the following line.
````
[assembly: InternalsVisibleTo("JsonGeneratedAssembly, PublicKey=xxxx")]
````
The code should compile and run.

The rest problem is that `StrongNameKeyPair` is unavailable in .NET Standard.

**Comment by rpgmaker** [comment]
I can #if #define my way out of the no support of net standard. It might be supported in future versions

**Comment by wmjordan** [comment]
I encountered another associated issue about the "InternalsVisibleTo" solution.
If we use WinMerge to merge NetJSON into another assembly, the serializer would not have access to the internal methods any more.

**Comment by imacks** [comment]
@rpgmaker did you encounter any issue when serializing structures? It kind of just crashed on me...

**Comment by rpgmaker** [comment]
I have not tested with struct so far. I will look into that. It looks like I will have to create a separate package for this. NetJSON.Signed. I will try to get it tested this weekend and let you know my results

**Comment by rpgmaker** [comment]
@wmjordan, You could change the following code below to try to detect merge assembly, so that the dynamic serializer can kick in. The IsPrivate method is what need to detect it some how, example could be checking the assembly info to see if it contains any metadata from ILMerge


```
private static NetJSONSerializer<T> GetSerializer()
            {
                NetJSONSerializer<T> serializer = null;
                var type = typeof(T);
                if (type.GetTypeInfo().IsGenericType)
                {
                    foreach (var item in type.GetGenericArguments())
                    {
                        if (IsPrivate(item))
                        {
                            type = item;
                            break;
                        }
                    }
                }
                if (IsPrivate(type))
                    serializer = new DynamicNetJSONSerializer<T>();
                else serializer = (NetJSONSerializer<T>)Activator.CreateInstance(Generate(typeof(T)));
                
                return serializer;
            }

            private static bool IsPrivate(Type type)
            {
                return type.GetTypeInfo().IsNotPublic ||
                        type.GetTypeInfo().IsNestedPrivate ||
                        !type.GetTypeInfo().IsVisible;
            }
```

**Comment by rpgmaker** [comment]
@wmjordan, based on https://github.com/Microsoft/ILMerge/blob/master/ILMerge/ILMerge.cs
There is an option called CopyAttributes that would allow you to make it merge all the attribute of the assembly and remove duplicate. So if you have internal visible to, it will get preserve i will guess? Could you try it out and let me know?

Thanks,

**Comment by wmjordan** [comment]
@rpgmaker The `CopyAttributes` setting not only copies the `InternalsVisibileTo` attribute but also other attributes such as `AssemblyProduct`, `AssemblyTitle`, etc. which is not a desirable behavior.
Explicitly adding an `InternalsVisibileTo` attribute to the primary assembly, referring to the NetJSON assembly will be the workaround at this moment.

**Comment by rpgmaker** [comment]
I see. I guess ILMerge should give an option to specify it without the use of primary assembly hack.

**Comment by rpgmaker** [comment]
Please try the suggested work around. And feel to reopen this issue if you want a more standard solution for it.

Thanks,

**Comment by wmjordan** [comment]
A more elegant solution for the ILMerge issue might be using the `AttributeFile` (`attr`) setting, by providing a small and almost-empty assembly file which contains only the `InternalVisibleToAttribute` to merge with the other assembly files:
https://github.com/Microsoft/ILMerge/blob/master/ilmerge-manual.md#25-attributefile

**Comment by rpgmaker** [comment]
That sounds better I suppose. Does not feel like a hack 😀

**Comment by wmjordan** [comment]
I found another approach to solve the `ILMerge` problem recently.

Function pointers and `Calli` is the way to go.
Afterwards, there's no need to use the `InternalsVisisbleToAttribute` any more.

**Comment by rpgmaker** [comment]
How does this help with signing, though?

**Comment by wmjordan** [comment]
The signing can be retained as it is currently, which is another story.

Function pointers can help bypass the accessibility check, thus you can get rid of the `InternalsVisibleToAttribute`.

**Comment by wmjordan** [comment]
The implementation workflow:
1. Define a static type in the dynamic module.
2. Define quite a few fields within that static type, each of them is typed `IntPtr`.
3. Obtain function pointers from methods in your internal helper class, and assign them to those fields via reflection or emitting dynamic assembly.
4. Replace previous direct calls to internal helper classes with indirect calls (`OpCodes.Call` to `OpCodes.Calli`)
