### ISSUE TITLE
Support to custom serialization attributes

### ISSUE THREAD

**Issue by dimzon** [rpgmaker/NetJSON#172]
Sometimes model are placed in separate project and you can't control it (can't place NetJONProperty attributes). Or model is too huge and you are switching from another serialzation framework/library....

I discovered it's pretty easy to add support for any custom attribute. Just add 2 properties to NetJSONOptions:
```Func<MemberInfo,bool> CanSerialize``` and ```Func<MemberInfo,string> SerializeAs``` so user can provide his own implementation to analyze any attributes....

**Comment by rpgmaker** [comment]
Could you submit a pull request for it? Since it is just an additional inline instruction to call. I don't understand the other "SerializeAs". It is for changing the name of member?

Thanks,

**Comment by dimzon** [comment]
>  I don't understand the other "SerializeAs". It is for changing the name of member?
Yes. I made dirty hack to reuse XmlAttribute/XmlElement/XmlIgnore attributes:
```
       static void lookup<T>(ref NetJSONPropertyAttribute attr, MemberInfo mi, Func<T, string> nameExtracor) where T : Attribute
        {
            if (attr != null) return;
            var a = mi.GetCustomAttributes(typeof(T), true).OfType<T>().FirstOrDefault();
            if(a==null) return;
            attr = new NetJSONPropertyAttribute(nameExtracor(a));
        }

        internal static NetJSONMemberInfo[] GetTypeProperties(this Type type) {
            return _typeProperties.GetOrAdd(type, key => {
                lock (GetDictLockObject("GetTypeProperties")) {
                    var props = key.GetProperties(PropertyBinding)
                        .Where(x => x.GetIndexParameters().Length == 0)
                        .Where(x=>x.GetCustomAttributes(typeof(XmlIgnoreAttribute),true).Length==0)
                        .Select(x =>
                        {
                            var attr = x.GetCustomAttributes(_netjsonPropertyType, true)
                                    .OfType<NetJSONPropertyAttribute>()
                                    .FirstOrDefault();
                            lookup<XmlAttributeAttribute>(ref attr, x, it=>it.AttributeName);
                            lookup<XmlElementAttribute>(ref attr, x, it=>it.ElementName);
                            lookup<XmlArrayAttribute>(ref attr, x, it=>it.ElementName);
                            return new NetJSONMemberInfo
                            {
                                Member = x,
                                Attribute = attr
                            };
                        });
                    if (_includeFields) {
                        props = props.Union(key.GetFields(PropertyBinding).Select(x => new NetJSONMemberInfo { Member = x, Attribute = x.GetCustomAttributes(_netjsonPropertyType, true).OfType<NetJSONPropertyAttribute>().FirstOrDefault() }));
                    }
                    var result = props.ToArray();

```

**Comment by rpgmaker** [comment]
Interesting solution. You can create a pull request for it and I can merge it up.

Thanks,

**Comment by rpgmaker** [comment]
Let me know if you are able create a pull request for it. Else i will look into making it myself after i test it

**Comment by rpgmaker** [comment]
Please test it. I added it as NetJSON.SerializeAs and NetJSON.CanSerialize because it is impossible to make it a setting because i cache the types ahead of time and do not check them at runtime.
