### ISSUE TITLE
Enum flags do not work

### ISSUE THREAD

**Issue by physhi** [rpgmaker/NetJSON#173]
Enum Flags do not seem to work as expected. when using multiple flag bits, it deserializes the value to 0. Serialization works fine.

Test case below.

`   using NUnit.Framework;
    using System;

    [TestFixture]
    public class NetJSONTests
    {
        [Flags]
        public enum TestFlags
        {
            A = 1,
            B = 2,
            C = 4
        }

        public class FooA
        {
            public int Type
            { get; set; }

            public int IntVal
            { get; set; }

            public TestFlags EnumVal
            { get; set; }
        }

        [Test]
        public void TestEnumFlags()
        {
            var foob = new FooA
            {
                IntVal = 1,
                EnumVal = TestFlags.A | TestFlags.B,
                Type = 2
            };

            NetJSON.NetJSON.IncludeTypeInformation = true;
            var json = NetJSON.NetJSON.Serialize((FooA)foob);
            var obj = NetJSON.NetJSON.Deserialize<FooA>(json);

            Assert.AreEqual(obj.EnumVal, foob.EnumVal);
        }
}
`

**Comment by rpgmaker** [comment]
Can you try passing netjsonsetting and use "enum string" property and see if it does preserve it? If it does, it might just be missing from the int version of enum only. I believe this was implement a long time ago. What version are you using?

Thanks,

**Comment by rpgmaker** [comment]
This issue seem to be similar with https://github.com/rpgmaker/NetJSON/issues/130 .

**Comment by physhi** [comment]
Even "UseEnumString" does not work. It Serializes enum just fine as string, but deserialization fails.

I'm using ver: v1.2.1.9, last updated Jan 30th from nuget.

**Comment by rpgmaker** [comment]
It is a small issue that was caused by expecting a attribute for the enum data member. I will fix it tonight. Can you submit the full error for it 

Thanks,

**Comment by rpgmaker** [comment]
Please try it again. It should work now. Thanks again for the find
