### ISSUE TITLE
customizing enum serialization

### ISSUE THREAD

**Issue by ksysiekj** [rpgmaker/NetJSON#175]
hi, I would like to be able to customise enum serialization. I know that there is UseEnumString setting flag but what in case when my object consist of two enums and i want to be able to serialize as a string and the other one as int. IMHO the NetJSONProperty could be extended and have UseEnumString property like below:

internal class Program
    {
        private static void Main(string[] args)
        {
            User user = new User
            {
                FirstName = "John",
                Id = 23,
                LastName = "Doe",
                Status = UserStatus.Suspended,
                AccountType = AccountType.External
            };

            string json = NetJSON.NetJSON.Serialize(user);
            // outputs: {"Status":2,"AccountType":"External","LastName":"Doe","FirstName":"John","Id":23}

            Console.ReadLine();
        }
    }

    internal abstract class Person
    {
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public int Id { get; set; }
    }

    internal sealed class User : Person
    {
        [NetJSONProperty{UseEnumString = false}]

        public UserStatus Status { get; set; }

    [NetJSONProperty{UseEnumString = true}]

        public AccountType AccountType { get; set; }
    }

    internal enum AccountType
{
    Internal, External, Demo
}

internal enum UserStatus
{
    Active, Inactive, Suspended, Pending
}

Is it doable?

**Comment by rpgmaker** [comment]
It is doable, but it is a very special case scenario. It sound like the data type for the other enum should be the corresponding expected type such as int or string so that one of them uses the default setting of what enum does. The best I could do is extend the current registerTypeSerializer method to get called when a flag is enabled else it will cause some slow down in the overall code.

**Comment by rpgmaker** [comment]
I don't mind taking a pull request for this if possible.

**Comment by rpgmaker** [comment]
I am closing this for now. Please reopen if this is still important.

Thanks,
