### ISSUE TITLE
missing Deserialize(Type type, string value,NetJSONSettings settings) method

### ISSUE THREAD

**Issue by ksysiekj** [rpgmaker/NetJSON#176]
i need to serialize object with camelCase nad then in the application there is a need to deserialize back to target type but camelcased string could not be deserialized to object correctly because of properties names mismatch.

internal class Program
    {
        private static void Main(string[] args)
        {
            User user = new User
            {
                FirstName = "John",
                Id = 23,
                LastName = "Doe",
                Status = UserStatus.Suspended,
                AccountType = AccountType.External
            };

            string json = NetJSON.NetJSON.Serialize(user, new NetJSONSettings { CamelCase = true });
            // outputs: {"status":2,"accountType":1,"lastName":"Doe","firstName":"John","id":23}

            object userObject = NetJSON.NetJSON.Deserialize(typeof(User), json);
![deserializescreen](https://user-images.githubusercontent.com/23241739/28457328-f3e5577c-6e05-11e7-93cb-12f0c6128e5a.png)

            // method like this should be available
            // object userObject = NetJSON.NetJSON.Deserialize(typeof(User), json,new NetJSONSettings { CamelCase = true } );

            Console.ReadLine();
        }
    }

    internal abstract class Person
    {
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public int Id { get; set; }
    }

    internal sealed class User : Person
    {
        public UserStatus Status { get; set; }

        public AccountType AccountType { get; set; }
    }

    internal enum AccountType
    {
        Internal, External, Demo
    }

    internal enum UserStatus
    {
        Active, Inactive, Suspended, Pending
    }

**Comment by rpgmaker** [comment]
You need to pass case sensitive false to your settings and it works

**Comment by rpgmaker** [comment]
Why are you using type when you know your type?

**Comment by ksysiekj** [comment]
i dont know it when doing deserialization. i have info only about deserialized object type - not specific one but generic Type type

**Comment by rpgmaker** [comment]
Ok. I could easily add the option I guess

**Comment by rpgmaker** [comment]
Please retest it. I added a unit test to valid it also. Make sure to put CaseSensitive false since you are using camelcase
