### ISSUE TITLE
Exceptions when trying to serialize an interface

### ISSUE THREAD

**Issue by KTW-NIRAS** [rpgmaker/NetJSON#179]
I get these exceptions when trying to serialize simple interface types:
- FatalExecutionEngineError
- ExecutionEngineException

I have tried to set this property, as suggested in the bottom of #78
NetJSON.IncludeTypeInformation = true

**Comment by rpgmaker** [comment]
Can you post the sample code of the class you are serializing?

Thanks,

**Comment by KTW-NIRAS** [comment]
Yes of course, this sample actually throws several exceptions:

```
public interface IPerson
{
    string Name { get; set; }
}
public class Person : IPerson
{
    public string Name { get; set; }
}

```
```
// This did work at some point, but the NetJSONCachedSerializer seems to remember the failed attempts? (IncludeTypeInformation might have been set to false)
Person p1 = new Person { Name = "Bob" };
NetJSON.NetJSON.Serialize(p1, new NetJSON.NetJSONSettings { IncludeTypeInformation = true });

// TypeInitializationException (Something about identical types in NetJSONCachedSerializer)
var p2 = new Person { Name = "John" };
NetJSON.NetJSON.Serialize(p2, new NetJSON.NetJSONSettings { IncludeTypeInformation = true });

// These throws the above exceptions (FatalExecutionEngineError/ExecutionEngineException)
IPerson p3 = new Person { Name = "Carl" };
NetJSON.NetJSON.Serialize(p3, new NetJSON.NetJSONSettings { IncludeTypeInformation = true });
```

**Comment by rpgmaker** [comment]
Can you change your interface to an abstract class and let me know if you are still getting same error?

Thanks,

**Comment by KTW-NIRAS** [comment]
Yes, I am now using an abstract class in my tests. (BasePerson)

Now all of the above examples fail with the same error:
TypeInitializationException -> Access denied: 'NetJSON.NetJSONSerializer`1[UserQuery+BasePerson]'

**Comment by rpgmaker** [comment]
Interesting, thanks for checking. I will look into this tomorrow.

**Comment by rpgmaker** [comment]
Btw, setting IncludeTypeInformation on NetJSON setting does nothing at this point. You need to set it using NetJSON.IncludeTypeInformation = true since it is a global

**Comment by rpgmaker** [comment]
I tested with Abstract class and it works fine. I think your Access Denied is due to access level of your class. Can you make sure it is not private or internal class. I was able to reproduce the Interface issue and working on it now.

**Comment by rpgmaker** [comment]
Please test again and let me know if it works for you now.

**Comment by KTW-NIRAS** [comment]
Cool, thanks!

Btw. it doesn't like the ICollection<T> type.
Is there any way to make it serialize read only interface properties? (No setter)

**Comment by rpgmaker** [comment]
I guess I can do so too since they are all interfaces for collection.

Thanks,

**Comment by rpgmaker** [comment]
I added support for ICollection. Please test again.

Thanks,

**Comment by KTW-NIRAS** [comment]
ICollection<> now works.

Thanks!
