### ISSUE TITLE
unicode escape support (\u four-hex-digits)

### ISSUE THREAD

**Issue by kenjiuno** [rpgmaker/NetJSON#183]
Hi.

Is it able to decode unicode escape (\u four-hex-digits) like `"\u56f3\u9762"` to `"図面"`, described at http://json.org/
I get undecoded string `"\\u56f3\\u9762"` on NetJSON 1.2.1.10.

**Comment by rpgmaker** [comment]
So you are getting \\uvalue when deserializing? Anything is possible I suppose. The code changes can be done in the encore method to preserve it from add the extra escape.

Thanks,

**Comment by rpgmaker** [comment]
any comment?

**Comment by wmjordan** [comment]
Hi, @kenjiuno :

You may have to provide more detail about the reproduction of the problem.
I tested with the following statement and it returned the two Japanese characters you mentioned above:
````C#
NetJSON.NetJSON.Deserialize<string>("\"\u56f3\u9762\"")
````

@rpgmaker I found another potential security problem with the latest source code.
Change the double quotes in the above JSON string to single quotes.
````C#
NetJSON.NetJSON.Deserialize<string>("'\u56f3\u9762'")
````
It will produce unexpected result like the following (executed in the _C# Intermediate_ window of VS):
````C#
"\0ʳ\0ā\0\0\0\u0002\0\u0004\0\b\0\n\0離߮\u1afe\0\n\0\u0001\0\0\0\u0004\0\u0006\0뇠߮<\0\0\0\0\0\u0004\0\b\0눜߮\0\0\0\0\0\0\u0004\0눜߮\0\0\u0001\0Ā\0\0\0\u0004\0\u0006\0\b\0\n\0\f\0\u0010\0\u0012\0\u0016\0\u001a\0눜߮\u001a\0\0\0\0\0\u0004\0눶߮\0\0\0\0\0\0\u0004\0\b\0\f\0눶߮\0\0\u0003\0\0\0Ā\0\0\0\u0002\0\u0004\0\u0006\0\b\0\f\0\u000e\0\u0012\0\u0016\0\u0018\0눶߮H\0\0\0\u0001\0\0\0\u0004\0\u0006\0뉾߮\0\0\0\0\u0001\0\0\0\u0004\0\b\0\f\0\u000e\0뉾߮\0\0\0\0Ā\0\0\0\u0004\0\b\0\n\0뉾߮\0\0\0\0\u0001\0\0\0\u0004\0\b\0\f\0\u0010\0\u0012\0뉾߮\0\0\u0004\0\u0001\0\0\0\u0004\0\b\0\f\0\u000e\0뉾߮8\0G\0\u0001\0\0\0\u0002\0\u0004\0늶߮Ĝ\0\0\0\u0001\0\0\0\u0002\0\u0004\0\u0006\0\n\0돒߮\0\0\u0003\0ā\0\0\0\u0002\0\u0004\0돒߮\f\0\0\0ā\0\0\0\u0002\0\u0004\0돞߮\0\0\0\0ā\0\u0002\0\u0004\0\u0006\0\b\0돞߮\0\0\0\0ā\0\u0002\0\u0004\0돞߮\0\0\0\0āā\u0002\0\u0004\0\u0006\0\b\0\f\0\u0010\0돞߮\0\0\0\0\0\0\0\0\u0002\0\u0004\0\b\0돞߮\0\0\0\0Ā\0\u0004\0\u0006\0돞߮\0\0\0\0ā\0\u0002\0\u0004\0돞߮\0\0\0\0\u0001\0\u0002\0\u0004\0돞߮\0\0\0\0Ā\u0001\u0004\0\u0006\0\b\0돞߮\0\0\u...
````

**Comment by rpgmaker** [comment]
Thanks for the catch. I will look into it. If you could create a bug to track it, that would be nice too.

Thanks,

**Comment by wmjordan** [comment]
There's also some problems in the source code of the `DecodeJSONString` method, regarding the Unicode decoding section for `\u????`.
````C#
const int offset = 0x10000;

// problem 1: (security) there may not be 4 more characters after the \u sequence
// problem 2: (performance) if possible, read the encoded character sequence one by one
//          and calculate the int number for "uu", so the temporary string "str" can be avoided
var str = new string(ptr, index + 1, 4);
var uu = Int32.Parse(str, NumberStyles.HexNumber);

// problem 3: (performance) append the (char)uu directly to sb, don't create the string
var u = uu < offset ? new string((char)uu, 1) :

// problem 4: (performance) append the two char instances one by one to sb,
//                 it is quite OK to do so, don't create the char array or the string
    new string(
        new char[]{
            (char)(((uu - offset) >> 10) + 0xD800),
            (char)((uu - offset) % 0x0400 + 0xDC00)
        }
    );
sb.Append(u);
index += 4;
break;
````

**Comment by wmjordan** [comment]
OK, I'd just created a new issue.

**Comment by kenjiuno** [comment]
> You may have to provide more detail about the reproduction of the problem.

@rpgmaker @wmjordan 
Sorry, here is a simple repro code:

```c#
using System;
using System.Collections.Generic;

namespace ConsoleApp9
{
    class Program
    {
        static void Main(string[] args) {
            var table = NetJSON.NetJSON.Deserialize<IDictionary<string, object>[]>(@"[{""title"": ""\u56f3\u9762""}]");
            Console.WriteLine(NetJSON.NetJSON.Serialize(table));
        }
    }
}
```

Output:
```
[{"title":"\u56f3\u9762"}]
```

Better:
```
[{"title":"図面"}]
```

I have encountered this problem when I tried to transfer a database table/view as a JSON.

**Comment by rpgmaker** [comment]
Btw, are you using the code from the repo or the nuget package?

Thanks,

**Comment by kenjiuno** [comment]
Hi, I have used latest nuget package installer `Install-Package NetJSON -Version 1.2.1.10`

**Comment by rpgmaker** [comment]
Do you get same output when using the current repository code?

Thanks,

**Comment by kenjiuno** [comment]
Latest master d0bb1cda0aa802e20805d5f3e1a91ad5fa0e42ae solved this issue, thanks!

![image](https://user-images.githubusercontent.com/5955540/33531566-2aa81f88-d8d2-11e7-9a37-5925d41d2f33.png)

```
title
[{"title":"図面"}]
```

**Comment by rpgmaker** [comment]
I am going to close this issue for now. And push the latest to nuget once I fix the security issue that was discovered through this issue.

Thanks,

**Comment by rpgmaker** [comment]
The latest code is now available on nuget: https://www.nuget.org/packages/NetJSON/

**Comment by kenjiuno** [comment]
Thanks I have confirmed that 1.2.2 has fixed it!
