### ISSUE TITLE
Models with loop reference

### ISSUE THREAD

**Issue by rosostolato** [rpgmaker/NetJSON#186]
I'm trying to serialize a model that has children with reference to their parents, so I guess that is why it's throwing exception. On Newtonsoft Json I use [JsonIgnore] on parents reference and all works great.
Does NetJson have a way to igonre them too?

![image](https://user-images.githubusercontent.com/27731641/33554294-403c8fee-d8e3-11e7-98b6-b32f855a7d11.png)

**Comment by rpgmaker** [comment]
It has indirect support for it. You can add it yourself using the provided extension methods. Example below

```
static void Main(String[] args){
	NetJSON.CanSerialize = CanSerialize;
}

private static bool CanSerialize(MemberInfo memberInfo)
{
	var attr = memberInfo.GetCustomAttribute<TestIgnoreAttribute>();
	if(attr != null)
	{
		return false;
	}
	return true;
}

public class TestClassWithIgnoreAttr
{
	[TestIgnore]
	public int ID { get; set; }
}

public class TestIgnoreAttribute : Attribute
{
}
```

**Comment by rpgmaker** [comment]
If the solution satisfy your question. Please help me close the issue.

**Comment by rpgmaker** [comment]
The documentation is here: https://github.com/rpgmaker/NetJSON/wiki/Quick-Guide

 NetJSON.CanSerialize
            - Allow specifying a custom delegate to implement custom attribute and other features to allow additional functionality such as Ignoring fields/properties, and etc

**Comment by rosostolato** [comment]
Great, I used the same JsonIgnore as attribute and now it ignores on serialization. But, I guess that was not my problem at all, it still throws exception.

Take a look at my models. Maybe it's not working with Icollections:
![image](https://user-images.githubusercontent.com/27731641/33555546-eeb4ba02-d8e7-11e7-916d-65cfe3422ab1.png)

I had a exception when using Newtonsoft Json too, but it was resolved with JsonIgnore. And JsonIgnore is working here, I tested ignoring the Icollection in the first class and all worked. But with these collections it's not.

**Comment by rpgmaker** [comment]
ICollection should work. Are you using the nuget package? If so, you might want to use the latest from the repo. I am waiting for a change to push the latest changes to nuget.

Thanks,

**Comment by rosostolato** [comment]
yes, I'm using from nuget

**Comment by rosostolato** [comment]
I tested now using just the first 2 classes and it's still getting exception.

![image](https://user-images.githubusercontent.com/27731641/33555878-18d46ff2-d8e9-11e7-8891-b6a52f998ae9.png)

Ignoring all collection it works

**Comment by rpgmaker** [comment]
Are you testing using the latest code from the source code repo and not nuget? The latest code should work.

Thanks,

**Comment by rosostolato** [comment]
Ok, I'm downloading the last code from repo

**Comment by rosostolato** [comment]
Great! With the last repo it works!! Thank you a lot!

**Comment by rpgmaker** [comment]
The latest code is now available on nuget: https://www.nuget.org/packages/NetJSON/
