### ISSUE TITLE
excluding properties from serialization

### ISSUE THREAD

**Issue by adaml984** [rpgmaker/NetJSON#189]
Hello,
Is possible to exclude certain properties from serialization process (e.q. via some attribute)?
Best regards,
Adam

**Comment by rpgmaker** [comment]
It is supported but you can customize whatever you want.

```
public void Main(){
	NetJSON.CanSerialize = CanSerialize;
	
	var data = new TestClassWithIgnoreAttr { ID = 100 };
    var json = NetJSON.Serialize(data);
}

private static bool CanSerialize(MemberInfo memberInfo)
{
	var attr = memberInfo.GetCustomAttribute<TestIgnoreAttribute>(); // Check for any attribute you want
	return attr == null;
}


public class TestClassWithIgnoreAttr
{
	[TestIgnore]
	public int ID { get; set; }
}

public class TestIgnoreAttribute : Attribute
{
}


```

**Comment by rpgmaker** [comment]
If that works for you. Please close the issue.

Thanks,

**Comment by adaml984** [comment]
Great, it works. thanks

**Comment by rpgmaker** [comment]
Just a note. This piece of code is compiled once at runtime into the generated serializer. So it should be stateless without depending on recurring calls.

Thanks,
