### ISSUE TITLE
Requested value 'true' was not found

### ISSUE THREAD

**Issue by cubed-it** [rpgmaker/NetJSON#190]
Hey there!

I'm having some trouble getting the library integrated in my project.
Unfortunately, I could not reproduce it in a simple test project...
When I build my big application, I get the following errors:

Example 1:
```
   System.ArgumentException
  HResult=0x80070057
  Message=Requested value 'true' was not found.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at System.Enum.Parse(Type enumType, String value)
   at NetJSON.Internals.SerializerUtilities.FlagStringToEnum[T](String value)
   at StammdatenClass.ReadEnumGender(String )
   ...
```
Example 2:
```
   {System.ArgumentException: Requested value 'true' was not found.
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at NetJSON.Internals.SerializerUtilities.FlagStringToEnum[T](String value)
   at StammdatenClass.ReadEnumWarnwertTyp(String )
   ...
```

"Gender" is an enumeration in a class that isn't even part of my Json sting.

Any idea what that could cause or what I can do to track the issue down to it's source?

Thanks!

**Comment by rpgmaker** [comment]
What version of .net are you using?

Thanks,

**Comment by rpgmaker** [comment]
Can you post your class definition? As for the read showing your enum; it is for precomputing the mapping of enum to string and int.

Thanks,

**Comment by cubed-it** [comment]
Deserialization takes place in a .netstandard1.6 project wich is referenced by a uwp 16299 project with Microsoft.NETCore.UniversalWindowsPlatform 6.0.6. - But if I create a striped down sample project of this type it is working...

There is nothing special about the enums I would say. e.g. for "Gender" Deserialize<RechteSet>(json)

```
   public class RechteSet
   {
      public RechteSet()
      {
         Users = new List<Benutzer>();
         ....
      }

      public IEnumerable<Benutzer> Users { get; set; }

      .....
   }

   public class Benutzer : IBenutzer
   {
      public Benutzer()
      {
      }

      public Benutzer(IBenutzer benutzer)
      {
           ....
      }

      public Gender Gender { get; set; }

      ....
   }
   public enum Gender { Female = 0, Male = 1, Neutral = 2 };
```

**Comment by rpgmaker** [comment]
Can I see the json string you are using for deserializing? It is strange that it is failing in that method. I will take a look at it later tonight

**Comment by rpgmaker** [comment]
Can i see your data? It seem like the problem is your dataset. Because there is no way this will get this error unless it is feed the specific information that it is trying to parse

**Comment by cubed-it** [comment]
That's really strange... netjson can deserialize my json string in a sample linqpad project without any problem. But it can't in my large solution. However other serializers like jsonnet and servicestack can do the job since several years.
I will see if I can find the reason. But it may take a while, doing this beside my normal todo's.
If you have any idea where I can look further just let me know.

**Comment by cubed-it** [comment]
Yeah, my bad. The error message is somehow misleading. Runs fine now, can be closed. Thanks for your help!

It's definitely faster than the competition. After the types are known even very clear the number 1.
Would it be possible to keep the generated assembly and not analyze the types again at the next start of the application?

**Comment by rpgmaker** [comment]
Yes, you can use the following method to create the precompiled assembly for it.

NetJSON.GenerateTypesInto(string asmName, params Type[] types)
	- This method allows you to specify a list of types you would like to serialize and deserialize  and output an assembly which will contain the code that can be reference for precompile serialization code
	- Using this method allow you to avoid the initial cost of generating the classes needed to serialize your objects

**Comment by cubed-it** [comment]
Very cool. But it looks like the AssemblyBuilder can't save under net core. Let's see what Microsoft can do there in the future.
Thanks again!!

**Comment by rpgmaker** [comment]
Sorry, I guess we will see what ms does in the future.

Thanks,
