### ISSUE TITLE
Problem deserializing big int

### ISSUE THREAD

**Issue by Helven12** [rpgmaker/NetJSON#192]
When deserializing a Json that contains a number greater than 9 digits the number is changed to 1410065407.

**Comment by rpgmaker** [comment]
Could an example of the json?

Thanks,

**Comment by Helven12** [comment]
It can be replicated with this line:
var test = NetJSON.Deserialize<Dictionary<string,object>>("{\"test\":9999999999}");

**Comment by rpgmaker** [comment]
Thanks, I will look into it later today.

**Comment by rpgmaker** [comment]
Please test again and thanks for the find
