### ISSUE TITLE
Serializing fields with an escape character

### ISSUE THREAD

**Issue by marianoFIUBA** [rpgmaker/NetJSON#194]
Differents results between versions 1.2.1.5 and 1.2.3 when serializing fields containing an escape character ("\\").

Sample code:

var testDictionary = new Dictionary<string, object>();
testDictionary["Path"] = "\\\\fabcde\\pabcde\\abcde\\abcde.txt";
NetJSON.Serialize(testDictionary); 

Result with 1.2.1.5:
"{\"Path\":\"\\\\fabcde\\pabcde\\abcde\\abcde.txt\"}"

Result with 1.2.3:
"{\"Path\":\"\\fabcdeabcdebcdebcde.txt\"}"

**Comment by rpgmaker** [comment]
Thanks for the find. I must have broke it with the last update in regards to object type serialization. I will look into tonight.

Does it work fine if the type is a string type instead of object?

Thanks,

**Comment by marianoFIUBA** [comment]
It works fine with strings in 1.2.3

var testString = "\\\\fabcde\\pabcde\\abcde\\abcde.txt";
NetJSON.Serialize(testString); 
"\"\\\\\\\\fabcde\\\\pabcde\\\\abcde\\\\abcde.txt\""

Thanks.

**Comment by rpgmaker** [comment]
Then I guess I did break the object serialization logic.

**Comment by rpgmaker** [comment]
Thanks for the find. It seem that at some point, i mixed up the method calls. I was calling decode string all the time for both deserialization and serialization of object strings. I will push nuget in a minute

**Comment by marianoFIUBA** [comment]
Thanks!!!
