### ISSUE TITLE
Deserialisation Returns Rules as NULL

### ISSUE THREAD

**Issue by dev-day** [rpgmaker/NetJSON#195]
Hi,

My JSON is:

[{
	"Join": "and",
	"Boost": 1,
	"Maths": "+",
	"Rules": [{
		"key": "attributes.dietary_requirement",
		"display": "Attributes.Dietary Requirement",
		"operator": "equals",
		"type": "text",
		"values": ["vegan", "Dairy Free", "Wheat Free", "Gluten Free", "Organic"]
	}]
}, {
	"Join": "and",
	"Boost": 2,
	"Maths": "+",
	"Rules": [{
		"key": "dateintroduced",
		"display": "Date Introduced",
		"operator": "gt",
		"type": "date",
		"values": ["01-Mar-2018"]
	}]
}]

My Model is:

    public class Rule
    {
        public string Name { get; set; }
        public string Entity { get; set; }
        public string Type { get; set; }
        public string DataType { get; set; }
        public string Key { get; set; }
        public string Display { get; set; }
        public string Operator { get; set; }
        public string[] Values { get; set; }

    }

    public class RuleGroup
    {
        public string Join { get; set; }
        public int? Boost { get; set; }
        public string Maths { get; set; }
        public List<Rule> Rules { get; set; }
    }

When I deserialise the above JSON into List<RuleGroup>, I get the main object filled in.
However, the Rules list has 1 entry but that entry has NULLs for every value.

Please can you advise?

Dev

**Comment by rpgmaker** [comment]
Can you show me how you are calling the deserialize logic?

Thanks,

**Comment by dev-day** [comment]
Hi,

Thank you for getting back to me so promptly.
Yes, my code is:

 List<RuleGroup> boostFactors = new List<RuleGroup>();
    if (Model.BoostFactors != null)
    {
        try
        {
            //boostFactors = Newtonsoft.Json.JsonConvert.DeserializeObject<List<RuleGroup>>(Model.BoostFactors);
            boostFactors = NetJSON.NetJSON.Deserialize<List<RuleGroup>>(Model.BoostFactors);
            
        }
        catch
        {
        }
    }

I have replaced by Newtonsoft line with the new line above.

Regards,
Dev

**Comment by dev-day** [comment]
Hi,

Thank you for getting back to me so promptly.
Yes, my code is:

```
List boostFactors = new List();
if (Model.BoostFactors != null)
{
try
{
//boostFactors = Newtonsoft.Json.JsonConvert.DeserializeObject<List>(Model.BoostFactors);
boostFactors = NetJSON.NetJSON.Deserialize<List>(Model.BoostFactors);

    }
    catch
    {
    }
}

```
I have replaced by Newtonsoft line with the new line above.

Regards,
Dev

**Comment by dev-day** [comment]
Hi,

Thank you for getting back to me so promptly.
Yes, my code is:

    ```
List<RuleGroup> boostFactors = new List<RuleGroup>();
    if (Model.BoostFactors != null)
    {
        try
        {
            //boostFactors = Newtonsoft.Json.JsonConvert.DeserializeObject<List<RuleGroup>>(Model.BoostFactors);
            boostFactors = NetJSON.NetJSON.Deserialize<List<RuleGroup>>(Model.BoostFactors);
            
        }
        catch
        {
        }
    }

```


I have replaced by Newtonsoft line with the new line above.

Regards,
Dev

**Comment by dev-day** [comment]
Hi,

If I go back to Newtonsoft it works fine.
When I switch back to NetJSON it seems to fail (the Rules node has 1 item which has all values as NULL).

Regards,
Dev

**Comment by rpgmaker** [comment]
Ok. Thanks. I will take a look at it this noon.

**Comment by rpgmaker** [comment]
It is working properly. You just need to pass the setting object and tell it to not be case-sensitive which is true by default.
```

var json = File.ReadAllText("rule_object.txt");
var boostFactors = NetJSON.Deserialize<List<RuleGroup>>(json, new NetJSONSettings { CaseSensitive = false });
```

**Comment by rpgmaker** [comment]
You can find additional information about the different options here: https://github.com/rpgmaker/NetJSON/wiki/Quick-Guide. 

Do reopen this issue if it is still a problem. 

Thanks,
