### ISSUE TITLE
Infinite loop during deserialization of expando object property that end with "\\"

### ISSUE THREAD

**Issue by isorak** [rpgmaker/NetJSON#197]
Error  (infinite loop) during deserialization of string that end with "\\" 

Sample test code (VB)

Dim test As List(Of Dynamic.ExpandoObject)
test = NetJSON.NetJSON.Deserialize(Of List(Of Dynamic.ExpandoObject))("[{""StringValue"":""C:\\\\ProgramData\\\\""}]")

**Comment by rpgmaker** [comment]
Thanks for the fine, i will look into it. Could you try using List[Dictionary[String,String]] instead? ExpandoObject support is not designed as you are currently using it.

**Comment by rpgmaker** [comment]
You could also try using List[object] since it will automatically Dictionary[String,Object] internal for the object representation.

**Comment by rpgmaker** [comment]
Any update on changing the object to something else?

Thanks,

**Comment by isorak** [comment]
I can change to Dictionary(Of String, String) without problem, if i use Dictionary(Of String, object) i've the same problem. I maintain Expando because is very useful to handle whatever present (number,date, etc). I paying attention my content not end with '\'

**Comment by rpgmaker** [comment]
I see. To better understand, you are saying that dictionary of string object work, right? But you want expando to work similar?

Thanks,

**Comment by rpgmaker** [comment]
Thanks, i found the bug now. I try to see if i can fix it by tomorrow. Thanks again for the find :)

**Comment by rpgmaker** [comment]
Sorry it been a while. Still trying to resolve the issue :)

**Comment by rpgmaker** [comment]
I will take a look at this weekend. Sorry it been a while. Thanks

**Comment by Krakean** [comment]
@rpgmaker any progress on this? :)

**Comment by rpgmaker** [comment]
I have been busy with other stuff. I look at it again, I promise this weekend for sure.

**Comment by rpgmaker** [comment]
Please test it again, i have fixed it. And also publish it to nuget. It should be available soon.

Thanks,
