### ISSUE TITLE
NetJSONCachedSerializer throw InvalidOperationException when placing serialize and deserializeobject at the same method

### ISSUE THREAD

**Issue by Nexxkinn** [rpgmaker/NetJSON#199]
The code(simplified):
`string test = NetJSON.NetJSON.Serialize(graphqltest);`
`string content = "{\"data\":{\"MediaListCollection\":{\"lists\":[{\"name\":\"Rewatching\".....`
`var x = NetJSON.NetJSON.DeserializeObject(content) ;`

Returns

> System.TypeInitializationException
>   HResult=0x80131534
>   Message=The type initializer for 'NetJSONCachedSerializer`1' threw an exception.
>   Source=NetJSON.Core
>   StackTrace:
>    at NetJSON.NetJSON.DeserializeObject(String json)
>    at ConsoleApp1.Program.<Main>d__2.MoveNext() in C:\Users\*user*\source\repos\ConsoleApp1\ConsoleApp1\Program.cs:line 99
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at ConsoleApp1.Program.<Main>(String[] args)
> 
> Inner Exception 1:
> InvalidOperationException: Unable to import a global method or field from a different module.
> 

I can assure you that the program runs correctly if one of them got removed.

**Comment by rpgmaker** [comment]
Are you running in .net core or .net framework?

Thanks,

**Comment by Nexxkinn** [comment]
Console .Net Core 2.0

**Comment by rpgmaker** [comment]
Thanks, will take a look at it this evening.

**Comment by rpgmaker** [comment]
Not able to reproduce it with my own local test.

![image](https://user-images.githubusercontent.com/557807/44292586-80b30000-a253-11e8-93a6-8dcb360b455c.png)

**Comment by Nexxkinn** [comment]
Here ya go
[Program.cs.txt](https://github.com/rpgmaker/NetJSON/files/2299006/Program.cs.txt)

**Comment by rpgmaker** [comment]
Thanks

**Comment by rpgmaker** [comment]
This is going to take a bit longer. It seems to be an issue with usage of DynamicMethod. The same code works in .net framework

**Comment by rpgmaker** [comment]
I fixed it and pushed the changes to 1.2.7 nuget package. Please test and let me know if you find any other issues.

Thanks,
