### ISSUE TITLE
Please, integrate .NetFramework 4.7.2 binary into NuGet package

### ISSUE THREAD

**Issue by hhblaze** [rpgmaker/NetJSON#200]
Please, integrate .NetFramework 4.7.2 into NuGet package, otherwise it tries to use .NETStandard binary and adds a tone of .NET Core system libraries into .NET Framework project.

**Comment by rpgmaker** [comment]
Thanks for the find. I have noticed that too myself lately

**Comment by hhblaze** [comment]
I think it is still not solved for .NetCore 2.1 (when Project is .NetCore 2.1 embedding NetJson needs a couple of files)

![image](https://user-images.githubusercontent.com/486781/44648790-7676cb80-a9e2-11e8-9076-b98d8c3c8fe6.png)

**Comment by rpgmaker** [comment]
Thoses files are required for .net core since I am using .net standard 2.0 for managing the code for it. Are you expecting a .net core 2.0+ library with no dependency? I can look into that and see if it is possible.

Thanks,
