### ISSUE TITLE
Deserialization mistake of boolean value

### ISSUE THREAD

**Issue by hhblaze** [rpgmaker/NetJSON#203]
NetJSON versions 1.2.7
Object can be deserialized but shows incorrect boolean value.

File netjson.txt contains generated (by NetJSON) a JSON-string -  serialized object YadroUser from attached file netjsonObj.txt. 

Reproducing:

```C#
var usr = NetJSON.NetJSON.Deserialize<TEST.YadroUser>(File.ReadAllText(@"D:\Temp\1\netjson.txt"));
```

Value "Enabled" after deserialization is true, though must be false.

[netjson.txt](https://github.com/rpgmaker/NetJSON/files/2520443/netjson.txt)
[netjsonObj.txt](https://github.com/rpgmaker/NetJSON/files/2520444/netjsonObj.txt)

**Comment by rpgmaker** [comment]
In looking at your object. You don't have "Enabled" in your netjson.txt string. And since you have a constructor that initialize the YadroUser object which set Enabled = true. It will be true by default. 

Since this is the step that occurs during deserialization.

- Create a new instance of object using the constructor
- Load json string and parse it and all it properties that match object

**Comment by hhblaze** [comment]
Thanx, I see that....was a bit it's xml tag... closing the issue

**Comment by rpgmaker** [comment]
Np. 👍

**Comment by hhblaze** [comment]
In total this problem appeared, because default boolean (and probably other types) value is not storing together with the JSON object. 
I couldn't implement the idea that after initializing class YadroUser (from NetJsonObj.txt) the defualt value for "Enabled" must be set to true, by setting it up in constuctor.
It was set to "Enabled"= false within the program and saved without that JSON property. On reading from DB it was set to default value and not overriden with false, because there was no such JSON property. 
Very unhandy. 
Probably, there should be (or there is) a NetJSON flag that tells to store all values, even default. In my case disk space doesn't play much role, so I would use that. More of it, IMHO, this option must be set by default to "full-save".

**Comment by rpgmaker** [comment]
The option to not skip default exists. Here https://github.com/rpgmaker/NetJSON/wiki/Quick-Guide .

You need to set skipDefualt to false in the settings object.

Thanks,

**Comment by hhblaze** [comment]
Mystical persecution continues:

**Comment by rpgmaker** [comment]
I will look into it. 

Thanks,

**Comment by rpgmaker** [comment]
It is fixed. I will create a new nuget package once i fix the other two issues. Thanks

**Comment by rpgmaker** [comment]
It is published on nuget and should be available soon.

**Comment by hhblaze** [comment]
Very nice, thank you!
