### ISSUE TITLE
IReadOnlyCollection Support

### ISSUE THREAD

**Issue by mrfrankbell** [rpgmaker/NetJSON#205]
Following on from #121 , it seems that IReadOnlyCollection is not currently supported, throwing an ArgumentNullException on serialisation. Changing from an IReadOnlyCollection to IEnumerable works.

IReadOnlyCollection seems a better fit for immutable objects.

```
[TestMethod]
public void HandlesReadOnlyCollection()
{
	var entity = new Entity { Items = new[] { "One", "Two", "Three" } };
	var serialised = NetJSON.NetJSON.Serialize(entity, Settings);
	var deserialised = NetJSON.NetJSON.Deserialize<Entity>(serialised, Settings);

	Assert.AreEqual(entity.Items.Count(), deserialised.Items.Count());
	foreach (var item in entity.Items)
		Assert.IsTrue(deserialised.Items.Contains(item));
}

public class Entity
{
	public IReadOnlyCollection<string> Items { get; set; }
}
```

**Comment by rpgmaker** [comment]
It is supported now. I will create a new nuget package once i fix the other two issues. Thanks

**Comment by rpgmaker** [comment]
It is published on nuget and should be available soon.

**Comment by mrfrankbell** [comment]
Tested and working, thanks!
