### ISSUE TITLE
IReadOnlyDictionary Support

### ISSUE THREAD

**Issue by mrfrankbell** [rpgmaker/NetJSON#207]
As with #205 , NetJSON doesn't currently support IReadOnlyDictionary, throwing ArgumentNullException on serialisation. 

```
[TestMethod]
public void HandlesReadOnlyDictionary()
{
	var entity = new EntityWithReadOnlyDictionary { Map = new Dictionary<string, string> { { "One", "Eno" }, {"Two", "Owt"}, { "Three", "Eerht"} } };
	var serialised = NetJSON.NetJSON.Serialize(entity, Settings);
	var deserialised = NetJSON.NetJSON.Deserialize<EntityWithReadOnlyDictionary>(serialised, Settings);

	Assert.AreNotSame(entity.Map, deserialised.Map);
	Assert.AreEqual(entity.Map.Count, deserialised.Map.Count);
	foreach (var item in entity.Map)
	{
		Assert.IsTrue(deserialised.Map.ContainsKey(item.Key));
		Assert.AreEqual(item.Value, deserialised.Map[item.Key]);
	}
}

public class EntityWithReadOnlyDictionary
{
	public IReadOnlyDictionary<string, string> Map { get; set; }
}
```

There is also [IReadOnlyList](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.ireadonlylist-1) so perhaps worth adding support at the same time just in case someone else needs this in future.

**Comment by mrfrankbell** [comment]
Apologies, only noticed this as I started to test NetJSON with additional projects. I should have included the additional read-only interfaces in #205.

**Comment by rpgmaker** [comment]
Np, It is actually very easy to support. If you look at the code changes I made for it in regards to the read only collection. Could you make a pull request for it? If not, then I will take a look it when I get a chance. 

Thanks

**Comment by rpgmaker** [comment]
The nuget package should be visible for download soon. Thanks

**Comment by mrfrankbell** [comment]
Working, thanks!

**Comment by rpgmaker** [comment]
Np
