### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by viveklpu2011** [rpgmaker/NetJSON#210]
I am getting an issues while serializing and deserializing

"**Unhandled Exception:
System.TypeInitializationException: The type initializer for 'NetJSONCachedSerializer`1' threw an exception. occurred**"

Please Help

**Comment by rpgmaker** [comment]
Hi, could you give me the specific scenario in which this happened?

Thanks,

**Comment by rpgmaker** [comment]
Any example?
