### ISSUE TITLE
DateTime in ISO format not deserialized

### ISSUE THREAD

**Issue by adoris123** [rpgmaker/NetJSON#211]
Deserialized without problem: "2014-07-31T00:00:00.0000000+02:00"
Error deserializing: "2014-07-31T00:00:00.0000000"

**Comment by rpgmaker** [comment]
Do you mean serialized without problem? Also, can you post the code example of what you are doing if possible? E.x what is your netjson setting look like and etc.

Thanks,

**Comment by rpgmaker** [comment]
Any example would be helpful. Thanks,

**Comment by rpgmaker** [comment]
I will close this for now. Please be sure to reopen it when you have an example to reference. Thanks again
