### ISSUE TITLE
NetJSON cannot serialize model casted to object

### ISSUE THREAD

**Issue by ZOXEXIVO** [rpgmaker/NetJSON#212]
I tried to replace Jil serilizer by NetJSON, but it not worked for simple cases! 
It my second attemp to use it (first was 2-3 years ago).

How you test your serializer? 

I have some JsonExtensions that use some serialization settings. 
I can use many other serializers and it all works well, except NetJSON. It not worked!

How can develop serializer, that fail serialization of simple objects?

//P.S
It serialize array of simple objects as [,,,,,,,]

**Comment by rpgmaker** [comment]
Can you be more specific for the simple object scenario?

**Comment by rpgmaker** [comment]
You can pull down the code. There is 90+ test for it at the moment. Thanks

**Comment by ZOXEXIVO** [comment]
My project simply serialize List<SomeModel> with

```
 private static readonly NetJSONSettings Options = new NetJSONSettings
 {
            CamelCase = true
  };

   public static string ToJson(this object obj)
   {
            return NetJSON.NetJSON.Serialize(obj, Options);
   }

```

```
public class SomeModel
    {
        public MentionModel()
        {
            Related = new RelatedSomeModel();
        }

        public long Id { get; set; }

        public string Title { get; set; }

        public string Text { get; set; }

        public DateTime Date { get; set; }

        public OtherModel3 Mode3 { get; set; }

        public OtherModel Model1 { get; set; }

        public OtherModel2 Model2 { get; set; }

        public double[] Location { get; set; }

        public int SomeCount{ get; set; }

        public string SourceUrl { get; set; }

        public bool IsApproved { get; set; }

        public RelatedSomeModelRelated { get; set; }

        public DateTime? SomeDate{ get; set; }

        public class RelatedSomeModel
        {
            public RelatedSomeModel()
            {
                Players = new List<int>();
                Clubs = new List<int>();
            }

            public List<int> SomeCollection { get; set; }
            public List<int> SomeCollection { get; set; }
        }
    }
```

Result:

![image](https://user-images.githubusercontent.com/14014921/52750698-0b579a80-2ffe-11e9-9586-dcc6f6bd7a1f.png)

**Comment by rpgmaker** [comment]
Thanks for the example.

**Comment by rpgmaker** [comment]
A working example with the failure case will be nice for me to debug the issue and resolve. Thanks

**Comment by ZOXEXIVO** [comment]
It caused only if serialization type passed as object

```
public class MentionModel
    {
        public long Id { get; set; }

        public string Title { get; set; }

        public string Text { get; set; }
    }
    
    class Program
    {
        private static readonly NetJSONSettings Options = new NetJSONSettings
        {
            CamelCase = true
        };

        static async Task Main(string[] args)
        {
            object model = new List<MentionModel>
            {
                new MentionModel
                {
                    Text = "test",
                    Id = 23232,
                    Title = "test",
                },
                new MentionModel
                {
                    Text = "test",
                    Id = 23232,
                    Title = "test",
                  
                }
            };


            var resultStr = NetJSON.NetJSON.Serialize(model, Options);

           //resultStr = "[,]"
        }
    }
```

**Comment by rpgmaker** [comment]
That is normal. It is expected to work. It is by design

**Comment by rpgmaker** [comment]
Object serialization only support primitive type as the wiki describe. It is not Netjson fully broken, if you specific the type via typeof as an additional parameter it will work fine. Please change the title as it does not match what you are describing.😀

Thanks,

**Comment by rpgmaker** [comment]
Would it not be best to manually call .GetType within your code and use the overload that accept system.Type?

Thanks,

**Comment by rpgmaker** [comment]
![image](https://user-images.githubusercontent.com/557807/52929711-86c58e80-3313-11e9-8968-bf3dc5744b2d.png)

**Comment by ZOXEXIVO** [comment]
netcoreapp2.2 console application 
![image](https://user-images.githubusercontent.com/14014921/52938770-91177500-3373-11e9-83c5-e27f8ab0892f.png)

**Comment by rpgmaker** [comment]
You need to use SerializeObject method since that will do the get type of the model for you underlying it. I can push the changes to nuget for you.

**Comment by rpgmaker** [comment]
I have pushed the changes to nuget. So you can now use the SerializeObject method now. It is in 1.2.10.1 version

**Comment by ZOXEXIVO** [comment]
@rpgmaker it works! thank you
