### ISSUE TITLE
mysterious deserialization result for auto property initializer

### ISSUE THREAD

**Issue by cubed-it** [rpgmaker/NetJSON#229]
The following linqpad example...

```
<Query Kind="Program">
  <NuGetReference>NetJSON</NuGetReference>
  <Namespace>NetJSON</Namespace>
</Query>

void Main()
{
	var myObject1 = new SimpleObject1() { ID = 0, Name = "Test", Value = "Value" };
	var json1 = NetJSON.NetJSON.Serialize(myObject1, new NetJSONSettings() {SkipDefaultValue = false});
	json1.Dump();
	var recreatedObject1 = NetJSON.NetJSON.Deserialize<SimpleObject1>(json1);
	recreatedObject1.Dump();

	var myObject2 = new SimpleObject2() { ID = 0, Name = "Test", Value = "Value" };
	var json2 = NetJSON.NetJSON.Serialize(myObject2, new NetJSONSettings() {SkipDefaultValue = false});
	json2.Dump();
	var recreatedObject2 = NetJSON.NetJSON.Deserialize<SimpleObject2>(json2, new NetJSONSettings() {SkipDefaultValue = false});
	recreatedObject2.Dump();

	var myObject3 = new SimpleObject3() { ID = 0, Name = "Test", Value = "Value" };
	var json3 = NetJSON.NetJSON.Serialize(myObject3);
	json3.Dump();
	var recreatedObject3 = NetJSON.NetJSON.Deserialize<SimpleObject3>(json3);
	recreatedObject3.Dump();
}

public class SimpleObject1
{
	public int ID { get; set; }
	public string Name { get; set; }
	public string Value { get; set; }
}

public class SimpleObject2
{
	public int ID { get; set; } = -5;
	public string Name { get; set; }
	public string Value { get; set; }
}

public class SimpleObject3
{
	public SimpleObject3()
	{
		ID = 5;
	}
	
	public int ID { get; set; }
	public string Name { get; set; }
	public string Value { get; set; }
}
```

...produces the following result. SimpleObject2.Id should actually be 0, but the result is -5?

![image](https://user-images.githubusercontent.com/11182260/89640852-bc1bbe80-d8b0-11ea-8ec7-dc3effc98a19.png)

**Comment by wmjordan** [comment]
````C#
public int ID { get; set; } = -5;
````
The above will set the `ID` to -5, once the constructor of `SimpleObject2` is called.

Why did you think it should be 0?

**Comment by wmjordan** [comment]
It is really weird.

**Comment by rpgmaker** [comment]
that is really weird indeed. What version are you using and what .net framework is this?

Thanks,

**Comment by wmjordan** [comment]
I checked the code, if we set the ID to another value, like the following:
````C#
new SimpleObject2() { ID = 1, Name = "Test", Value = "Value" }
````

It was deserialized properly.

It seems that there is something wrong when deserializing default values, since ID=0 happens to be the default value.

The `SkipDefaultValues` should only be used when serializing objects, I suggest. When deserializing, there is no need to check whether the values in the given JSON are _default_ ones.

**Comment by rpgmaker** [comment]
It seem the default value been returned is a random initialize value for int or something.  And I am taking that value and inserting it somehow.  Thanks for suggestions i will look into it

**Comment by wmjordan** [comment]
@rpgmaker 
Look at this place:
https://github.com/rpgmaker/NetJSON/blob/master/NetJSON/NetJSON.cs#L4472

It may be the problem.

It loads the default value of the member and compare it against the deserialized value, if they equal each other, goto `propNullLabel`. Thus the value 0 was not set and the default -5 was remained there.

**Comment by wmjordan** [comment]
I tried to use `GenerateTypesInto` to save the assembly, however, I got this:
System.TypeLoadException: Access is denied: 'NetJSON.NetJSONSerializer`1[ConsoleApp1.SimpleObject2]'.

**Comment by rpgmaker** [comment]
Use GenerateAssembly flag instead

**Comment by wmjordan** [comment]
By analyzing the generated assembly, I confirmed the aforementioned problem was caused by the comparison against the default value of the member type. Why there was such kind of comparison? It seemed to be unnecessary and removable.

**Comment by rpgmaker** [comment]
The comparison is only generated if the skip default is enabled which is by default. What happens if you set it to false?

**Comment by wmjordan** [comment]
It had already been `false` in the posted code.
Before calling the `Deserialize` method, I could verify that value was still `false` in the settings instance.

**Comment by rpgmaker** [comment]
Sorry I missed that 😔.  Will try to change the code to avoid the compare and see what happens.

**Comment by rpgmaker** [comment]
@cubed-it, Will try to work on a solution this weekend. Thanks.

**Comment by cubed-it** [comment]
> @cubed-it, Will try to work on a solution this weekend. Thanks.

hey, i've been following your conversation in silence ;) thanks a lot in advance!

**Comment by rpgmaker** [comment]
Ended up generated the code as the following

![image](https://user-images.githubusercontent.com/557807/90355209-8ab59800-e000-11ea-8d67-38b6cbbf412b.png)

**Comment by rpgmaker** [comment]
@cubed-it, can you pull the latest from master and test your code again? I also added a unit test for your scenario which is passing for me at the moment.

I will push to nuget soon if you rather wait for that.

**Comment by rpgmaker** [comment]
@cubed-it , i just published to nuget a moment ago - https://www.nuget.org/packages/NetJSON/

**Comment by cubed-it** [comment]
my test looks good, thanks for the quick fix!

**Comment by wmjordan** [comment]
> Ended up generated the code as the following
> 
> ![image](https://user-images.githubusercontent.com/557807/90355209-8ab59800-e000-11ea-8d67-38b6cbbf412b.png)

The code logic could be optimized to the following, which may save some comparisons:

````C#
if (P_4.SkipDefaultValue == false || n != 0) {
   P_2.ID = num;
}
````

**Comment by rpgmaker** [comment]
I can flip the condition and check if skip default first on my next code change. Thanks
