### ISSUE TITLE
NetJSONKnownType doesn't work

### ISSUE THREAD

**Issue by thecodrr** [rpgmaker/NetJSON#231]
Okay, I just tried NetJSON and it is not serializing Interface properties properly. Here is my data structure:

```cs
public class User
{
      [DataMember(Name = "appData")]
      public AppData AppData { get; set; }
}
```
```cs
public class AppData
{
     [DataMember(Name = "subscription")]
     public ISubscription Subscription { get; set; }
}
```
```cs
[NetJSON.NetJSONKnownType(typeof(Subscription))]
public interface ISubscription
{
        string OrderId { get; set; }
        string Ref { get; set; }
        bool IsRecurring { get; set; }
        DateTime Expiry { get; set; }
}
```
```cs
public class Subscription : ISubscription
{
        [IgnoreDataMember]
        public string OrderId { get; set; }

        [IgnoreDataMember]
        public string Ref { get; set; }

        [DataMember(Name = "isRecurring")]
        public bool IsRecurring { get; set; }

        [DataMember(Name = "expiry")]
        public DateTime Expiry { get; set; }

        [DataMember(Name = "isTrial")]
        public bool IsTrial { get; set; }
 }
```

Now when I try to serialize the `User` object using:
```cs
var user = new User() { /* initialize appropriately */ };
NetJSON.NetJSON.Serialize(user);
```
It gives me this JSON:
```json
{
   "appData":{
      "subscription":{
         "Expiry":"\/Date(15992888338610000)\/"
      }
   }
}
```
I have overriden `CanSerialize` and `SerializeAs` to respect `DataMember` and `IgnoreDataMember` attributes appropriately.

In the `Subscription` object, `IsTrial = true` and `IsRecurring = false` which is never serialized. I don't know what is the issue here. Also, `Expiry` key should be `expiry`.

Hope you can help.

**Comment by rpgmaker** [comment]
Is this still an issue?

**Comment by rpgmaker** [comment]
I am working on a solution to make this more useful for custom serializer types, so NETJson can be extended easily.

**Comment by rpgmaker** [comment]
So I just verified that the custom serialization actually does work as expected. The problem with the replacement occurs when you try to call NetJSON.Serialize inside the custom serialize which might be causing an issue with the generator.

As shown below, it yield the expected result in both scenario

With custom serializer only and manual building of json.

![image](https://user-images.githubusercontent.com/557807/118592439-cb426d80-b75a-11eb-927e-106b4822bf90.png)

With custom serializer/deserializer and manual building of json

![image](https://user-images.githubusercontent.com/557807/118592626-18264400-b75b-11eb-84bb-bb9936b064e3.png)

![image](https://user-images.githubusercontent.com/557807/118592675-31c78b80-b75b-11eb-919d-717e91eb4086.png)

**Comment by rpgmaker** [comment]
@thecodrr , Let me know if the above makes sense to you.

**Comment by rpgmaker** [comment]
Closing issue. Reopen if still needed @thecodrr
