### ISSUE TITLE
Time for .Net 5 Release

### ISSUE THREAD

**Issue by hhblaze** [rpgmaker/NetJSON#234]
Hi, it is time to put into Nuget a version with [ .Net 5](https://devblogs.microsoft.com/dotnet/announcing-net-5-0/?ocid=AID3017126) support. Otherwise many dependencies must be downloaded extra with the newest project type.

**Comment by hhblaze** [comment]
[NetJSON.zip](https://github.com/rpgmaker/NetJSON/files/5567202/NetJSON.zip)
Probably it can look like that (added preprocessor directives NET5_0) and created NetJSON.Net5_0 project. 
VS19 16.8.1 is needed for .NET 5

**Comment by rpgmaker** [comment]
Thanks.  Will make the changes

**Comment by hhblaze** [comment]
Made a small fix (after that my code runs good). All places must be rechecked like 
#if NET_STANDARD_20 || NET5_0

#if NET_STANDARD
#if NET_STANDARD_20 || NET5_0

etc.

[NetJSON.zip](https://github.com/rpgmaker/NetJSON/files/5567326/NetJSON.zip)

**Comment by rpgmaker** [comment]
Thanks for the help.  Will take a look at it once I get a chance

**Comment by rpgmaker** [comment]
Please test again. I also went ahead and added the symbol for easy debugging of the nuget packages. Thanks again for contributing the changes.

**Comment by hhblaze** [comment]
This adventure is not finished yet:

1.3.6 throws mistake (with my compilation it works) by reading such json string:
```js
{"All":{"ym":"ss"},"ervicesAuto":{"ym":"ss"},"ocessor":{"":"ss"},"sonalDevice":{"":"ss"},"rryCan":{"":"ss"},"licom":{"ymr":"ss"}}
```
```C#
var mydict= NetJSON.NetJSON.Deserialize<Dictionary<string, Dictionary<string, string>>>(...thatJsonString...);
```
```
System.TypeInitializationException: The type initializer for 'NetJSONCachedSerializer`1' threw an exception. ---> System.TypeLoadException: Access is denied: 'NetJSON.NetJSONSerializer`1[System.Collections.Generic.Dictionary`2[System.String,System.Collections.Generic.Dictionary`2[System.String,System.String]]]'. at System.Reflection.Emit.TypeBuilder.CreateTypeNoLock() at System.Reflection.Emit.TypeBuilder.CreateType() at NetJSON.NetJSON.Generate(Type objType) at NetJSON.NetJSON.NetJSONCachedSerializer`1.GetSerializer() at NetJSON.NetJSON.NetJSONCachedSerializer`1..cctor() --- End of inner exception stack trace --- at NetJSON.NetJSON.GetSerializer[T]() at NetJSON.NetJSON.Deserialize[T](String json) at
```

**Comment by rpgmaker** [comment]
I guess I need some unit test specifically for .net 5.0

**Comment by rpgmaker** [comment]
Your compilation works where?

**Comment by hhblaze** [comment]
I would say that it works exactly like .NET standard... but preprocessor  directives "#if NET_STANDARD_20 || NET5_0" sometimes tricky.

**Comment by hhblaze** [comment]
From the latest NetJson.zip I published here, I have changed mostly those twofiles for adding NET5_0 directive:

![image](https://user-images.githubusercontent.com/486781/100071216-1712fa80-2e3b-11eb-8cf7-49dbcaec1020.png)

**Comment by rpgmaker** [comment]
I added the constant and applied it for any net standard 2.0 code since they are similar

**Comment by rpgmaker** [comment]
Can you create a pull request instead based on the previous code before my change and I can see what I missed. 

Thanks

**Comment by hhblaze** [comment]
Yeap, you got a pull request

**Comment by rpgmaker** [comment]
Thanks. Will close this issue out and use the pull request for questions

**Comment by rpgmaker** [comment]
@hhblaze, Thanks i have updated the code and pushed another version.
