### ISSUE TITLE
Ignore object properties

### ISSUE THREAD

**Issue by isabr85** [rpgmaker/NetJSON#235]
How can I ignore object properties in serialization action?
Is that possible?

**Comment by rpgmaker** [comment]
Have you looked into using the following if you want your own custom logic.

https://github.com/rpgmaker/NetJSON/wiki/Quick-Guide

NetJSON.CanSerialize
            - Allow specifying a custom delegate to implement custom attribute and other features to allow additional functionality such as Ignoring fields/properties, and etc

https://github.com/rpgmaker/NetJSON/blob/master/NetJSON.Tests/SerializeTests.cs#L1405

https://github.com/rpgmaker/NetJSON/blob/master/NetJSON.Tests/SerializeTests.cs#L2196-L2204

**Comment by rpgmaker** [comment]
The answer is in the link I gave above.
