### ISSUE TITLE
has exited with code -1073741819 (0xc0000005) 'Access violation'

### ISSUE THREAD

**Issue by mergoktas** [rpgmaker/NetJSON#37]
.
'WindowsFormsApplication4.vshost.exe' (CLR v4.0.30319: WindowsFormsApplication4.vshost.exe): Loaded 'c:\users\pc\documents\visual studio 2013\Projects\WindowsFormsApplication4\WindowsFormsApplication4\bin\Debug\WindowsFormsApplication4.exe'. Symbols loaded.
'WindowsFormsApplication4.vshost.exe' (CLR v4.0.30319: WindowsFormsApplication4.vshost.exe): Loaded 'c:\users\pc\documents\visual studio 2013\Projects\WindowsFormsApplication4\WindowsFormsApplication4\bin\Debug\NetJSON.dll'. Symbols loaded.
'WindowsFormsApplication4.vshost.exe' (CLR v4.0.30319: WindowsFormsApplication4.vshost.exe): Loaded 'MyHouseClass'. 
A first chance exception of type 'System.Reflection.AmbiguousMatchException' occurred in mscorlib.dll
A first chance exception of type 'System.TypeInitializationException' occurred in NetJSON.dll
'WindowsFormsApplication4.vshost.exe' (CLR v4.0.30319: WindowsFormsApplication4.vshost.exe): Loaded 'C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The program '[5656] WindowsFormsApplication4.vshost.exe' has exited with code -1073741819 (0xc0000005) 'Access violation'.

**Comment by rpgmaker** [comment]
Can you give an example of how to reproduce this error? Such as a class definition and what the content is.

Thanks,

**Comment by mergoktas** [comment]
I tried the debug and the release configurations but the result were unsuccessful for both.I just created simple winform project with vs2013 pro, install NETJSON with nuget manager.On form load method, I tried to run the samples that are in the attached file.Even I created a new project from scratch and downloaded the package from github and made a reference to it, but result were same.
This is extra : I need to serialize my objects and send with MSMQ. So at the receiving side I should know which object arrived. Any suggestion?
Please see the attached c# file
Thanks,
Muharrem
 

     On Friday, January 16, 2015 7:30 PM, Rpgmaker <notifications@github.com> wrote:
   

 Can you give an example of how to reproduce this error? Such as a class definition and what the content is.Thanks,—
Reply to this email directly or view it on GitHub.   
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Runtime.Serialization.Formatters.Binary;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Xml.Serialization;
using NetJSON;
	
	//1. Trial, vs2013 pro, win7 home pre
    [Serializable]
    public class MyJsonBase
    {
        public Type MyType { get; set; }
        public string Value { get; set; }
        public string TargetTask { get; set; }
        public string SourceTask { get; set; }
        public int Evt = 9;
        public MyEnum MyEnum { get; set; }
    }
    [Serializable]
    public class MyHouse : MyJsonBase
    {
        public string Street { get; set; }
        public string ZipCode { get; set; }
        public int Number { get; set; }
        public int Id { get; set; }
        public string Town { get; set; }
        public int Rent { get; set; }
        public int X1 { get; set; }
        public int X2 { get; set; }
        public int X3 { get; set; }
        public int X4 { get; set; }

        public MyHouse()
        {
            MyType = this.GetType(); 
        }
    }

    public class NetJSONMessage
    {
        public Type Type { get; set; }
        public string Value { get; set; }
        public string TargetTask { get; set; }
        public string SourceTask { get; set; }
        public int Evt = 9;
        public MyEnum MyEnum { get; set; }

        public NetJSONMessage()
        {

        }
        public static NetJSONMessage FromValue<T>(T value)
        {
            return new NetJSONMessage { Type = typeof(T), Value = NetJSON.NetJSON.Serialize(value) };
        }

        public static NetJSONMessage FromValue<T>(T value, string sourceTask, string targetTask)
        {
            return new NetJSONMessage { Type = typeof(T), Value = NetJSON.NetJSON.Serialize(value), SourceTask = sourceTask, TargetTask = targetTask };
        }

        public static string Serialize(NetJSONMessage message)
        {
            return NetJSON.NetJSON.Serialize<NetJSONMessage>(message);
        }

        public static NetJSONMessage Deserialize(string data)
        {
            return NetJSON.NetJSON.Deserialize <NetJSONMessage>(data);
        }
    }
	
	// Then try to following
			var json = NetJSON.NetJSON.Serialize(newHouse); //this line throws the exception
            var obj = NetJSON.NetJSON.Deserialize<House>(json);

            var j1 = NetJSONMessage.FromValue(newHouse);	//this line seems to be fine
            //var data4 = NetJSONMessage.Serialize(j1);		// this does't, so I commented out
            
		//Second trial with new created project
		
    public enum MyEnum
    {
        Open,
        Close,
        Read,
        Write
    }

    //Putting the [Serializable] attrib did not make any difference for my classes
    public class MyJsonBase
    {
        public Type MyType { get; set; }
        public string Value { get; set; }
        public string TargetTask { get; set; }
        public string SourceTask { get; set; }
        //public int Evt = 9;
        //public MyEnum MyEnum { get; set; }

        public MyJsonBase()
        {

        }
    }

    public class MyHouse : MyJsonBase
    {
        public string Street { get; set; }
        public string ZipCode { get; set; }
        public int Number { get; set; }
        public int Id { get; set; }
        public string Town { get; set; }
        public int Rent { get; set; }
        public int X1 { get; set; }
        public int X2 { get; set; }
        public int X3 { get; set; }
        public int X4 { get; set; }

        public MyHouse()
        {
            MyType = this.GetType();
        }
    }
	
            var newHouse = new MyHouse
            {
                Street = "Mill Lane",
                ZipCode = "LO1 BT5",
                Number = 11,
                Id = 1,
                Town = "London",
                Rent = 45678,
                X1 = 123456,
                X2 = 87654,
                X3 = 4364432,
                X4 = 56434
            };
			
            //newHouse.Evt = 90;
            newHouse.SourceTask = "xxx";
            newHouse.TargetTask = "yyy";
            //newHouse.MyEnum = MyEnum.Close;

           
            var json = NetJSON.NetJSON.Serialize(newHouse); //this line throws the exception
            textBox1.Text = json;

            var obj = NetJSON.NetJSON.Deserialize<MyHouse>(json);

**Comment by rpgmaker** [comment]
Without any test from my side. I think if you remove Type property from your classes it will work. My serializer does not work  on Type Type out of the  box to my knowledge. Let me if that fixes it

**Comment by rpgmaker** [comment]
Btw, if you want include the field members of your  classes for serialization you need to do NetJSON.IncludeFields = true

**Comment by rpgmaker** [comment]
Netjson  does not use Serialiable to determine whether to serialize or not

**Comment by mergoktas** [comment]
OK.Without Type type property, it works.Are you planing to include this too?When?
Otherwise how to determine the type of the object at deserialization time?Or if I need to transfer the object type too?
Thanks
 

     On Saturday, January 17, 2015 7:50 PM, Rpgmaker <notifications@github.com> wrote:
   

 Without any test from my side. I think if you remove Type property from your classes it will work. My serializer does not work on Type Type out of the box to my knowledge. Let me if that fixes it—

**Comment by rpgmaker** [comment]
You can send the Type.FullName as a string and use that with Type.GetType method to retrieve it

**Comment by rpgmaker** [comment]
http://stackoverflow.com/a/11107562

**Comment by mergoktas** [comment]
OK.
I already include the type name in my container class.
But I have another question.Why you omit the properties in serialized string if their values are omitted or not assigned?Will it be a problem or not? 

     On Sunday, January 18, 2015 5:55 PM, Rpgmaker <notifications@github.com> wrote:
   

 http://stackoverflow.com/a/11107562—

**Comment by rpgmaker** [comment]
It will not be a problem to omit them because  it is  just the default values. Excluding them is for performance  and size improvement. Internal there is a flag that I can expose to allow it always write default values

**Comment by rpgmaker** [comment]
The flag is called SkipDefaultValue and it is true by default. If you want to include default set it to false. It is not a huge perf hit when enable
