### ISSUE TITLE
How to change the format where dates are serialized?

### ISSUE THREAD

**Issue by nohros** [rpgmaker/NetJSON#39]
More specific, how can I serialize dates using the unix epoch format?

**Comment by rpgmaker** [comment]
Do you mean serializing it with January 1 1970 as the starting  point.

**Comment by nohros** [comment]
Yes, the number of seconds that have elapsed since January 1 1970.

**Comment by rpgmaker** [comment]
So you want it to print just the timestamp not the date format with month day

**Comment by nohros** [comment]
No, but I want the date to be a single long value on the wire and deal with format on the client side.

**Comment by rpgmaker** [comment]
Got it. Thanks

**Comment by rpgmaker** [comment]
I will add a flag to handle date just like IsoFormat

**Comment by rpgmaker** [comment]
I added a new property to NetJSON.DateFormat = NetJSONDateFormat.EpochTime
