### ISSUE TITLE
Error Serializing Properties With Private Setter

### ISSUE THREAD

**Issue by IronGeek** [rpgmaker/NetJSON#40]
The following class serialized properly with NetJSON:
````csharp
public class TestClass
{
  private string testProperty = "Test";

  public string TestProperty
  {
    get { return testProperty; }      
  }
}
````
These ones however throw error upon serialization:
> _System.TypeInitializationException : The type initializer for 'NetJSONCachedSerializer`1' threw an exception._
> _----> System.ArgumentNullException : Value cannot be null._
> _Parameter name: meth_

````csharp
public class TestClass
{
  private string testProperty = "Test";

  public string TestProperty
  {
    get { return testProperty; }      
    private set { testProperty = value; }
  }
}

public class TestClass
{
    public TestClass()
    {
      TestProperty = "Test";
    }
    public string TestProperty { get; private set; }
}
````
I believe you need to add `null` validation in [NetJSON.cs](https://github.com/rpgmaker/NetJSON/blob/master/NetJSON/NetJSON.cs#L2865-L2866):
````csharp
if (prop.CanWrite && prop.GetSetMethod() != null)
````
or use the other overload of [`PropertyInfo.GetSetMethod`](https://msdn.microsoft.com/en-us/library/scfx0019.aspx) that returns non-public setter
````chsharp
il.Emit(isTypeValueType ? OpCodes.Call : OpCodes.Callvirt, prop.GetSetMethod(true));
````

Note: I'm using the latest version Github.

**Comment by rpgmaker** [comment]
Thanks for the find. This is similar to this issue: https://github.com/rpgmaker/NetJSON/issues/10 . At this time NetJSON does not support serializing non-public properties because of the use of dynamic assemblies rather than Dynamic methods. I plan to update NetJSON to use dynamic methods just for non-public classes/properties in the future.

**Comment by IronGeek** [comment]
Thank you for the quick reply.

I understand your reasoning for not supporting serialization of non-public properties. However, being lazy as I am, I tend to write my `DTO` with automatic properties such as:
````csharp
public class TestClass
{    
    public string TestProperty { get; private set; }
}
````
Notice that the `TestProperty` is `public` but its setter is `private`. With the recent commit you made in dc1e839dbfd76cc57b7acb8b9b02251f2da5b6da, my initial expectation was that the above class will be treated the same way as _a public property **without** setter_.

**Comment by rpgmaker** [comment]
I see now, then it is a bug. I will look into it and get back to you.

**Comment by rpgmaker** [comment]
Until the fix is in to properly handle non-public members/classes the solution is not idea since deserialization will always give you a null string value since setter will never be called.

**Comment by IronGeek** [comment]
Fair enough. 
My issue here is for serialization, so it seems I've overlooked the deserialization part.

**Comment by rpgmaker** [comment]
Closing this issue since it is related to this issue: https://github.com/rpgmaker/NetJSON/issues/10
