### ISSUE TITLE
Tests & Experiments

### ISSUE THREAD

**Issue by grigorey** [rpgmaker/NetJSON#41]
Hi, I'll post my findings here :) By the way try run tests against http://fastjson.codeplex.com I will use it in my test :)

**Comment by rpgmaker** [comment]
I follow this test. https://github.com/amacal/Quality.Json

**Comment by grigorey** [comment]
Sweet, thanks for the link!

**Comment by rpgmaker** [comment]
If you can help in making suggestions to improve performance overall to
make netjson faster than or as fast as binaries that would be great.
Netjson is already faster than all json (based on all the benchmark online)
that I have seen and tested and also beat messageshark and protobuf on some
use cases.

**Comment by rpgmaker** [comment]
Closing this issue. Open a new issue when there are any changes to be made to netjson. Thanks

**Comment by grigorey** [comment]
Cool!
