### ISSUE TITLE
Add 3.5 .NET Target

### ISSUE THREAD

**Issue by Givemeyourgits** [rpgmaker/NetJSON#42]
Is it possible to add a 3.5 .NET target?

I want to test this with Unity, but it can only use .net dll's version 3.5 or lower.

**Comment by rpgmaker** [comment]
have you try to download the source to see if it compiled under 3.5?

**Comment by Givemeyourgits** [comment]
I tried, but it says it Microsoft.CSHARP is for version 4 (which I believe is only used in 4+) I tried removing it and it wouldn't compile.  I tried to find a replacement for 3.5 and I couldn't find one.

**Comment by rpgmaker** [comment]
It will not compile except you add a  #IF DEFINE macro checks for 3.5 so it does not add the code for expando object

**Comment by Givemeyourgits** [comment]
How would I do that?
Is there only one section where the expando object is?

**Comment by rpgmaker** [comment]
You can do the if define on line 98. And that should help  with removing the dependency

**Comment by Givemeyourgits** [comment]
Is there a reference I need to add to replace Microsoft.CSHARP?
Without it, I get a lot of missing namespace messages.

**Comment by rpgmaker** [comment]
You should also wrap the using statement in a if define.

**Comment by Givemeyourgits** [comment]
Those are needed though right?  There was a lot of them that errored out.

Tasks
Concurrent
Threading
Dynamic
Security

Seems like I would need something to replace the CSHARP reference that works in 3.5.

**Comment by rpgmaker** [comment]
Since there is a lot to change. I will say you hold off on all your change and let me look into it and get back to you

**Comment by Givemeyourgits** [comment]
Thanks!

**Comment by Givemeyourgits** [comment]
Mad props, thanks!

**Comment by rpgmaker** [comment]
You are welcome. :)
