### ISSUE TITLE
Properties of type object are ignored

### ISSUE THREAD

**Issue by hudo** [rpgmaker/NetJSON#44]
If I serialize SomeDTO, it works fine. But if I have a wrapper class with property of type object, like:

    public class SomeWrapper { public object Payload { get; set; } };
    var wrapper = new SomeWrapper { Payload = new SomeDto { ... } }; 

then Payload is empty in serialized json string. Is that by design and limitation of this lib, or something else?

**Comment by rpgmaker** [comment]
When you use object it is limited to just primitive types only for now. Because it is easier to detect for deserialization. Support for serialization of non primitive can be done, it will not just be deserializable without knowing the type.

**Comment by rpgmaker** [comment]
Best you can do is create payload as string and also write the type name in another property as string. And when you need the object back. You can use Type.GetType and then use the deserialize method that uses Type as a parameter  to deserialize your payload
