### ISSUE TITLE
Issue trying to serialize Booleans

### ISSUE THREAD

**Issue by neerajks** [rpgmaker/NetJSON#45]
var json = "{ \"BoolValue\": false, \"StringValue\": \"Neeraj\" }";
var res = NetJSON.NetJSON.Deserialize(typeof(CompositeType), json);

res here has the BoolValue property set to true.

The serialization to Bool also fails if the bool value is put under qoutes. 

While JSON.Net from Newtonsoft.Json does it correctly
var res1 = JsonConvert.DeserializeObject(json);

**Comment by rpgmaker** [comment]
I just tried it using

    public class TestBool {
        public bool BoolValue { get; set; }
        public string StringValue { get; set; }
    }

            var json = "{ \"BoolValue\": false, \"StringValue\": \"Neeraj\" }";
            var res = NetJSON.NetJSON.Deserialize(typeof(TestBool), json);

And it works fine it gives me false value as expect instead of true. The reason why boolean fails with quote is because the boolean values are not string literals based on the JSON specs.

Here is a screenshot: http://postimg.org/image/jj598vuzp/

**Comment by neerajks** [comment]
Thanks for a prompt reply. 
Could you please try the same code with this model implementation.

[DataContract]
    public class CompositeType
    {
        private bool boolValue = true;
        private string stringValue = "Hello ";

        [DataMember]
        public bool BoolValue
        {
            get { return boolValue; }
            set { boolValue = value; }
        }

        [DataMember]
        public string StringValue
        {
            get { return stringValue; }
            set { stringValue = value; }
        }
    }   

Thanks again for looking at this promptly.

**Comment by neerajks** [comment]
OK I did some more experiments it seems the Deserialize fails when there are default values in the class. Once I removed the default values in the private members it worked as expected.

**Comment by rpgmaker** [comment]
The reason why it is default to true is because you defined your private member as true. And when NetJSON see that you are deserializing a default value, it does not bother setting it for optimization reason but because you have predefined as true, you ended up with true for the final result.

**Comment by rpgmaker** [comment]
You can turn off the function of skipping default value if you want. I would not advise it.

NetJSON.SkipDefaultValue = false;

**Comment by neerajks** [comment]
But inspite of the default value the false coming from the jsonstring should have come accross as false. Correct?

**Comment by rpgmaker** [comment]
No, it would not come back as false since you predefined as true in your class definition. It will only do so by doing what you did which is removing the default value been set to true

**Comment by neerajks** [comment]
You said you advise against turning off the Default value. Is that for speed concerns?

**Comment by rpgmaker** [comment]
It is a performance things, but again it depends on your scenario not skipping default for basic classes are usually fine as long as it is done moderately where you are deserializing/serializing a few times not thousands of iterations

**Comment by neerajks** [comment]
Thankyou for your prompt support.
