### ISSUE TITLE
Deserialization fails (or is incorrect) for classes which contain Nullable<> or ?

### ISSUE THREAD

**Issue by Villenny** [rpgmaker/NetJSON#46]
public class TestMe
        {
            public string a { get; set; }
            public string b { get; set; }
            public int? c { get; set; }
            public int? d { get; set; }
        }

                    var testMe = new TestMe
                    {
                        a = "Test",
                        c = 0
                    };
                    if (useNetJSON == true)
                    {
                        vals[j] = NetJSON.NetJSON.Serialize(testMe);
                        var obj = NetJSON.NetJSON.Deserialize(typeof(TestMe), vals[j]);
                        testMe = (TestMe)obj;
                    }

afterwards in the new testMe object c will be null rather than 0.

**Comment by rpgmaker** [comment]
It is not really a bug. It does that because the default value of int is
zero. And since NetJSON.SkipDefault is set to true it will not set the
value because zero is considered the default. The fix is either set the
flag to false or I can simple ignore the flag for nullable types.

**Comment by Villenny** [comment]
I would consider it a bug myself.

The default for int is 0
the default for int? (ie Nullable<int>) is null. (In fact the default of
Nullable<T> is always null)

hence the problem, you must stream Nullable<int> if its non default (ie non
null). Once you do everything should work properly.

thanks.
Ryan

**Comment by rpgmaker** [comment]
Yep you are correct it is a bug that needs to be fixed.

Thanks,
