### ISSUE TITLE
Nullable types are not being deserialized correctly when set to 0

### ISSUE THREAD

**Issue by cuethenoise** [rpgmaker/NetJSON#47]
If I have a class:

public class TestME
{
    public int? Test { get; set; }
}

and I set Test = 0 the class will serialize correctly, but when it deserializes the value will be null instead of 0. This occurs with decimals as well.

**Comment by rpgmaker** [comment]
Thanks. I will look into it and get back to you soon

**Comment by cuethenoise** [comment]
Thanks!

**Comment by rpgmaker** [comment]
Can you please confirm that it works now?

Thanks,

**Comment by cuethenoise** [comment]
Looks great! Works with bool?, int? and decimal? and string. Thanks again!
