### ISSUE TITLE
Control over assembly generated types are created in

### ISSUE THREAD

**Issue by tanglebones** [rpgmaker/NetJSON#50]
Currently: each type generates a deserializer/serializer type into a different assembly.

Feature Request: allow the specification of an assembly name and set of types to generate into it ahead-of-time. Something like: void NetJSON.NetJSON.GenerateTypesInto(string assemblyName, type[] types); that call be called during static initialization.

Why: This lets the author of the types being serialized add InternalsVisibleTo directives to their assembly's properties.cs so the generated serialization code can access those types without them needing to be marked as public.

**Comment by rpgmaker** [comment]
Thanks. Will look into implementing it soon.
