### ISSUE TITLE
Issue with serialization depth?

### ISSUE THREAD

**Issue by VictorySquareAdmin** [rpgmaker/NetJSON#53]
Hello, I am trying to deserialize an object from the [Facebook Graph API](https://developers.facebook.com/docs/graph-api/reference/user);
``GET https://graph.facebook.com/v2.3/12345678912345678/friends?fields=name,installed,picture``
```JSON
{
   "data":[
      {
         "name":"Firstname Lastname",
         "installed":true,
         "id":"12345678912345678",
         "picture":{
            "data":{
               "is_silhouette":false,
               "url":"https://fbcdn-profile.net/user_image_resource.jpg"
            }
         }
      }
   ],
   "paging":{
      "next":"https://graph.facebook.com/v2.3/12345678912345678/friends?fields=name,installed,picture"
   },
   "summary":{
      "total_count":100
   }
}
```

Here is the target class;

```CSharp
public class FacebookFriendsQueryResponse
{
	public class ResponseData
	{
		public class PictureResponse
		{
			public class ResponseData
			{
				public bool is_silhouette { get; set; }
				public string url { get; set; }
			}

			public ResponseData data { get; set; }
		}

		public long id { get; set; }
		public string name { get; set; }
		public bool installed { get; set; }
		public PictureResponse picture { get; set; }
	}
	
	public class PagingData
	{
		public string next { get; set; }
	}
	
	public class SummaryData
	{
		public int total_count { get; set; }
	}

	public ResponseData[] data { get; set; }
	public PagingData paging { get; set; }
	public SummaryData summary { get; set; }
}
```

The top-level objects (ResponseData, PagingData & SummaryData) deserialize just fine, anything nested below that level does not deserialize & remains null. Thus the picture's url property cannot be retrieved!

```CSharp
myQueryResp.data;            	// Valid array
myQueryResp.data[x].name; 		// Expected value
myQueryResp.data[x].picture; 	// !!! Null Object !!!
myQueryResp.paging; 			// Expected value
myQueryResp.summary; 			// Expected value
```

**Comment by rpgmaker** [comment]
Have you tried making the class structure flat and see if the deserialization works?

**Comment by rpgmaker** [comment]
I see the issue now. You have two class with the exact name. In the code, I generate class with the name and most likely did not use fully qualified name properly some where. Try to rename the two Response Dara with different name as see if it still does not work.

Thanks,

**Comment by VictorySquareAdmin** [comment]
Making all the class names unique didn't fix the problem.

I did find the problem, it reveals some strange behavior.

In each of the following test cases, I'm using the original class I posted above as the target. In each of the cases, the position of the `id` field (in the outermost `data` block) relative to the other fields is changed.

----
Test case: JSON returned by facebook (`id` in third position)
```json
"name":"Firstname Lastname",
"installed":true,
"id":"12345678912345678",
"picture":{
	"data":{
		"is_silhouette":false,
		"url":"https://fbcdn-profile.net/user_image_resource.jpg"
	}
}
```
```CSharp
myQueryResp.data[0].id;             // Error: 4570200862833008382
myQueryResp.data[0].name;           // OK
myQueryResp.data[0].installed;      // OK
myQueryResp.data[0].picture;        // Error: Null
myQueryResp.data[0].picture.url;    // Error: Empty
```
----
Test case: `id` in second position
```json
"name":"Firstname Lastname",
"id":"12345678912345678",
"installed":true,
"picture":{
	"data":{
		"url":"https://fbcdn-profile.net/user_image_resource.jpg"
	}
}
```
```CSharp
myQueryResp.data[0].id;             // Error: 4570200862833008382
myQueryResp.data[0].name;           // OK
myQueryResp.data[0].installed;      // Error: False
myQueryResp.data[0].picture;        // OK
myQueryResp.data[0].picture.url;    // OK
```

---
Test case: `id` in first position
```json
"id":"12345678912345678"
"name":"Firstname Lastname",
"installed":true,
"picture":{
	"data":{
		"url":"https://fbcdn-profile.net/user_image_resource.jpg"
	}
}
```
```CSharp
myQueryResp.data[0].id;             // Error: 4570200862833008382
myQueryResp.data[0].name;           // Error: Empty
myQueryResp.data[0].installed;      // Error: False
myQueryResp.data[0].picture;        // OK
myQueryResp.data[0].picture.url;    // OK
```
---

The fact that `id` is wrong in each case lead me to look at it more closely. In the JSON, `id` is given as a quote-wrapped string (``"id":"12345678912345678"``), on a hunch I tried each test case again except with the `id` field unquoted: ``"id":12345678912345678``, **deserialization succeeded in all cases**

I looked back at the target class and found that the `id` field is of type `long`:

```CSharp
public long id { get; set; }
```

If the `id` field in the target class is changed to type `string` **deserialization succeeds** using the original JSON provided by Facebook.

**So to summarize:** If the **target class field type** of `id` is `long` but the **JSON object field** is given as a quoted string, serialization **silently fails** and may affect 'adjacent' fields. The solution was to make sure that **all quote-wrapped JSON fields are represented as strings in the target class**. The long-term solution would be to make sure that the deserialization failure on the `id` field is not silent.

---

**Final Solution**

JSON returned by facebook API:
```Json
{
   "data":[
      {
         "name":"Firstname Lastname",
         "installed":true,
         "id":"12345678912345678",
         "picture":{
            "data":{
               "is_silhouette":false,
               "url":"https://fbcdn-profile.net/user_image_resource.jpg"
            }
         }
      }
   ],
   "paging":{
      "next":"https://graph.facebook.com/v2.3/12345678912345678/friends?fields=name,installed,picture"
   },
   "summary":{
      "total_count":100
   }
}
```

Target class:
```CSharp
public class FacebookFriendsQueryResponse
{
    public class ResponseData
    {
        public class PictureResponse
        {
            public class ResponseData
            {
                public bool is_silhouette { get; set; }
                public string url { get; set; }
            }

            public ResponseData data { get; set; }
        }

        public string id { get; set; } // Previously a `long`
        public string name { get; set; }
        public bool installed { get; set; }
        public PictureResponse picture { get; set; }
    }

    public class PagingData
    {
        public string next { get; set; }
    }

    public class SummaryData
    {
        public int total_count { get; set; }
    }

    public ResponseData[] data { get; set; }
    public PagingData paging { get; set; }
    public SummaryData summary { get; set; }
}
```

Result
```CSharp
myQueryResp.data[0].id;             // OK
myQueryResp.data[0].name;           // OK
myQueryResp.data[0].installed;      // OK
myQueryResp.data[0].picture;        // OK
myQueryResp.data[0].picture.url;    // OK
```

**Comment by rpgmaker** [comment]
Good find. Thanks for the details. Basically the real issue is data type validation. I had some previous fixes that check for invalid json in term of having non matching quote. I will extend it to validate that the data been process match what is created. I will close this issue and create a new issue for data type validation.
