### ISSUE TITLE
Can't make NetJSON v 1.0.7.0 working

### ISSUE THREAD

**Issue by hhblaze** [rpgmaker/NetJSON#60]
Got from NuGet v 1.0.7.0

muj1 is instantiated object, actually I have some working lines before NetJSON call

//working lines
string jsonx = JsonConvert.SerializeObject(muj1);
string ssx = ServiceStack.Text.JsonSerializer.SerializeToString(muj1);
//this one gives mistake
string njs = NetJSON.NetJSON.Serialize(muj1);

Error is System.Typ​eInitializ​ationExcep​tion   "NetJSONCachedSerializer`1"
in German:
Der Typeninitialisierer für "NetJSONCachedSerializer`1" hat eine Ausnahme verursacht.

**Comment by rpgmaker** [comment]
Does an older version work and if so which version? And is it possible to post the structure of the object you are trying to serialize? 

Thanks,

**Comment by hhblaze** [comment]
I don't have older version.

object structure is 

public class MccUserData
        {
            public MccUserData()
            {    
            }

         
            public int ifjhklfdfjlkdjfldgfdgdgdfgdgdgdf = 0;

            public enum eTestE
            {
                One = 1,
                Two = 2,
                Three = 1,
            }

            public eTestE TestEnum { get; set; }

            public TType1 tt1 { get; set; }

            public long CustomerId { get; set; }

            public long HostId { get; set; }

            public string Login { get; set; }

            public bool Active { get; set; }

            public DateTime DtuCreated { get; set; }

            public DateTime ExpirationDate { get; set; }
            public DateTime? ExpirationDate1 { get; set; }

            public bool LoggingPermission { get; set; }


            public string Language { get; set; }

            public int CultureId { get; set; }

            public bool IsAppSubscriber { get; set; }

            public byte[] RowKey { get; set; }

            public HashSet<string> SubscribedApps { get; set; }


            public string CompanyBindingId { get; set; }

            public bool IDT_Enabled { get; set; }

            public DateTime IDT_ExpirationDate { get; set; }

            public bool IDT_PlayStore { get; set; }

            public float FloaTest { get; set; }
            public double DoubleTest { get; set; }
            public decimal DecimalTest { get; set; }
            public double DoubleNullTest { get; set; }
            public char CharTest { get; set; }

            public Dictionary<int, string> rD { get; set; }

            public Dictionary<int, TType1> rObj { get; set; }

            public int?[] arr { get; set; }

            public List<string> sdt { get; set; }

            public string TestString { get; set; }

            public sbyte TestByte { get; set; }

            public TimeSpan TestTimeSpan { get; set; }

            public Guid TestGuid { get; set; }

            public int[][] arr1 { get; set; }
        }

**Comment by rpgmaker** [comment]
Thanks, what is TType? Is it of type System.Type? If so then it will fail.

**Comment by hhblaze** [comment]
public class TType1
        {
            public long P1 = 12;
            public float P2 = 4.5f;
            public int? P4 = null;
        }

**Comment by rpgmaker** [comment]
If you want fields to be serialized. You need to enable NetJSON.IncludeFields = true. But I will look into the error and get back to you.

Thanks,

**Comment by hhblaze** [comment]
Thank you!

**Comment by hhblaze** [comment]
In total - very cool job :+1: ! 
Would be nice to have the same core, but implementing Protobuf concept for the payload size/compatibility and byte[] output.

Also, Tuples data type support is missing/needed.

**Comment by rpgmaker** [comment]
The current does not support deserializing array of nullable type such as int?[]. I have logic to do so at the moment, but it throw FatalEngineExecution exception. So i am still testing.

Let me know if you find any other issue.

As for Tuple support, please create a new issue for that.

Thanks,
