### ISSUE TITLE
System.TypeInitializationException when Deserializing (NetJSON 1.0.7.0, NET 3.5)  

### ISSUE THREAD

**Issue by marksimpson82** [rpgmaker/NetJSON#64]
Hi,

I've been using Json.NET for ages, but some optimization work led me to NetJSON. I can successfully install & use NetJSON via NuGet using a project targeting .NET 4.5 and performance has increased to the point where the json parsing has all but disappeared -- awesome.

Unfortunately, the project I'm working on targets .NET 3.5. When I install the appropriate version of NetJSON, an exception is thrown when deserializing even the simplest of examples. 

.NET 4.5 + NetJSON 1.0.7.0 = all good
.NET 3.5 + NetJSON 1.0.7.0 = problem

I double-checked to make sure there wasn't some stale nuget assembly kicking around, too. It looks legit:

Any help would be appreciated, and thanks for writing the library :+1: 

```javascript
{ "SomeString": "51113120021011" } 
```
```c#
public class MyClass
{
    public string SomeString { get; set; }
}

public static void DeserializeMyClass(string json)
{
     // System.TypeInitializationException: The type initializer for 'NetJSONCachedSerializer`1' threw an exception
    MyClass deserialized = NetJSON.NetJSON.Deserialize<MyClass>(_json);
}
```
The stack trace is as follows:

{System.TypeInitializationException: The type initializer for 'NetJSONCachedSerializer`1' threw an exception. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: methodInfo
   at System.Reflection.Emit.ILGenerator.EmitCall(OpCode opcode, MethodInfo methodInfo, Type[] optionalParameterTypes)
   at System.Reflection.Emit.ILGenerator.Emit(OpCode opcode, MethodInfo meth)
   at NetJSON.NetJSON.Generate(Type objType)
   at NetJSON.NetJSON.NetJSONCachedSerializer`1..cctor()
   --- End of inner exception stack trace ---
   at NetJSON.NetJSON.GetSerializer[T]()
   at NetJSON.NetJSON.Deserialize[T](String json)
   at MyProject.MyType.CreateFromJson(String _json) in ...

I'm definitely using the .3.5 download from nuget, too:
![untitled](https://cloud.githubusercontent.com/assets/1375021/8148916/73f85096-12a9-11e5-82fa-83bb55b71a27.png)

**Comment by rpgmaker** [comment]
Thanks for the find. I will look into and get back to you.

**Comment by rpgmaker** [comment]
Please try again and let me know. The issue was the use of StringBuilder.Clear, it does not exists in 3.5 and the emitted code does not check to emit a different instruction.

**Comment by marksimpson82** [comment]
Working now, thanks a lot.
