### ISSUE TITLE
Primitive value de/serialization

### ISSUE THREAD

**Issue by StefanBelo** [rpgmaker/NetJSON#65]
It seems your library does not allow primitive value de/serialization. 

```c#
string json = NetJSON.NetJSON.Serialize<string>("text");
```

**Comment by rpgmaker** [comment]
The reason I did not bother with it is because it is just a single value. Did not think people will do it at all. I can easily support it  by calling the methods for the internal writing of primitive types

**Comment by StefanBelo** [comment]
But JSON standard supports just primitive types as well and people use such features in REST API for instance in asp.net mvc REST API uses Newtosoft JSON, and one's api method could return or accept in post body json parameter made by primitive value not only by object wrappers, then you have got problems because your library does not behave like the rest of JSON deser/serialization libraries.

You have got problems with both, deserialization and serialization of primitive types including enums.

**Comment by rpgmaker** [comment]
I guess  that make sense. I already have the code to do both. Just need to enable it

**Comment by rpgmaker** [comment]
Can you please re-test? I also added unit test for them

**Comment by StefanBelo** [comment]
Thank you, all works fine.
