### ISSUE TITLE
floating number rounding problem

### ISSUE THREAD

**Issue by StefanBelo** [rpgmaker/NetJSON#67]
It seems you have got quite strange problem with rounding floating numbers. For instance 1.14 in JSON is represented as 1.14000000001. 

This makes problems when you work with data comparing what is in app 1.14, but in processed json data 1.14000000001

**Comment by rpgmaker** [comment]
Sorry about that. I will look into it today.

Thanks,

**Comment by rpgmaker** [comment]
For now if you don't care about the performance for floats, you can change this code till i fix it since what i am missing is Significand/mantissa which will prevent me from generating a long floating point for the result of floats.

public static unsafe float FastStringToFloat(string numStr) {
            float val = 0.0f;
            float neg = 1;
            fixed (char* ptr = numStr) {
                char* p = ptr;
                if (*p == '-') {
                    neg = -1;
                    ++p;
                }
                while (*p != '\0') {
                    if (*p == '.') {
                        float rem = 0.0f;
                        float div = 1;
                        ++p;
                        while (*p != '\0') {
                            rem = (rem * 10.0f) + (*p - '0');
                            div *= 10.0f;
                            ++p;
                        }
                        val += rem / div;
                        return val * neg;
                    }
                    val = (val * 10.0f) + (*p - '0');
                    ++p;
                }
            }
            return val * neg;
        }


to 


public static unsafe float FastStringToFloat(string numStr) {
            return float.Parse(numStr);
}

Thanks,

**Comment by StefanBelo** [comment]
Actually in F#, the float is represented as double in C# .NET. 
F# float == C# double

Will the use of decimal solve this problem? It is quite strange that 1.14 is wrong adding those .00000001, but 1.13... and so on a good. My app is trading app with ladder prices from 1.01 to 1000 with different increment for different price ranges.

**Comment by rpgmaker** [comment]
If you use decimal I believe that might solve temporary since I let .net handle the conversion from both string and back to decimal. It does preserve value as it is.

**Comment by rpgmaker** [comment]
Let me know if it works. Then I can close this

**Comment by StefanBelo** [comment]
Yes, it works. In FastStringToDouble I declared all variables you use as decimal, and returned value is casted to double of course. So this way floating point rounding has been fixed, as decimal precision calculation are higher.

I do not know what performance implication are, you are expert in this one.

**Comment by rpgmaker** [comment]
The casting should be fine. But the divide and multiply on decimal are somewhat expensive. Maybe using simd would improve it

**Comment by rpgmaker** [comment]
I guess I can close this for now? And then create solution for float conversation later.

**Comment by StefanBelo** [comment]
Of course, you can close it. I am aware of fact that decimal operations needs more processing power and took longer, but for how much I do not know. For now this is the quick fix.

**Comment by rpgmaker** [comment]
I might be able to improve it in the future when simd is supported in .net.
