### ISSUE TITLE
Failure to parse specific JSON (skipping property names)

### ISSUE THREAD

**Issue by JohanLindvall** [rpgmaker/NetJSON#69]
With the latest release and also master, the following code fails (yy.aaaaaURL is never set). If 'aaaaaaaaaa' is changed to 'aaaaaaaaaaa', the parsing succeeds.

    class Program
    {
        private static byte[] _text;

        static void Main(string[] args)
        {
            var ss = "{\"aaaaaaaaaa\":\"52\",\"aaaaaURL\":\"x\"}";

            var yy = NetJSON.NetJSON.Deserialize<Foo>(ss);
        }
    }

    [Serializable]
    public class Foo
    {
        public string aaaaaURL { get; set; }

        public string XXXXXXXXXXXXURL { get; set; }
    }

**Comment by rpgmaker** [comment]
Thanks for the finding. I will look into it and get back to you

**Comment by rpgmaker** [comment]
Can you please retest and let me know if it is working?

Thanks,

**Comment by JohanLindvall** [comment]
Thanks, works for me

**Comment by rpgmaker** [comment]
The issue was counting offset so I can skip reading character by character which result into having a particular size of property that collides with the index check. So I had to check boundary of string to make sure I am actually at the end of correctly skipped character.

**Comment by StefanBelo** [comment]
Last time I downloaded when you said you corrected e/E problem.
