### ISSUE TITLE
Unable to deserialize byte[]

### ISSUE THREAD

**Issue by virtualsurfer** [rpgmaker/NetJSON#71]
Hi, we found an issue when deserializing byte[].

var arr1 = new byte[] { 1, 2, 3, 4, 5, 6 };
var xjson2 = NetJSON.Serialize(arr1);
var arr2 = NetJSON.Deserialize(typeof(byte[]), xjson2);

arr2 value is an empty byte[]

By the way, great job.
Thanks

**Comment by rpgmaker** [comment]
Thanks. I will look into it. Have you tried serializing it from within a
class?

**Comment by virtualsurfer** [comment]
Yes, and works fine.
But we need to handle this type in order to migrate a legacy system.
List<KeyValuePair<string, byte[]>> didnt work either.

**Comment by rpgmaker** [comment]
Ok. I will check to make sure it is handled properly.

Thanks,

**Comment by rpgmaker** [comment]
Can you try serializing using Dictionary<String, Byte[]> instead of List<>? I handle KeyValuePair only through IEnumerable and IDictionary types. Let me know what your results are.

Thanks,

**Comment by virtualsurfer** [comment]
Dictionary work just fine.
Thanks,

**Comment by rpgmaker** [comment]
Do you want still want me to make it work with a list too and be able to
serialize it without any wrapper?
On Jul 23, 2015 10:07 AM, "virtualsurfer" <notifications@github.com> wrote:

Dictionary work just fine.
Thanks,

—
Reply to this email directly or view it on GitHub
<https://github.com/rpgmaker/NetJSON/issues/71#issuecomment-124118846>.

**Comment by rpgmaker** [comment]
Closing this issue. Reopen if issue still needs to focus on specific type of serialization.

Thanks,
