### ISSUE TITLE
NetJSON not working for F# apps, infinite loop in values parsing

### ISSUE THREAD

**Issue by StefanBelo** [rpgmaker/NetJSON#74]
Please for testing add to your solution F# console app project, add reference to you library and replace it with this code to test:
```F#
open NetJSON

[<CLIMutable; NoEquality; NoComparison>]
type BaseApiResponse =
    {
        token : string
        product : string
        status : string
        error : string
    }

    member this.IsSuccess
        with get() = this.status = "SUCCESS"

[<EntryPoint>]
let main argv = 
    
    let jsonData = """{"token":"sFdDNKjLPZJSm0+gvsD1PokoJd3YzbbsClttbWLWz50=","product":"productblabla","status":"SUCCESS","error":""}"""

    let data = NetJSON.Deserialize<BaseApiResponse>(jsonData)

    printf "%A" data
    0
```
When you debug the same experience as you can see in my video. Only product property will be set in this case, well no pointer overflow in this case but data were not parse correctly.

When I add the same code to your unit test project:

```C#
        [TestMethod]
        public void StringSkippingCauseInfiniteLoop2()
        {
            string jsonData = "{\"token\":\"sFdDNKjLPZJSm0+gvsD1PokoJd3YzbbsClttbWLWz50=\",\"product\":\"productblabla\",\"status\":\"SUCCESS\",\"error\":\"\"}";

            var data = NetJSON.Deserialize<BaseApiResponse>(jsonData);
        }
```
and if I use assembly compiled in F# then test in C# ends in infinite loop. It means there is some problem how F# code is compiled to .net assembly, and how your code treats it. In your previous library there was no such problem.

This F# code for my data object/type:

```F#
namespace FsharpData

[<CLIMutable; NoEquality; NoComparison>]
type BaseApiResponse =
    {
        token : string
        product : string
        status : string
        error : string
    }

    member this.IsSuccess
        with get() = this.status = "SUCCESS"
```

is compiled to C# representation:

```C#
using Microsoft.FSharp.Core;
using System;
using System.Diagnostics;
namespace FsharpData
{
	[CLIMutable, CompilationMapping(SourceConstructFlags.RecordType), NoComparison, NoEquality]
	[Serializable]
	public sealed class BaseApiResponse
	{
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		internal string token@;
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		internal string product@;
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		internal string status@;
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		internal string error@;
		[CompilationMapping(SourceConstructFlags.Field, 0)]
		public string token
		{
			get
			{
				return this.token@;
			}
			set
			{
				this.token@ = value;
			}
		}
		[CompilationMapping(SourceConstructFlags.Field, 1)]
		public string product
		{
			get
			{
				return this.product@;
			}
			set
			{
				this.product@ = value;
			}
		}
		[CompilationMapping(SourceConstructFlags.Field, 2)]
		public string status
		{
			get
			{
				return this.status@;
			}
			set
			{
				this.status@ = value;
			}
		}
		[CompilationMapping(SourceConstructFlags.Field, 3)]
		public string error
		{
			get
			{
				return this.error@;
			}
			set
			{
				this.error@ = value;
			}
		}
		public bool IsSuccess
		{
			get
			{
				return string.Equals(this.status@, "SUCCESS");
			}
		}
		public BaseApiResponse(string token, string product, string status, string error)
		{
			this.token@ = token;
			this.product@ = product;
			this.status@ = status;
			this.error@ = error;
		}
		public BaseApiResponse()
		{
		}
	}
}
```
I cannot see any problem in such object representation, well in source code you would write through property getters/setters without using internal data, but actually .net do the same for you.

Well this attribute on properties:

[CompilationMapping(SourceConstructFlags.Field, 3)]

just keeps order of properties.

**Comment by rpgmaker** [comment]
Thanks. Just to be sure it does not work for both c# and f# code. It has nothing to do with the code generation of f#, right?

Thanks,

**Comment by StefanBelo** [comment]
Yes, in both C# and F#. But in my case I consume your library in F# code so I gave it such title.

In UnitTest it is C# code, just data object is in F# assembly.

**Comment by rpgmaker** [comment]
Does it fail if the reference am assembly written in c# or if you copy the class directly into the unit test?

Thanks,

**Comment by StefanBelo** [comment]
I referenced data assembly, that is actually use case scenario, I did not add the C# version of data in my test, it is just 4 parameters with auto properties in C# you have got almost such short source code as in F#

**Comment by rpgmaker** [comment]
Can you try it again? 

The issue was that the range method was not checking for the offset of the data, it was always reading from the beginning of the character which ptr pointed too. By adding index to the range method and including it in the check, i was able to get the correct result.


Thanks,

**Comment by StefanBelo** [comment]
There is no freezing in code but it does not work, and you actually had it working in old version.

Please watch video:

https://www.youtube.com/watch?v=ojxT5Togtrs

What I noticed, and actually was not able to test other request, was that parameter which names are keywords in C# are not parsed: for instance event

In F# there is convention:

```F#
type JsonRpcRequest<'T> =
    {
        jsonrpc : string
        ``method`` : string
        ``params`` : 'T
        id : int
    }
```

To use `` so the you can name parameter as you like even with spaces ``this is my property name ``

In C# there is convention with @ adding to start of such property name, so:

```C#
public class MarketCatalogue
{
    public @event get; set;
}
``` 
Well, maybe you have got other problem in code, but maybe it is this one.

**Comment by rpgmaker** [comment]
If @ is not been counted when property name is requested then that is the issue. The code works fine as you can see in the test. 

Does F# count it? Or does your json include @ in it?

The issue with infinite loop was clearly fixed. @ in c# is just a character for letting you use keywords as variable and members name.

Thanks,

**Comment by StefanBelo** [comment]
I think in any .net language there is some restriction for naming properties and variables, basically you cannot use key words of the language to name property. You can do use but then you have to decorate the name with @ in C# or '' in F#

As I said you some way implemented this issue, as your old library was working fine with my domain objects, Newtonsoft as well some way solves this issue.

In F# event is not language key word, so I can use it directly, but not params or method, then in F# sorce code I have to use obje.''params" <- "some data" (let's say params is mutable string)

On CLI level so what is produced by compiler, I think variables are treated with @variable. Just decompile and see interpretation of different languages assembly converted to C#, then you will see, and actually it is clear that your library is written in C# so you must deal with @variable

.http://stackoverflow.com/questions/91817/whats-the-use-meaning-of-the-character-in-variable-names-in-c

You already did it right, but now you fixed something and by accident fruck up other stuff.

**Comment by rpgmaker** [comment]
I  will make a change that allows you to disable the skip optimization that
make use of the name of properties  and we can see if it temporary solve
the problem. And later I can do more research in regards to f#. I will
check in soon.

Thanks,

**Comment by StefanBelo** [comment]
I think we do not understand each other.

**Comment by StefanBelo** [comment]
Please implement your library to deal correctly with C# naming convention.

**Comment by rpgmaker** [comment]
I have added NetJSON.UseStringOptimization which you can set to false since you are using F#. 

C# naming convention does work lol, i used @ on my properties and it still works even with the StringOptimization turned on.

Picture here to show it works fine when using @ symbol in name: http://postimg.org/image/bpg3mjwdp/

The issue is not C# naming convention, the issue is how F# deals with names :)

**Comment by rpgmaker** [comment]
If using that flag set to false works for you in f#. Then my next step is to test using f# itself like you suggested to see what type of code is generated. If possible can you set NetJSON.GenerateAssembly to true and send me what is created from f# for me to look into?

Thanks,

**Comment by StefanBelo** [comment]
A hint:

```F#
type TypeName =
    {
        mutable event : string
    }
```
and this F# source code will be compiled to .net assembly, your C# code will see this:

```C#
	public class TypeName
	{
		public string @event { get; set; }
	}
```

Your source code is C#, so when setting my TypeName object property "event" from JSON data, as in JSON it will be named event, your C# code sets property @event, as by convention in C#, event is keyword, so property must be named: @event

**Comment by StefanBelo** [comment]
Simply forgot about other languages, but implement C# naming convention to your code. Property started with @name, are equal to JSON name, so without @

**Comment by rpgmaker** [comment]
I don't understand. In the picture I just sent using @ works perfectly fine
and I did not have to modify the json string to contain any special
characters. And the string optimization option was on and not disabled.

Are saying that this does not work when using keywords that had @? And that
it is treated different from non keywords that have @?

Thanks,

**Comment by rpgmaker** [comment]
I just tried using your example with @event and it still works fine without having to change any json string and string optimization was still on and not disabled.

http://postimg.org/image/msxxfwi1j/full/

I think the issue you are having is nothing to do with C# naming convention. It clearly support all C# naming convention without any issue be it with keyword or non-keywords.

The problem is F# not C# naming convention, send me your generated Assembly by setting

NetJSON.GenerateAssembly = true and email me the dll that is generated as [...]Class.dll

Thanks,

**Comment by StefanBelo** [comment]
Ok, I will do so, but explain me. 

Your old code was working with my domain model before, now it is not working. I did not change a line in my domain code, and it works fine with Newtonsoft library written in C# as well, so there is nothing strange in my compiled assembly of domain model, as Newtonsoft works fine with it, as well as worked fine your old library, so changes must be in your latest code.

**Comment by rpgmaker** [comment]
I think the different is how I handle the string skipping. Does setting the
new flag to false remove the problem? If it does then I clearly jacked it
up :). Sorry.

Would it be possible to create a sample f# project showing this problem and
make sure it is referencing the dll or nuget.

Thanks,

**Comment by rpgmaker** [comment]
Also be sure to include all the model that is failing.

Thanks,

**Comment by StefanBelo** [comment]
I have just downloaded your update and it works with the one:

NetJSON.UseStringOptimization = false; 

So you know what to do, thanks for your help.

**Comment by rpgmaker** [comment]
Can you still set it to true and use the generate assembly flag also. So I
can see what the dll looks like for f#?

Thanks,

**Comment by StefanBelo** [comment]
Where can I find your email, or could reply on GitHub notification email?

**Comment by rpgmaker** [comment]
You can upload the dll anywhere online and just share a link to it.

Thanks,

**Comment by StefanBelo** [comment]
http://bfexplorer.net/Content/Downloads/JsonGenerated.zip

**Comment by rpgmaker** [comment]
Can you try your code again with NetJSON.UseStringOptimization = true?

Thanks,

**Comment by StefanBelo** [comment]
Great work, all works fine.

**Comment by rpgmaker** [comment]
Great to hear :)
