### ISSUE TITLE
add interface support

### ISSUE THREAD

**Issue by s-trooper** [rpgmaker/NetJSON#78]
Hi, its seems today only concrete types can be de/serialized. I get this error when i use ´´´IList<string>``` but ```List<string>``` type would work.

```
System.TypeInitializationException was unhandled
  HResult=-2146233036
  Message=The type initializer for 'NetJSONCachedSerializer`1' threw an exception.
  Source=NetJSON
  TypeName=NetJSONCachedSerializer`1
  StackTrace:
       at NetJSON.NetJSON.GetSerializer[T]()
       at NetJSON.NetJSON.Serialize[T](T value)
       at ConsoleApplication1.Program.Main(String[] args) in C:\Dev\Local\src\Sandbox\dotnet\x\ConsoleApplication1\ConsoleApplication1\Program.cs:line 12
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
```

Sourcecode:
```csharp
using System.Collections.Generic;

namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
            var myObject = new Dictionary<string, IList<string>>();
            myObject.Add("key", new List<string> { "1", "2" });

            var json = NetJSON.NetJSON.Serialize(myObject);
            var recreatedObject = NetJSON.NetJSON.Deserialize<Dictionary<string, IList<string>>>(json);
        }
    }
}
```

**Comment by hhblaze** [comment]
voting up for that!

**Comment by rpgmaker** [comment]
Thanks. I will add it to my todo list.

**Comment by rpgmaker** [comment]
For deserialization would it be OK to use an attribute to determine the final type for non collection type such as IList and IDictionary?  And for serialization it will simply get the underlying type.

Thanks

**Comment by s-trooper** [comment]
to use underlying type for serialization is a fine thing. for deserialization case i think there is no solution to make all happy. I looked on json.net and servicestack  and what they do is a funny thing, for List/Dict they basically ignore request Type and return type is a Dictonary/List. 

for this one 
```c#
IDictionary<string, IReadOnlyList<string>> res0 = TypeSerializer.DeserializeFromString<IDictionary<string, IReadOnlyList<string>>>(json0);
```
the return type is
```c#
Dictionary<string, List<string>> 
```

Imho this is an arguable solution even if ReadOnlyCollection for IReadOnlyList and List for IEnumerable may be better.

To use attribute for such common case in json as List/Dict make the API to cumbersome, imho .

**Comment by rpgmaker** [comment]
Following the same approach used for Dictionaries and Lists. What about Interface based Properties?

public IMyInterface MyProperty {get;set;}

Thanks

**Comment by rpgmaker** [comment]
Any ideas on the use of property with interface type? Should I not simply support it?

Thanks,

**Comment by s-trooper** [comment]
i don't have strong opinion about this case, for me an IList/IDict support was necessary for F# types serialization. 
But indeed i know a system that make deserialization to Interfaces e.g. Google GWT, but that is a real rare case imho. Deserialization to Interfaces means that interface serve/represent a data structure as an IList do but most time interface "hide" behavior and such cannot be deserialized from json of course ... very IMHO 

Thus i wouldn't support custom interfaces but without strong argument about.

**Comment by rpgmaker** [comment]
Would it make sense to introduce an attribute to specific the type that an interface will be converted to? It can be on the interface it self or even on the property itself

**Comment by s-trooper** [comment]
there are two things i see. this one must work as you have the concrete type, but it does not in the master version:
```
 public interface IPocoInterface   {   string Prop { get; set; }    }
 public class PocoInterfaceImpl : IPocoInterface   {   public string Prop { get; set; }    }

[TestMethod]
public void InterfacePocoDeserialize()
{
    IPocoInterface x = new PocoInterfaceImpl { Prop = "x" };
    var json = NetJSON.Serialize(x);

    IPocoInterface y = NetJSON.Deserialize<PocoInterfaceImpl>(json);
}
---
Result Message: 
Test method NetJSON.Tests.SerializeTests.InterfacePocoDeserialize threw exception: 
System.TypeInitializationException: The type initializer for 'NetJSONCachedSerializer`1' threw an exception. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: con
```

for the second one, you idea with attributes is very nice and if the cost not too large is you should implement it. but again i consider this a rare case and you shouldn't spend much performance or you man time on this IMHO.

```
[TestMethod]
public void InterfacePocoDeserialize2()
{
    IPocoInterface x = new PocoInterfaceImpl2 { Prop = "x" };
    var json = NetJSON.Serialize(x);

    // here i will get PocoInterfaceImpl as declared with an attribute
    IPocoInterface y = NetJSON.Deserialize<IPocoInterface>(json); 
}
``

**Comment by rpgmaker** [comment]
The reason the example fails is because you are trying to serialize with x which is an interface. It will try to generate serialization and deserialization logic for any object type it get. So in this case, you gave it an interface. I will look into implementing later this week and get back to you.

Thanks,

**Comment by rpgmaker** [comment]
Sorry I have not posted update on this. I will look into this upcoming week.

Thanks,

**Comment by rpgmaker** [comment]
Refer to this issue: https://github.com/rpgmaker/NetJSON/issues/97 . I believe it resolved this issue because of the support for including type information by using NetJSON.IncludeTypeInformation = true.


Thanks,
