### ISSUE TITLE
Add support for single quote JSON ?

### ISSUE THREAD

**Issue by oolaru** [rpgmaker/NetJSON#79]
Hi,

Currently if you try to deserialize a single quote JSON to an anonymous type, it will fail with: Input is not a valid JSON

{'information': {'id': '1','name': 'tariff information','providerId': '112'}}

I use this code:

 object myObject;
 using (TextReader reader = new StreamReader(FILE_PATH)) {
             myObject = NetJSON.NetJSON.Deserialize<object>(reader);
  }

Could we add support to be able to customize if we want to use single or double quotes? Or even better - to be smart enough to accept both formats for input?

Thanks!

**Comment by rpgmaker** [comment]
I could try to make it smart. But even if I do that it will still fail because I don't support anonymous type. You should try to deserialize into a dictionary string, object instead

**Comment by oolaru** [comment]
Yeah, this sounds good ! Thanks!

**Comment by rpgmaker** [comment]
I think for now I will try to make it an option enumeration to be able to quickly do substitution between the two quotes since detection will slow down the code. Then afterward I can add the third option which will be called Automatic and would be used by the caller knowing that it can have some performance impact on serialization and deserialization.

Does that makes sense?

**Comment by oolaru** [comment]
This sounds good. 
I don't pretend to understand your program, but I would like to make a suggestion.
I don't think the Automatic option will slow down the process significantly if you take into consideration the fact the JSON must be consistent with their notation: this means a JSON should be considered as valid if contains only the single quote or the double quote notation. And therefore, to detect what notation is used, means only you need to detect the first notation. So not a big deal. I hope it makes sense.
Many thanks.

**Comment by rpgmaker** [comment]
I guess that makes sense. Detecting the first and throwing an exception if all quotes does not follow suit. So I could throw exception such unbalanced json or inconsistent json exception to let the caller know what happened. 

I guess automatic will not sense when serializing because at that time there is really only two options.

Thanks,

**Comment by rpgmaker** [comment]
This first phase requires you to set NetJSON.QuoteType = NetJSONQuote.Single for your scenario. I will look into the autodetect in the coming days or possibly today.

Let me know if it works for you

Thanks,

**Comment by oolaru** [comment]
Thank you! It works. Though I need more the 2nd change: the auto detect feature. Also I use it as a nuget, so if you can push the latest I would be very thankful. Cheers!

**Comment by rpgmaker** [comment]
I have added it as a nuget package. I will let you know once I start working on the auto-detect .

Thanks,

**Comment by oolaru** [comment]
Hi,

I was wondering if I will get an update soon on this issue with autodetect. 
If not, unfortunately, I will need to switch to another JSON library because it gets critical for us. Even if I like very much NetJSON.

Thanks!

**Comment by rpgmaker** [comment]
I have not had a chance to work on it because I was busy and recently been sick. When do you need it to be available? I can work on it sooner based on when you need it.

Thanks,

**Comment by oolaru** [comment]
2 weeks would be awesome.

**Comment by rpgmaker** [comment]
I will have it done by this Sunday.

Thanks,

**Comment by rpgmaker** [comment]
I have added the auto detection of quotes. And can be found in 1.0.13 nuget release.

Thanks,

**Comment by oolaru** [comment]
Thank you very much! It works for me. I will let you know if I encounter any issue.
Highly appreciated!
