### ISSUE TITLE
Serializing a Dictionary containing a var with type short

### ISSUE THREAD

**Issue by diazrm** [rpgmaker/NetJSON#80]
When you have a Dictionary<string, object> and you populate it with an item which contains a string and a short, the latter does not reach the serialized JSON string.
For example:
```c#
namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
            short shortVar = 1;
            int intVar = 1;
            Dictionary<string, object> diccionario = new Dictionary<string, object>();
            diccionario.Add("exampleKey one", shortVar);
            string result = NetJSON.NetJSON.Serialize(diccionario);
            Console.WriteLine(result);
            diccionario.Add("exampleKey two", intVar);
            result = NetJSON.NetJSON.Serialize(diccionario);
            Console.WriteLine(result);
            Console.ReadKey();
        }
    }
}
```
Results in the following output:

![image](https://cloud.githubusercontent.com/assets/14352381/9968831/37793932-5e21-11e5-9d6f-7eede71cb468.png)

Best regards,
Manuel

**Comment by rpgmaker** [comment]
Sorry about that. The reason it failed is  because short is not part of the list when serializing dictionary string object. I will add it later today.

Thanks,

**Comment by rpgmaker** [comment]
I also added NetJSON.RegisterTypeSerializer[T](...), so if any type is missing for serializing to dictionary object, you can always register them yourself :)

E.x.

NetJSON.RegisterTypeSerializer[short](ToShortString).

Using the method above you can serialize complex type in Dictionary[string,object] if you want, but deserialization will not work same way till i also implement that into it.

Thanks,

**Comment by rpgmaker** [comment]
Let me know if it works for you.

Thanks,

**Comment by diazrm** [comment]
The fix worked perfectly. Short types now are de-serialized correctly. Another problem raised while testing this one, but I'll post it in another issue. Thank you.
