### ISSUE TITLE
Failed to parse JSON.

### ISSUE THREAD

**Issue by binis2** [rpgmaker/NetJSON#82]
Here is my data structure:

    public class Group
    {
        public int id { get; set; }
        public string name { get; set; }
        public List<Group> groups { get; set; }
    }

    public class Root
    {
        public Group group { get; set; }
    }

    public class Path
    {
        public string englishName { get; set; }
    }

    public class Event
    {
        public int id { get; set; }
        public string name { get; set; }
        public string homeName { get; set; }
        public string awayName { get; set; }
        public string start { get; set; }
        public string group { get; set; }
        public string type { get; set; }
        public string boUri { get; set; }
        public List<Path> path { get; set; }
        public string state { get; set; }
    }

    public class Criterion
    {
        public int id { get; set; }
        public string label { get; set; }
    }

    public class BetOfferType
    {
        public string name { get; set; }
    }

    public class Outcome
    {
        public int id { get; set; }
        public string label { get; set; }
        public int odds { get; set; }
        public int line { get; set; }
        public string type { get; set; }
        public int betOfferId { get; set; }
        public string oddsFractional { get; set; }
    }

    public class BetOffer
    {
        public int id { get; set; }
        public string closed { get; set; }
        public Criterion criterion { get; set; }
        public BetOfferType betOfferType { get; set; }
        public List<Outcome> outcomes { get; set; }
        public int eventId { get; set; }

    }

    public class EvntsRoot
    {
        public List<BetOffer> betoffers { get; set; }
        public List<Event> events { get; set; }
    }

Here is the parsing call

using (var file = File.OpenText(@"..\test.txt"))
            {
                var evnts = NetJSON.NetJSON.Deserialize<EvntsRoot>(file.ReadToEnd());
            }

Here is the JSON:
http://pastebin.com/PZcx8Q3Y

Thou its a valid JSON NetJSON fails to parse "events" section. I think the problem is that I did not declared a field for values in "combinableOutcomes" section. But since I don't need the values I want them skipped.

**Comment by binis2** [comment]
Indeed it is the problem. Declaring an empty class made "events" section parsed.

    //Test remove when NetJSON fixe arrives.
    public class CombinableOutcomes
    {

    }

    public class BetOffer
    {
        public int id { get; set; }
        public string closed { get; set; }
        public Criterion criterion { get; set; }
        public BetOfferType betOfferType { get; set; }
        public List<Outcome> outcomes { get; set; }
        public int eventId { get; set; }
        //Test remove when NetJSON fixe arrives.
        public CombinableOutcomes combinableOutcomes { get; set; }
    }

**Comment by rpgmaker** [comment]
Since it works on the previous version. I will reverse the quote type option which is the major change introduced recently. And create a new version on nuget temporary and try to fix the major issue in the next release.

Sorry for the break. :)

Thanks,

**Comment by binis2** [comment]
Since there is a workaround its not show stopper. The speed is essential here and you product provides it. Keep up the good work!

**Comment by rpgmaker** [comment]
I have not forgotten about this issue. Trying to rewrite the logic that skip properties.

Thanks,

**Comment by binis2** [comment]
Hey there

Any news on this issue? It is causing me a lot of troubles.

Keep up the good work! :+1:

**Comment by rpgmaker** [comment]
Sorry, I have not had a chance to look at this issue carefully. I do have plan to try to figure it out this weekend.

Thank,

**Comment by rpgmaker** [comment]
Btw, there is a high possibility that I will it done before the weekend since I kinda of already have a solution for it and I just need to code it and test.

Sorry for having to wait for a while.

Thanks,

**Comment by rpgmaker** [comment]
Can you try it again and let me know if it works? Was able to simplify the skip property logic.

Thanks,
