### ISSUE TITLE
Add support for comments

### ISSUE THREAD

**Issue by dlonagh** [rpgmaker/NetJSON#83]
Javascript comments should be ignored, but NetJSON is one of the few parsers that cannot read JSON files with comments in them.

**Comment by rpgmaker** [comment]
Thanks for the find. Will look into it.

Thanks,

**Comment by rpgmaker** [comment]
Can you give me an example of comments in a json string?

Thanks,

**Comment by dlonagh** [comment]
{
    // comment style 1
    "NetJSON": /* comment style 2 */ "FAST!"
}

**Comment by rpgmaker** [comment]
Would it be possible if you simply run this regex against your json string before calling NetJSON? Or will you be ok with me simply adding another NetJSON option to enable/disable allowing comments in the json string?

This Regex should strip out all comments both single and multiple line:

(\/\*[\s\t\r\n]*([^\/*]+)[\s\t\r\n]*\*\/) |(\/\/\s*(.+)[\r\n\s\t]{0})

**Comment by rpgmaker** [comment]
Closing this issue since a simple regex will help in removing comments.

Thanks,
