### ISSUE TITLE
Support to change the key from the variable name

### ISSUE THREAD

**Issue by krishna-kashyap** [rpgmaker/NetJSON#84]
Currently JSON.NET uses JsonProperty attribute to provide the different values for keys other than variable names. Could something similar be possible with NetJSON as well?

For eg:
```
public class SimpleObj

{
    public string name { get; set; }
    public string email  { get; set; }
}
```

This I'd like to make into a JSON as 

```
{
    "name": "ABCD",
    "mail_address": "abc@xyz.com"
}
```

**Comment by rpgmaker** [comment]
That is possible, It going to be similar same as adding an attribute which is used in place of the names retrieved from the properties and fields.

I will try it add it tomorrow.

Thanks,

**Comment by rpgmaker** [comment]
Sorry it took so long.
