### ISSUE TITLE
A value containg text and some datetime will break the deserialization

### ISSUE THREAD

**Issue by oolaru** [rpgmaker/NetJSON#85]
Hi,

There is an issue at deserialization when a text contains some datetime information:

This is the code I am referring to:
At line 30 https://github.com/rpgmaker/NetJSON/blob/master/NetJSON/AutomaticTypeConverter.cs#L30 parser matches DateTime string inside of any string and then tries to parse that at line #50.

Below is an example of JSON which can't be deserialized. Exception will be thrown:
{
   “IAmString”: “And I have data time in me: 2015-11-05T12:34:12. So I will crush inside of NetJSON library.”
}

**Comment by rpgmaker** [comment]
Thanks for the find. I will update my regex.

Thanks,

**Comment by oolaru** [comment]
Thanks!

**Comment by rpgmaker** [comment]
I just tested with the regex and your string is not even been matched. I am guess you were trying to give an example where it does matches with the .2015-11-05T12:34:12.400Z., right?

**Comment by rpgmaker** [comment]
If you need a nuget package for it, i will create it later in the afternoon/evening.

Thanks,

**Comment by oolaru** [comment]
Yes, a new package version with the fix would be great! Many thanks!

**Comment by rpgmaker** [comment]
The nuget package has been uploaded. Thanks
