### ISSUE TITLE
Nullable types not supported

### ISSUE THREAD

**Issue by binis2** [rpgmaker/NetJSON#86]
Take a look at the following code

    public class TestJSON
    {
        public List<Rec> d { get; set; }
    }

    public class Rec
    {
        public int? val { get; set; }
    }

....
`var data = NetJSON.NetJSON.Deserialize<TestJSON>("{\"d\":[{\"val\":5},{\"val\":null}]}");`
....

This is quite common scenario. NetJSON can't process it, cause the code crashes.
If I set the val property to be string (public string val { get; set; }), the second record is not processed at all. So the case cannot be worked around this way either. 

I think both cases should work (int? and string).

**Comment by rpgmaker** [comment]
That is weird. It should already support nullable. I must have changed how it worked without fully testing. Thanks for the find.

I will look into it.

**Comment by rpgmaker** [comment]
I found the issue. I support  serialization to nullable value but i have not fully implemented the logic to deserialize nullable value.


 //Logic to properly resolve nullable type when null is returned(Currently throws FatalEngineException)
            /*
            var local = il.DeclareLocal(originalType ?? type);
            var nullLabelCheck = il.DefineLabel();
            var notNullLabel = il.DefineLabel();
            //Check for null
            il.Emit(OpCodes.Ldloc, value);
            il.Emit(OpCodes.Ldstr, NullStr);
            il.Emit(OpCodes.Call, _stringOpEquality);
            il.Emit(OpCodes.Brfalse, nullLabelCheck);
            il.Emit(OpCodes.Ldnull);
            il.Emit(OpCodes.Stloc, local);
            il.Emit(OpCodes.Br, notNullLabel);
            il.MarkLabel(nullLabelCheck);
            */
