### ISSUE TITLE
DateTime Conversion

### ISSUE THREAD

**Issue by badboy22** [rpgmaker/NetJSON#88]
I want to use NetJSON as a replacement of JSON.NET. Performance of NetJSON is really awesome. But i have some trouble about DateTime conversion.

First of all; 

I try to serialize & deserialize, but it works only if i use NetJSON.NetJSONDateFormat.EpochTime, using default or iso settings failed.

You can try with this code;

public class Dummy
{
	public DateTime? DateTimeStamp;
	public int IntegerValue;
	public string StringValue;
	public List<Dummy> ListValue;
	public Dictionary<int, Dummy> DictionaryValue;
	public Dummy DummyObjValue;

	public Dummy()
	{
		ListValue = new List<Dummy>();
		DictionaryValue = new Dictionary<int, Dummy>();
		DateTimeStamp = DateTime.UtcNow;
	}

	public Dummy(DateTime? dateTime)
	{
		ListValue = new List<Dummy>();
		DictionaryValue = new Dictionary<int, Dummy>();
		DateTimeStamp = dateTime ?? DateTime.UtcNow;
	}
}

private void Test()
{
	NetJSON.NetJSON.IncludeFields = true;
	NetJSON.NetJSON.DateFormat = NetJSON.NetJSONDateFormat.EpochTime;
	
	var dummyObject = new Dummy(new DateTime(2015, 11, 08, 19, 18, 00));
	dummyObject.DictionaryValue.Add(1, new Dummy() { IntegerValue = 1 });
	dummyObject.DictionaryValue.Add(2, new Dummy() { IntegerValue = 2, DummyObjValue = new Dummy() { StringValue = "SubClass2" } });
	dummyObject.DictionaryValue.Add(3, new Dummy() { IntegerValue = 3, DummyObjValue = new Dummy() { StringValue = "SubClass3" } });
	dummyObject.DictionaryValue.Add(4, new Dummy() { IntegerValue = 4, DummyObjValue = new Dummy() { StringValue = "SubClass4" } });
	dummyObject.DictionaryValue.Add(5, new Dummy() { IntegerValue = 5, DummyObjValue = new Dummy() { StringValue = "SubClass5" } });
	dummyObject.IntegerValue = 22;
	dummyObject.StringValue = "Test";
	dummyObject.ListValue.Add(new Dummy() { StringValue = "A", DummyObjValue = new Dummy() { StringValue = "SubClass1" } });
	dummyObject.ListValue.Add(new Dummy() { StringValue = "B", DummyObjValue = new Dummy() { StringValue = "SubClass2" } });
	dummyObject.ListValue.Add(new Dummy() { StringValue = "C", DummyObjValue = new Dummy() { StringValue = "SubClass3" } });
	dummyObject.ListValue.Add(new Dummy() { StringValue = "D", DummyObjValue = new Dummy() { StringValue = "SubClass4" } });
	dummyObject.ListValue.Add(new Dummy() { StringValue = "E", DummyObjValue = new Dummy() { StringValue = "SubClass5" } });
	dummyObject.ListValue.Add(new Dummy() { StringValue = "F" });
	dummyObject.DummyObjValue = new Dummy() { IntegerValue = 55, StringValue = "Dummy" };
	
	var tmpJson = NetJSON.NetJSON.Serialize(dummyObject);
	var tmpObj = NetJSON.NetJSON.Deserialize<Dummy>(tmpJson);
}

Another problem; JSON.NET (6.0.6) has two DateTime formatter handling settings; IsoDateFormat, MicrosoftDateFormat. 

I tried to;
Serialize using JSON.NET with IsoDateFormat, Deserialize using NetJSON with Iso => Success
Serialize using NetJSON with Iso, Deserialize using JSON.NET with IsoDateFormat => Failed ({"Could not convert string to DateTime: 2015-11-8T19:18:0.0Z. Path 'DateTimeValue', line 1, position 39."})

You can try with this code;

public class Simple
{
	public DateTime DateTimeValue;

	public Simple()
	{
		DateTimeValue = new DateTime(2015, 11, 08, 19, 18, 00);
	}
}

public void NetJSONtoJSONNetTest()
{
	NetJSON.NetJSON.IncludeFields = true;
	NetJSON.NetJSON.DateFormat = NetJSON.NetJSONDateFormat.ISO;
	var tmpJson = NetJSON.NetJSON.Serialize(new Simple())
	var tmpObj = Newtonsoft.Json.JsonConvert.DeserializeObject<Simple>(tmpJson, new JsonSerializerSettings() { DateFormatHandling = DateFormatHandling.IsoDateFormat });
}

public void JSONNettoNetJSONTest()
{
	NetJSON.NetJSON.IncludeFields = true;
	NetJSON.NetJSON.DateFormat = NetJSON.NetJSONDateFormat.ISO;
	var tmpJson = Newtonsoft.Json.JsonConvert.SerializeObject(new Simple(), new JsonSerializerSettings() { DateFormatHandling = DateFormatHandling.IsoDateFormat });
	var tmpObj = NetJSON.NetJSON.Deserialize<Simple>(tmpJson);
}

I have huge data that serialized using JSON.NET with MicrosoftDateFormat and NetJSON doesn't have an alternative built-in conversion format for that. Do you have any suggestions ?

Thanks.

**Comment by rpgmaker** [comment]
What is MicrosoftDateFormat? I can add the format if needed. What is the valid iso formats for json.net? I can also add that for special cases

Thanks,

**Comment by badboy22** [comment]
{\"DateTimeValue\":\"\\/Date(1447003080000+0200)\\/\"} => JSON.NET MicrosoftDateFormat
{"DateTimeValue":"2015-11-08T19:18:00"} => JSON.NET IsoDateFormat
{"DateTimeValue":"2015-11-8T19:18:0.0Z"} => NetJSON Iso
{"DateTimeValue":"\/Date(1447010280)\/"} => NetJSON Default
{"DateTimeValue":1447003080} => NetJSON Epoch

//2015-11-08 19:18:00 (TimeZone : +0200)
//2015-11-08 17:18:00 (UTC)

Thanks.

**Comment by rpgmaker** [comment]
I will look into it. And get back to you.

Thanks,

**Comment by rpgmaker** [comment]
Can you test it again? I added another format that will generate the same type of ISO format for JSON.NET which is called NetJSONDateFormat.JsonNetISO

**Comment by badboy22** [comment]
Here are the results :)

public class Simple
{
	public DateTime DateTimeValue;
	public Simple()
	{
		DateTimeValue = new DateTime(2015, 11, 08, 19, 18, 00, DateTimeKind.Local); //+02:00
	}
}

private void Test()
{
	var tmpJson = Newtonsoft.Json.JsonConvert.SerializeObject(new Simple());
	Console.WriteLine(tmpJson);
	NetJSON.NetJSON.IncludeFields = true;
	NetJSON.NetJSON.DateFormat = NetJSON.NetJSONDateFormat.JsonNetISO;
	var tmpObj1 = Newtonsoft.Json.JsonConvert.DeserializeObject<Simple>(tmpJson);
	var tmpObj2 = NetJSON.NetJSON.Deserialize<Simple>(tmpJson);
	Console.WriteLine(tmpObj1.DateTimeValue.ToString("yyyy-MM-dd HH:mm:ss"));
	Console.WriteLine(tmpObj2.DateTimeValue.ToString("yyyy-MM-dd HH:mm:ss"));
}


//DateTimeValue = new DateTime(2015, 11, 08, 19, 18, 00, DateTimeKind.Local);
tmpJson => {"DateTimeValue":"2015-11-08T19:18:00+02:00"}
JSON.NET => 2015-11-08 19:18:00
NetJSON => 2015-11-08 17:18:00


//DateTimeValue = new DateTime(2015, 11, 08, 19, 18, 00, DateTimeKind.Utc);
tmpJson => {"DateTimeValue":"2015-11-08T19:18:00Z"}
JSON.NET => 2015-11-08 19:18:00
NetJSON => 2015-11-08 19:18:00

//DateTimeValue = new DateTime(2015, 11, 08, 19, 18, 00, DateTimeKind.Unspecified);
tmpJson => {"DateTimeValue":"2015-11-08T19:18:00"}
JSON.NET => 2015-11-08 19:18:00
NetJSON => 2015-11-08 19:18:00

Only for DateTimeKind.Utc don't match.

Thanks.

**Comment by rpgmaker** [comment]
It happens just for that specific one because I don't read the +02:00 part of the iso format

**Comment by rpgmaker** [comment]
I will try to fix it soon

Thanks,

**Comment by badboy22** [comment]
Hi,

I think you pick name JsonNetISO for JSON.NET MicrosoftDateFormat. So i re-tested again with that format;

so here are the results;

public class Simple
{
	public DateTime DateTimeValue;

	public Simple()
	{
		DateTimeValue = new DateTime(2015, 11, 08, 19, 18, 00, DateTimeKind.Local); //+02:00
	}
}

private void Test()
{
	var tmpJson = Newtonsoft.Json.JsonConvert.SerializeObject(new Simple(), new JsonSerializerSettings(){DateFormatHandling = DateFormatHandling.MicrosoftDateFormat});
	Console.WriteLine(tmpJson);
	NetJSON.NetJSON.IncludeFields = true;
	NetJSON.NetJSON.DateFormat = NetJSON.NetJSONDateFormat.JsonNetISO;
	var tmpObj1 = Newtonsoft.Json.JsonConvert.DeserializeObject<Simple>(tmpJson);
	var tmpObj2 = NetJSON.NetJSON.Deserialize<Simple>(tmpJson);
	Console.WriteLine(tmpObj1.DateTimeValue.ToString("yyyy-MM-dd HH:mm:ss"));
	Console.WriteLine(tmpObj2.DateTimeValue.ToString("yyyy-MM-dd HH:mm:ss"));
}


//DateTimeValue = new DateTime(2015, 11, 08, 19, 18, 00, DateTimeKind.Local);
tmpJson => {"DateTimeValue":"\/Date(1447003080000+0200)\/"}
JSON.NET => 2015-11-08 19:18:00
NetJSON => 2015-11-08 17:18:00


//DateTimeValue = new DateTime(2015, 11, 08, 19, 18, 00, DateTimeKind.Utc);
tmpJson => {"DateTimeValue":"\/Date(1447010280000)\/"}
JSON.NET => 2015-11-08 19:18:00
NetJSON => 2015-11-08 19:18:00

//DateTimeValue = new DateTime(2015, 11, 08, 19, 18, 00, DateTimeKind.Unspecified);
tmpJson => {"DateTimeValue":"\/Date(1447003080000+0200)\/"}
JSON.NET => 2015-11-08 19:18:00
NetJSON => 2015-11-08 17:18:00

Thanks.

**Comment by rpgmaker** [comment]
The JsonNetISO is actually suppose to match the ISO of JSON.NET. The default dateformat suppose to match the MicrosoftDateFormat. 

I will look into it and come up with a different solution.

Thanks,

**Comment by rpgmaker** [comment]
Can you try again? And see if it works. If it does not, I will have to look at it in detail more later.

Thanks,
