### ISSUE TITLE
DateTime serialization not serializing miliseconds

### ISSUE THREAD

**Issue by dejanstojanovic** [rpgmaker/NetJSON#89]
Hi,
I noticed that when I serialize the date and deserialize it back, milliseconds are lost it is always 000
Not sure if there is a way to resolve this by setting some serialization contract value or it is an actual bug :)

**Comment by rpgmaker** [comment]
It is a bug. Someone submitted something similar recently or not to long ago. I might just introduce an attribute to indicate what needs to be serialized in regards to date as previously suggested.

Thanks,

**Comment by rpgmaker** [comment]
It should work now. Try again.

**Comment by dejanstojanovic** [comment]
Hi, it works fine now with milliseconds, but is you simply compare date you are serializing and deserialized value they do not match.
I would not notice but I have one simple unit test that checks writing value and deserialized value. Dates are matching down to milliseconds, but for example Ticks are not matching.

I am not sure how are you serializing date values, maybe serializing Ticks value would be good idea. Anyway not a major issue, just something I noticed accidentally.

Good work or the serializer

**Comment by rpgmaker** [comment]
I was using ticks before. But I had to also account for timezone which ticks does not accounts for. I will play around with it a little to see  what I can do to make sure that the ticks also matches.

Thanks,
