### ISSUE TITLE
deserialize bug

### ISSUE THREAD

**Issue by nickinchina** [rpgmaker/NetJSON#90]
{"NTON15-SOCAL-SP DODGERS STORE RECEIPT: FREE CORN DOG (required)":"O"}

Hi, i just found out netjson can't parse this because of the ":".

**Comment by rpgmaker** [comment]
Thanks, I will look into it. The name of the property itself looks invalid based on json standard and will never map to a property in .net except you use netjson property attribute to rename it.

**Comment by rpgmaker** [comment]
I verified and it looks like you are indeed right, having ":" is valid within the Json key since you are allowed to use dictionary and not just classes. So I will fix it

Thanks,

**Comment by nickinchina** [comment]
i don't use .net class, just parse them into iDictionary<string,object>. this is a valid json produced in node.js.

**Comment by nickinchina** [comment]
thanks

**Comment by rpgmaker** [comment]
Try it again and let me know if it works for you
