### ISSUE TITLE
DateTime accuracy options

### ISSUE THREAD

**Issue by megakid** [rpgmaker/NetJSON#93]
Hi there,

We use Newtonsoft JSON and love the added performance here! Keep up the good work. One thing we noticed is that DateTimes get truncated to the nearest millisecond so preSerializedDateTime != postSerializedDateTime.

Any chance we could configure it similar to timezones ?

Cheers

**Comment by rpgmaker** [comment]
There are configuration for timezone similar to newtonsoft. Have you try using the NetJSON.TimeZoneFormat?

https://github.com/rpgmaker/NetJSON/wiki/Quick-Guide

NetJSON.DateFormat = Default | ISO | EpochTime (default: Default)
    - Default: Generate the standard json date representation "\Date(value)"
    - ISO: Generate iso format of date using ISO 8601 e.x 2015-07-29T14:59:08Z
    - EpochTime: Generate a unix representation of the date

    NetJSON.TimeZoneFormat = Unspecified | Utc | Local (default: Unspecified)
            - This allows you to include the timezone information as part of serialization

**Comment by rpgmaker** [comment]
NetJSON.TimeZoneFormat = Unspecified | Utc | Local (default: Unspecified)
        - This allows you to include the timezone information as part of serialization

**Comment by megakid** [comment]
Yep I realise that but if I specify UTC or JSONNet and it still truncates the nearest ms. DateTime.Now serialised and deserialised doesn't match due to that

**Comment by rpgmaker** [comment]
Good to know. I will take a look at it.

Thanks,

**Comment by rpgmaker** [comment]
Can you give an example of what you serialize that was not same? i just tried the following

NetJSON.DateFormat = NetJSONDateFormat.ISO;
            NetJSON.TimeZoneFormat = NetJSONTimeZoneFormat.Utc;
            var date = new DateTime(2010, 12, 05, 1, 1, 30, 99);
            var djson = NetJSON.Serialize(date);
            var ddate = NetJSON.Deserialize<DateTime>(djson);
            var isEqual = date == ddate;

and isEqual is true.

Thanks,

**Comment by rpgmaker** [comment]
Can you try it again, I believe it is fixed now. I also published it as a nuget package in v 1.0.15.2

Thanks,

**Comment by megakid** [comment]
Yep that works great - thanks!
