### ISSUE TITLE
AnonymousType is not supported

### ISSUE THREAD

**Issue by zyz** [rpgmaker/NetJSON#96]
var obj = new { Id=1,Name="Test" };
var json = NetJSON.NetJSON.Serialize(obj);

Non-Public Types is not supported yet 
In C#, AnonymousType is powerful.
If don't support, very bad

**Comment by rpgmaker** [comment]
Still working on the support of anonymous types. Might take a bit. I can easily support a basic anonymous type but the issue is supporting complex ones.


Thanks,

**Comment by rpgmaker** [comment]
Closing this issue because it is a duplicate of https://github.com/rpgmaker/NetJSON/issues/10 

Thanks,
